/* FeelVoyage — răspunsuri preprogramate în limba franceză (FR).
   Completează, după id, intrările din js/faq-data-*.js (titlu, cuvinte-cheie, răspuns) și textele „cel mai bun moment" din js/faq-dest.js.
   Se încarcă lazy, o dată cu restul bazei de răspunsuri, când se deschide chatul. Dacă lipsește, chatul răspunde în engleză. */
(function (root) {
    'use strict';
    const F = root.FVFAQ;
    if (!F || !F.extend) return;

    F.extend('fr', {
        "hello": { t: "👋 Bonjour", k: ["bonjour", "salut", "bonsoir", "coucou", "allo"],
          a: "Bonjour ! 👋 Je suis l'assistant virtuel de FeelVoyage. Je peux vous aider pour les destinations, les prix, les réservations et les informations de voyage. Par quoi commençons-nous ?" },
        "thanks": { t: "🙏 Merci", k: ["merci", "merci beaucoup", "je vous remercie", "remercie", "merci bien"],
          a: "Avec plaisir ! 😊 Si vous avez d'autres questions sur les destinations, les prix ou les réservations, je suis là." },
        "bye": { t: "👋 Au revoir", k: ["au revoir", "a bientot", "a plus tard", "bonne journee", "bonne soiree", "adieu", "bon voyage"],
          a: "Au revoir et bon voyage ! ✈️ Vous pouvez nous joindre à tout moment au **{phone}** ou à **{email}**." },
        "ok": { t: "👍 D'accord", k: ["d accord", "ok", "parfait", "super", "genial", "compris", "entendu", "tres bien", "nickel"],
          a: "Parfait ! 😊 Si vous avez d'autres questions sur les destinations, les prix ou les réservations, n'hésitez pas." },
        "human": { t: "🧑‍💼 Parler à un conseiller", k: ["conseiller", "agent", "personne reelle", "parler a quelqu un", "parler a un humain", "un humain", "operateur", "rappelez moi", "conseiller humain"],
          a: "Un conseiller FeelVoyage peut vous aider :\n• **Téléphone / WhatsApp :** {phone}\n• **E-mail :** {email}\n• **Horaires :** {hours}\nVous pouvez aussi envoyer le formulaire de la section **Contact** et un conseiller vous recontactera." },
        "who": { t: "🤖 Qui êtes-vous ?", k: ["qui es tu", "qui etes vous", "tu es qui", "vous etes qui", "es tu un robot", "etes vous un robot", "es tu une ia", "tu es un bot", "comment tu t appelles", "comment vous appelez vous"],
          a: "Je suis l'assistant virtuel de FeelVoyage. Quand l'assistant IA est disponible, je réponds avec un modèle d'IA ; sinon, j'utilise des réponses préparées par l'équipe. Je peux vous aider pour les destinations, les prix et les réservations, et un conseiller confirme l'offre finale." },
        "can-do": { t: "❓ Que pouvez-vous faire ?", k: ["que peux tu faire", "que pouvez vous faire", "comment peux tu m aider", "comment pouvez vous m aider", "aide moi", "aidez moi", "a quoi tu sers", "tu peux m aider"],
          a: "Je peux vous aider pour :\n• **Les destinations et les forfaits** ({count} au catalogue) et des recommandations selon le budget\n• **Les prix** (par personne, enfants, saison, options)\n• **Les réservations**, le paiement et le contact\n• **Les infos de voyage** : documents, monnaie, météo, bagages\nEssayez par exemple : « Combien coûte Rome ? » ou « Que puis-je faire avec 800 € ? »." },
        "languages": { t: "🌐 Langues", k: ["parlez vous francais", "parles tu francais", "quelles langues", "vous parlez quelles langues", "repondez en francais", "parler anglais", "parler roumain", "parler italien"],
          a: "Vous pouvez écrire en **roumain, anglais, italien, français ou espagnol** et je vous répondrai dans la même langue. Vous pouvez aussi changer la langue du site avec le bouton **RO / EN / IT / FR / ES** de l'en-tête ou du menu." },
        "joke": { t: "😄 Une blague", k: ["blague", "raconte moi une blague", "quelque chose de drole", "fais moi rire", "une blague"],
          a: "Les blagues, ce n'est pas mon fort 😄, mais les vacances, si ! Voulez-vous que je vous propose une destination selon votre budget ou le type de voyage (plage, montagne, city break) ?" },
        "off-topic": { t: "Hors sujet", k: ["python", "javascript", "ecris du code", "code source", "programmation", "bitcoin", "crypto*", "ethereum", "politique", "election", "president", "recette", "devoirs", "equation", "horoscope", "poeme"],
          a: "Je ne peux répondre qu'aux questions sur l'agence FeelVoyage, notre site et les destinations de vacances. 🌍 Demandez-moi par exemple quels forfaits sont disponibles, leurs prix ou ce qu'il y a à voir dans une destination !" },
        "complaint": { t: "⚠️ J'ai un problème", k: ["reclamation", "mecontent", "insatisfait", "probleme avec ma", "j ai un probleme", "pas satisfait", "plainte", "souci avec ma"],
          a: "Nous sommes désolés pour ce désagrément ! Pour le résoudre rapidement, écrivez à **{email}** ou appelez le **{phone}** ({hours}) en nous expliquant brièvement ce qui s'est passé. Un conseiller prendra votre dossier en charge." },
        "contact": { t: "📞 Contact", k: ["contact", "coordonnees", "comment vous contacter", "vous contacter", "joindre", "vous joindre", "entrer en contact", "contacter"],
          a: "Vous pouvez nous joindre ici :\n• **Téléphone / WhatsApp :** {phone}\n• **E-mail :** {email}\n• **Bureau :** {address}\n• **Horaires :** {hours}\n• **Facebook :** [FeelVoyage](https://www.facebook.com/share/19XnMiUthZ/?mibextid=wwXlfr)" },
        "phone": { t: "☎️ Téléphone", k: ["telephone", "numero de telephone", "appeler", "appel", "je peux appeler", "puis je appeler", "numero"],
          a: "Vous pouvez nous appeler au **{phone}** (c'est aussi notre numéro WhatsApp). Horaires : {hours}." },
        "email": { t: "✉️ E-mail", k: ["email", "e mail", "adresse email", "adresse mail", "vous ecrire", "par email", "par mail", "courriel"],
          a: "Vous pouvez nous écrire à **{email}**. Pour une offre personnalisée, indiquez-nous la destination, les dates et le nombre de voyageurs ; nous répondons sous 24 heures maximum." },
        "whatsapp": { t: "💬 WhatsApp", k: ["whatsapp", "whats app", "message whatsapp", "groupe whatsapp", "ecrire sur whatsapp"],
          a: "Vous pouvez nous écrire sur **WhatsApp** au **{phone}**. Pendant votre voyage, votre conseiller dédié crée aussi un groupe de soutien WhatsApp." },
        "address": { t: "📍 Adresse", k: ["adresse", "ou etes vous", "ou est le bureau", "ou se trouve votre bureau", "localisation", "siege", "plan d acces", "ou se trouve l agence"],
          a: "Le bureau FeelVoyage se trouve **{address}**, Roumanie. 📍 Horaires : {hours}." },
        "hours": { t: "🕘 Horaires", k: ["horaires", "heures d ouverture", "ouvert", "ferme", "dimanche", "samedi", "a quelle heure ouvrez vous", "horaires du week end", "quand etes vous ouverts"],
          a: "Horaires : **{hours}**. Nous n'avons pas d'horaires de bureau affichés le dimanche ; vous pouvez nous écrire à tout moment par e-mail ou WhatsApp et nous répondrons le jour ouvrable suivant." },
        "facebook": { t: "🔵 Facebook", k: ["facebook", "page facebook", "fb", "reseaux sociaux", "instagram", "reseaux"],
          a: "Suivez notre page Facebook pour les offres, les promotions et l'actualité : [FeelVoyage Facebook](https://www.facebook.com/share/19XnMiUthZ/?mibextid=wwXlfr) 🔵" },
        "about": { t: "ℹ️ À propos de nous", k: ["a propos de vous", "a propos de l agence", "votre histoire", "qu est ce que feelvoyage", "a propos de feelvoyage", "parlez moi de l agence", "presentation de l agence"],
          a: "FeelVoyage est une agence de voyages de **Târgu Jiu (Gorj, Roumanie)** avec **{count} destinations**, du littoral roumain à la Chine et à la Corée du Sud. Nous construisons des vacances selon votre budget et votre rythme, avec des prix transparents et un conseiller dédié." },
        "why-us": { t: "⭐ Pourquoi FeelVoyage ?", k: ["pourquoi vous choisir", "pourquoi choisir", "pourquoi vous", "avantages", "ce qui vous differencie", "pourquoi feelvoyage", "vos atouts"],
          a: "Ce que vous obtenez chez nous :\n• **Des conseils gratuits** et une offre personnalisée sous 24 heures\n• Des prix en **EUR et en lei**, avec paiement en plusieurs fois sans frais sur certains forfaits\n• **Assurance** voyage et assistance médicale en option\n• Un **conseiller dédié** et un groupe WhatsApp pendant votre voyage" },
        "consultant": { t: "🧑‍💼 Conseiller dédié", k: ["conseiller dedie", "qui va m aider", "personne de contact", "aide pendant le voyage", "assistance pendant les vacances", "assistance pendant le voyage", "soutien pendant le sejour"],
          a: "Chaque client a un **conseiller dédié**, de la première offre jusqu'à son retour à la maison. Pendant votre séjour, vous avez aussi un **groupe de soutien WhatsApp** pour une aide rapide." },
        "response-time": { t: "⏱️ Sous quel délai répondez-vous ?", k: ["combien de temps", "quand allez vous repondre", "delai de reponse", "quand me contacterez vous", "en combien de temps", "quand recevrai je l offre", "rapidite"],
          a: "Pour le formulaire de la section **Contact**, un conseiller répond sous **2 heures ouvrables** maximum. Vous recevez votre offre personnalisée sous **24 heures**." },
        "visit-office": { t: "🏢 Visiter le bureau", k: ["visiter le bureau", "puis je venir", "rendez vous", "vous rencontrer", "venir au bureau", "passer au bureau"],
          a: "Oui, vous êtes les bienvenus dans notre bureau : **{address}**. Horaires : {hours}. Pour un échange dédié, appelez d'abord le **{phone}**." },
        "reviews": { t: "⭐ Avis", k: ["avis", "temoignages", "que disent les clients", "references", "notes", "evaluations", "avis clients"],
          a: "Nous n'affichons pas d'avis sur le site pour le moment. Vous trouverez actualités et offres sur [notre page Facebook](https://www.facebook.com/share/19XnMiUthZ/?mibextid=wwXlfr) ; pour des références, demandez à un conseiller au **{phone}**." },
        "how-to-book": { t: "🎫 Comment réserver ?", k: ["comment reserver", "comment je reserve", "je veux reserver", "reservation", "reserver", "faire une reservation", "etapes de reservation"],
          a: "Réserver sur le site, étape par étape :\n1. Choisissez un forfait et appuyez sur **Détails du forfait**.\n2. Sélectionnez adultes/enfants, **dates de départ et de retour** et options : vous voyez l'estimation instantanément.\n3. Remplissez vos coordonnées et appuyez sur **Envoyer la demande de réservation**.\nUn conseiller vous contacte pour confirmer. Vous pouvez aussi réserver par téléphone (**{phone}**) ou au bureau." },
        "request-offer": { t: "📝 Demander une offre", k: ["demander une offre", "demande de devis", "devis", "offre personnalisee", "formulaire de contact", "obtenir un devis", "offre sur mesure", "formulaire d offre"],
          a: "Pour une **offre personnalisée**, remplissez le formulaire **« Envoyer une demande de devis »** de la section **Contact** (nom, téléphone, e-mail, destination souhaitée, détails). Un conseiller vous contacte sous 2 heures ouvrables maximum." },
        "book-online": { t: "💻 Réserver en ligne", k: ["reserver en ligne", "reserver sur le site", "reservation en ligne", "reserver depuis mon telephone", "reserver sur internet"],
          a: "Oui, vous pouvez envoyer une **demande de réservation** directement depuis le site ou votre téléphone, dans la fenêtre du forfait. Vous ne payez pas sur le site : un conseiller vous contacte, confirme la disponibilité et convient du paiement avec vous." },
        "no-account": { t: "👤 Faut-il un compte ?", k: ["faut il un compte", "sans compte", "compte obligatoire", "dois je m inscrire", "besoin d un compte", "compte necessaire"],
          a: "Non, le **compte est facultatif** : vous pouvez envoyer des réservations et des demandes de devis sans compte. Avec un compte, vos coordonnées se remplissent automatiquement dans les formulaires." },
        "create-account": { t: "✍️ Créer un compte", k: ["creer un compte", "creer compte", "inscription", "m inscrire", "nouveau compte", "comment m inscrire", "ouvrir un compte"],
          a: "Appuyez sur le bouton **Mon compte** dans l'en-tête (icône utilisateur) → **Inscription**. Renseignez votre nom, votre **téléphone (obligatoire)**, votre e-mail et un mot de passe d'au moins 6 caractères. Le compte fonctionne sur n'importe quel appareil avec le même e-mail et le même mot de passe." },
        "login-help": { t: "🔑 Se connecter", k: ["se connecter", "connexion", "login", "mot de passe oublie", "reinitialiser le mot de passe", "je n arrive pas a me connecter", "se deconnecter", "deconnexion"],
          a: "Connexion : bouton **Mon compte** dans l'en-tête → e-mail et mot de passe. Si vous avez oublié le mot de passe, appuyez sur **« Mot de passe oublié ? »** (saisissez d'abord votre e-mail) et vous recevrez un lien de réinitialisation. Pour vous déconnecter, ouvrez votre profil et appuyez sur **Se déconnecter**." },
        "account-benefits": { t: "🎁 Avantages du compte", k: ["avantages du compte", "pourquoi creer un compte", "a quoi sert le compte", "avantages de l inscription"],
          a: "Avec un compte : votre nom, votre téléphone et votre e-mail sont **remplis automatiquement** lors de la réservation, vous retrouvez le même compte sur **téléphone et ordinateur**, et les demandes partent plus vite. Le compte reste facultatif." },
        "cancel": { t: "❌ Annuler une réservation", k: ["annuler", "annulation", "remboursement", "rembourse", "penalite", "annuler ma reservation", "je veux annuler"],
          a: "Les conditions d'annulation et les éventuelles pénalités dépendent du forfait et sont fixées lors de la confirmation de l'offre. Pour votre cas, appelez le **{phone}** ou écrivez à **{email}** dès que possible." },
        "change-booking": { t: "🔄 Modifier une réservation", k: ["modifier ma reservation", "modifier la reservation", "changer la date", "reporter", "decaler", "changer ma reservation"],
          a: "Les modifications (dates, personnes, services) se font avec votre conseiller, selon la disponibilité et les conditions du forfait. Appelez le **{phone}** ou écrivez à **{email}**." },
        "group": { t: "👥 Groupes", k: ["groupe", "groupes", "mariage", "team building", "voyage d entreprise", "voyage scolaire", "grand groupe", "sortie de groupe"],
          a: "Oui, nous organisons des **réservations de groupe** (mariages, team building, voyages d'entreprise ou scolaires). Envoyez le formulaire de devis avec la destination, les dates et le nombre de personnes, ou appelez le **{phone}**." },
        "custom-trip": { t: "🧭 Voyage sur mesure", k: ["voyage sur mesure", "sur mesure", "itineraire personnalise", "forfait personnalise", "destination absente", "pas dans votre liste", "voyage personnalise"],
          a: "Nous ne vendons pas que des forfaits tout faits : nous construisons des **itinéraires personnalisés** selon votre budget et vos centres d'intérêt. Si votre destination n'est pas au catalogue, écrivez-nous à **{email}** ou via le formulaire de contact et nous préparerons une offre." },
        "dates-how": { t: "📅 Comment choisir les dates ?", k: ["choisir les dates", "calendrier", "date de depart", "date de retour", "de quand a quand", "selectionner les dates", "choisir la date"],
          a: "Dans la fenêtre du forfait, appuyez sur **Départ** et choisissez le jour dans le calendrier (le premier jour disponible est **demain**). La date de **Retour** se remplit avec la durée standard, et sur les forfaits flexibles vous pouvez choisir un autre jour. Les circuits guidés ont une durée fixe. Les dates s'affichent au format jj/mm/aaaa." },
        "travelers-how": { t: "🧍 Adultes et enfants", k: ["combien de voyageurs", "adultes et enfants", "ajouter des enfants", "nombre de personnes", "combien de personnes", "ajouter des personnes"],
          a: "Dans la fenêtre du forfait, sous **Nombre de voyageurs**, utilisez les boutons **− / +** pour les adultes, les enfants de 0 à 4 ans et les enfants de 5 à 12 ans. Le total et le prix par personne se mettent à jour instantanément." },
        "after-request": { t: "📨 Que se passe-t-il ensuite ?", k: ["que se passe t il ensuite", "apres l envoi", "j ai envoye la demande", "personne ne m a contacte", "pas de reponse", "je n ai pas recu de reponse", "aucune reponse"],
          a: "Après l'envoi de la demande, un conseiller FeelVoyage vous contacte (pour le formulaire de contact, sous 2 heures ouvrables). Si vous n'avez pas de nouvelles, appelez le **{phone}** ou écrivez à **{email}**." },
        "payment": { t: "💳 Modes de paiement", k: ["paiement", "payer", "comment payer", "modes de paiement", "moyens de paiement", "options de paiement"],
          a: "Modes de paiement : **virement bancaire**, **carte** (Visa / Mastercard), **paiement échelonné** (pour les forfaits de plus de 500 €) et **espèces au bureau**. Vous convenez du mode exact avec votre conseiller une fois l'offre confirmée." },
        "installments": { t: "🧾 Paiement échelonné", k: ["mensualites", "paiement echelonne", "en plusieurs fois", "sans frais", "payer en plusieurs fois", "paiement en 3 fois", "echelonner"],
          a: "Nous proposons le **paiement échelonné** pour les forfaits de plus de 500 €, et **sans frais** sur certains forfaits. Demandez les détails au **{phone}** ou à **{email}**." },
        "card-pay": { t: "💳 Payer par carte", k: ["carte", "mastercard", "visa ou mastercard", "avec visa", "payer par carte", "carte bancaire", "carte de credit"],
          a: "Oui, nous acceptons les paiements par **carte** (Visa / Mastercard). Le paiement ne se fait pas sur le site : vous le convenez avec votre conseiller après la confirmation de l'offre." },
        "advance": { t: "💶 Acompte", k: ["acompte", "arrhes", "avance", "combien a l avance", "paiement a l avance", "payer d avance"],
          a: "La nécessité d'un acompte, et son montant, dépendent du forfait et sont fixés lors de la confirmation de l'offre. Renseignez-vous auprès d'un conseiller au **{phone}**." },
        "invoice": { t: "🧾 Facture", k: ["facture", "recu", "facture entreprise", "tva", "facture pour mon entreprise", "facture societe"],
          a: "Pour une facture (y compris pour une entreprise), communiquez les informations à votre conseiller lors de la confirmation de la réservation. Détails au **{phone}** ou à **{email}**." },
        "vouchers": { t: "🎟️ Chèques-vacances", k: ["cheques vacances", "bons vacances", "bon cadeau", "carte cadeau", "ancv", "cheque cadeau"],
          a: "Pour payer avec des chèques-vacances, des cartes ou des bons cadeaux, demandez à un conseiller s'ils sont acceptés pour le forfait souhaité : **{phone}**." },
        "pay-online": { t: "🌐 Payer sur le site", k: ["payer sur le site", "paiement en ligne", "payer en ligne", "payer sur internet"],
          a: "Pour le moment, vous **ne payez pas sur le site** : il envoie votre demande, et le paiement est convenu avec votre conseiller (virement, carte, paiement échelonné ou espèces)." },
        "price-ranges": { t: "💰 Prix", k: ["prix", "tarifs", "combien ca coute", "combien coute", "cout", "tarif", "combien coutent des vacances", "budget vacances"],
          a: "Les prix dépendent de la destination, de la saison, de la durée et du nombre de voyageurs. « À partir de » signifie **par adulte, en chambre double**. À titre indicatif :" },
        "price-from": { t: "❓ Que signifie « à partir de » ?", k: ["que signifie a partir de", "prix a partir de", "prix affiche", "prix par personne", "que veut dire le prix", "le prix sur la carte"],
          a: "Le prix « à partir de » affiché sur la carte est **par adulte**, en **chambre double**, en **basse saison** et pour la **durée standard** du forfait. Pour votre total, ouvrez le forfait et choisissez personnes, dates et options : l'estimation se recalcule instantanément." },
        "single": { t: "🛏️ Chambre individuelle", k: ["supplement chambre individuelle", "chambre individuelle", "voyager seul", "une personne", "voyageur solo", "je suis seul", "voyage en solo"],
          a: "Un adulte qui voyage seul dans une chambre paie un **supplément chambre individuelle** (par nuit, selon la destination). Avec 3 adultes, l'un paie le supplément ; avec un enfant dans la chambre, il ne s'applique pas. L'estimation dans la fenêtre du forfait le calcule automatiquement." },
        "kids-price": { t: "🧒 Prix enfants", k: ["prix enfant", "tarif enfant", "reduction enfant", "remise enfant", "bebe", "enfants gratuits", "nourrisson", "prix pour un enfant", "combien pour un enfant", "prix pour les enfants", "combien paient les enfants"],
          a: "Les enfants paient un pourcentage du prix adulte selon l'âge : **Roumanie** 40 % (0–4 ans) et 70 % (5–12 ans) ; **city breaks, plage, montagne** 65 % et 85 % ; **exotique et Asie** 75 % et 85 %. Un enfant qui partage la chambre avec **un seul adulte** paie le prix plein." },
        "season-price": { t: "🌞 Saison et prix", k: ["haute saison", "basse saison", "prix saison", "prix ete", "prix hiver", "pourquoi plus cher", "quand est ce moins cher", "periode la moins chere", "quand c est le moins cher"],
          a: "Le prix « à partir de » correspond à la **basse saison**. Pendant les mois de pointe, le prix augmente (par exemple au bord de la mer en juillet–août, au ski en décembre, pour les city breaks en décembre et au printemps). Choisissez votre date de départ dans le calendrier du forfait pour voir le supplément exact." },
        "extras": { t: "➕ Services supplémentaires", k: ["extras", "services supplementaires", "options", "services additionnels", "options supplementaires", "que puis je ajouter", "supplements"],
          a: "Dans la fenêtre du forfait, vous choisissez des options : **transfert aéroport-hôtel**, **formule repas**, **billets d'attractions**, **assurance voyage**, **guide local**, **location de voiture** (et transport en autocar sur les forfaits en Roumanie). Certaines sont déjà incluses ; le prix de chacune s'affiche à côté." },
        "nights-flex": { t: "🌙 Combien de nuits ?", k: ["combien de nuits", "duree du sejour", "prolonger", "plus de nuits", "sejour plus long", "sejour plus court", "nuits", "combien de temps puis je rester"],
          a: "Sur les forfaits flexibles, vous pouvez choisir entre **2 et 14 nuits** (5 à 21 pour l'exotique et l'Asie). Le prix s'ajuste : une partie (le vol) est fixe, le reste augmente à chaque nuit. Choisissez vos dates dans le calendrier pour voir l'estimation." },
        "fixed-tours": { t: "🧭 Circuits à durée fixe", k: ["circuit", "circuits", "duree fixe", "circuit guide", "circuits guides", "visite guidee", "voyage organise"],
          a: "Les circuits guidés ont une **durée fixe** et la date de retour est calculée automatiquement. Ce sont :" },
        "price-currency": { t: "💱 Euro ou lei ?", k: ["euro ou lei", "en quelle monnaie sont les prix", "prix en euro", "prix en lei", "devise des prix", "en lei", "monnaie des prix"],
          a: "Les prix sont affichés en **EUR** et en **lei** (taux de référence : 5 lei = 1 €). Votre conseiller confirme le montant final, en lei ou en euros." },
        "hidden-fees": { t: "🔎 Frais et coûts cachés", k: ["frais caches", "couts caches", "frais supplementaires", "taxe de sejour", "taxe touristique", "ce qui n est pas inclus", "autres frais"],
          a: "Le prix affiché ne comporte aucune commission cachée. L'estimation **n'inclut pas** les dépenses personnelles, les **taxes de séjour locales** (là où elles s'appliquent) et les entrées ou excursions facultatives que vous n'avez pas sélectionnées. Un conseiller confirme l'offre finale." },
        "cheapest": { t: "🏷️ Les moins chers", k: ["moins cher*", "pas cher*", "prix le plus bas", "abordable*", "petit budget", "economique*", "le plus abordable", "bon marche"],
          a: "Nos forfaits les plus abordables (prix « à partir de », par adulte) :" },
        "priciest": { t: "💎 Luxe", k: ["plus cher*", "luxe", "premium", "haut de gamme", "deluxe", "le meilleur"],
          a: "Nos forfaits les plus exclusifs (et les plus chers) :" },
        "budget": { t: "🎯 Selon le budget", k: ["budget", "j ai", "je peux depenser", "moins de", "jusqu a", "pas plus de", "maximum", "mon budget"],
          a: "Dites-moi votre budget." },
        "discounts": { t: "🎁 Réductions et offres", k: ["reductions", "promotions", "offres speciales", "bons plans", "reservation anticipee", "derniere minute", "coupon", "code promo", "offres"],
          a: "Les promotions et actualités apparaissent sur [notre page Facebook](https://www.facebook.com/share/19XnMiUthZ/?mibextid=wwXlfr). Les prix du site sont les prix de base (basse saison) ; pour une offre personnalisée sous 24 heures, envoyez le formulaire **Contact** ou appelez le **{phone}**." },
        "price-includes": { t: "📋 Que comprend le prix ?", k: ["qu est ce qui est inclus", "que comprend le prix", "le forfait comprend", "qu est ce qui est compris", "ce qui est dans le prix", "que comprend il"],
          a: "Cela dépend du forfait : dans la fenêtre du forfait, vous voyez la liste des **Services et équipements inclus** et l'étiquette **Inclus** sur les services. Sur les forfaits hors de Roumanie, le **vol est inclus** ; en Roumanie, non. Les dépenses personnelles, les taxes locales et les options non sélectionnées ne sont pas incluses." },
        "insurance": { t: "🛡️ Assurance voyage", k: ["assurance", "assurance voyage", "assurance medicale", "assurance annulation", "ai je besoin d une assurance"],
          a: "L'**assurance voyage** et l'assistance médicale sont facultatives sur tous les forfaits (vous les ajoutez comme option, tarifée par personne et par jour). Nous la recommandons toujours, surtout hors de l'UE. Dans l'UE, vous pouvez aussi avoir la carte européenne d'assurance maladie, mais elle ne couvre pas tout (par exemple le rapatriement)." },
        "tickets-extra": { t: "🎫 Billets d'attractions", k: ["billets d attractions", "billets", "droits d entree", "billets de musee", "coupe file", "tickets d entree", "entrees"],
          a: "Les billets d'attractions peuvent être ajoutés comme **service supplémentaire** (par personne, selon la destination et la durée). Certains forfaits incluent déjà une entrée, par exemple Rome : **billet coupe-file pour le Colisée**." },
        "car-rental": { t: "🚗 Location de voiture", k: ["location de voiture", "louer une voiture", "location voiture", "voiture de location", "louer un vehicule", "louer auto"],
          a: "La **location de voiture** s'ajoute comme option (tarifée par jour et par voiture ; une voiture pour 4 personnes maximum). Elle n'est pas disponible aux **Maldives**, en **Chine** ni pour le **safari au Kenya**." },
        "transfer": { t: "🚐 Transfert aéroport", k: ["transfert", "transfert aeroport", "transfert hotel", "de l aeroport a l hotel", "navette"],
          a: "Le **transfert aéroport-hôtel** s'ajoute comme option (tarifé par personne, aller-retour). Aux **Maldives**, le transfert (bateau rapide ou hydravion) coûte plus cher." },
        "guide": { t: "🧑‍🏫 Guide local", k: ["guide", "guide local", "guide touristique", "guide prive", "je veux un guide"],
          a: "Un **guide local privé** s'ajoute comme option (tarifé par groupe et par jour, jusqu'à 3 jours). Sur les circuits guidés (par exemple Tokyo, Pékin, safari au Kenya), le guide est déjà **inclus**." },
        "meals": { t: "🍽️ Repas", k: ["repas", "nourriture incluse", "demi pension", "pension complete", "petit dejeuner", "diner", "dejeuner", "qu est ce qu on mange"],
          a: "Les repas dépendent du forfait : **tout compris**, pension complète, demi-pension ou simple petit-déjeuner (voir la carte du forfait). Là où les repas ne sont pas inclus, vous pouvez ajouter une **formule repas** en option." },
        "destinations-list": { t: "🌍 Destinations", k: ["destinations", "quelles destinations", "liste des destinations", "ou puis je aller", "toutes les destinations", "quels forfaits avez vous", "forfaits", "forfaits de voyage"],
          a: "Nous avons **{count} destinations** au catalogue : **Roumanie** (Delta du Danube, Poiana Brașov, Bran, Transfăgărășan, Défilé du Danube, Maramureș, Sibiu et Sighișoara, Mamaia), **city breaks en Europe** (Rome, Barcelone, Londres, Prague, Vienne, Paris), **plage et montagne** (Santorin, Alpes suisses), **exotique** (Maldives, Kenya, Bali, Tokyo, Dubaï, Cappadoce, New York) et **Chine et Corée du Sud** (Pékin, Shanghai, Zhangjiajie, Séoul, Busan, Jeju)." },
        "romania": { t: "🇷🇴 Roumanie", k: ["roumanie", "en roumanie", "vacances en roumanie", "destinations en roumanie", "voyage en roumanie", "partir en roumanie"],
          a: "Découvrez la beauté de la Roumanie ! 🇷🇴 Nos forfaits dans le pays :" },
        "europe": { t: "🇪🇺 Europe", k: ["europe", "en europe", "europeen", "destinations europeennes", "city break europe", "vacances en europe"],
          a: "Nos city breaks les plus populaires en Europe : 🇪🇺" },
        "exotic": { t: "🏝️ Exotique", k: ["exotique*", "exotic*", "destinations exotiques", "vacances exotiques", "voyage lointain", "destination lointaine", "autre continent", "outre mer"],
          a: "Destinations exotiques et lointaines : 🏝️" },
        "beach": { t: "🏖️ Plage et mer", k: ["plage", "mer", "bord de mer", "soleil", "vacances au soleil", "vacances a la plage", "sable", "ile", "iles"],
          a: "Pour la plage et la mer, je recommande : 🏖️" },
        "mountain": { t: "⛰️ Montagne", k: ["montagne", "montagnes", "ski", "skier", "randonnee", "vacances a la montagne", "alpin"],
          a: "Pour la montagne et la nature : ⛰️" },
        "city": { t: "🏙️ City break", k: ["city break", "city breaks", "villes", "capitales", "vacances urbaines", "escapade urbaine", "sejour urbain", "visite de ville"],
          a: "Pour un city break : 🏙️" },
        "asia": { t: "🐉 Chine et Corée", k: ["chine", "coree", "coree du sud", "asie", "chinois", "en asie", "vacances en asie"],
          a: "Pour la Chine et la Corée du Sud : 🐉" },
        "romantic": { t: "💑 Romantique", k: ["voyage de noces", "lune de miel", "couple", "romantique", "anniversaire de mariage", "pour deux", "fiancailles", "escapade romantique"],
          a: "Pour une escapade romantique (lune de miel, anniversaire) : 💑" },
        "family": { t: "👨‍👩‍👧 En famille", k: ["famille", "avec des enfants", "avec enfants", "vacances en famille", "voyage en famille", "jeunes enfants", "pour la famille", "familial"],
          a: "Pour des vacances en famille, je vous suggère : 👨‍👩‍👧" },
        "adventure": { t: "🧗 Aventure", k: ["aventure", "nature", "adrenaline", "vacances actives", "paysages", "faune", "plein air"],
          a: "Pour l'aventure et la nature : 🧗" },
        "culture": { t: "🏛️ Culture et histoire", k: ["culture", "histoire", "musees", "monuments", "architecture", "patrimoine", "voyage culturel"],
          a: "Pour la culture et l'histoire : 🏛️" },
        "weekend": { t: "📆 Pour un week-end", k: ["week end", "weekend", "court sejour", "escapade", "quelques jours", "petite escapade", "vacances courtes"],
          a: "Pour une petite escapade (2–3 nuits) : 📆" },
        "longtrip": { t: "🗓️ Long séjour", k: ["long voyage", "deux semaines", "longues vacances", "long sejour", "une semaine", "pour une semaine", "beaucoup de temps"],
          a: "Pour un séjour plus long (8 nuits et plus) : 🗓️" },
        "winter": { t: "❄️ Hiver", k: ["hiver", "noel", "nouvel an", "vacances d hiver", "vacances hivernales", "neige", "fetes de fin d annee"],
          a: "Pour des vacances d'hiver (neige ou soleil, selon vos envies) : ❄️" },
        "summer": { t: "☀️ Été", k: ["ete", "vacances d ete", "grosse chaleur", "en juillet", "en aout", "juillet", "aout", "chaud"],
          a: "Pour des vacances d'été : ☀️" },
        "allinclusive": { t: "🍹 Tout compris", k: ["tout compris", "all inclusive", "tout inclus", "boissons incluses", "all in"],
          a: "Forfaits **tout compris** : 🍹" },
        "flight-included": { t: "✈️ Le vol est-il inclus ?", k: ["vol inclus", "en avion", "billet d avion", "vol", "vols", "prix du vol", "incluez vous les vols", "avec vol"],
          a: "Sur les forfaits hors de Roumanie, le **vol est inclus** (voir « Vol inclus » dans la liste des services inclus). Sur les forfaits en Roumanie, le transport n'est pas inclus, mais vous pouvez ajouter un **transport en autocar** en option. Votre conseiller confirme les détails du vol (aéroport, horaires)." },
        "docs": { t: "🛂 Documents", k: ["documents", "passeport", "carte d identite", "quels documents", "documents de voyage", "validite du passeport", "ai je besoin d un passeport"],
          a: "Dans l'**UE et l'espace Schengen** (Suisse comprise), vous pouvez généralement voyager avec une **carte d'identité** en cours de validité ou un passeport. Pour le **Royaume-Uni** et les pays hors d'Europe (Asie, Afrique, États-Unis, Émirats), il faut un **passeport valide**, généralement encore valable 6 mois après votre retour, et certains pays exigent un visa ou une autorisation électronique. Vérifiez toujours les exigences officielles selon votre nationalité (pour les citoyens roumains : le guide de voyage du ministère roumain des Affaires étrangères) avant de partir." },
        "visa": { t: "🛃 Visa", k: ["visa", "visas", "autorisation electronique", "eta", "etias", "e visa", "evisa", "ai je besoin d un visa"],
          a: "La nécessité d'un visa dépend du pays et de votre nationalité, et elle peut changer. Par exemple, le **Royaume-Uni** (ETA), les **États-Unis** (ESTA), le **Kenya** (autorisation électronique) et l'**Indonésie / Bali** (visa à l'arrivée, taxe touristique) ont des règles particulières. Consultez le site officiel du ministère des Affaires étrangères et demandez à un conseiller au **{phone}**." },
        "vaccines": { t: "💉 Vaccins et santé", k: ["vaccin", "vaccins", "vaccination", "paludisme", "malaria", "sante", "medecin", "ai je besoin d un vaccin", "precautions sanitaires"],
          a: "Pour les destinations exotiques (par exemple Kenya, Bali), nous recommandons de consulter votre médecin ou un centre de médecine des voyages **4 à 6 semaines avant** le départ. Les recommandations officielles (ministère des Affaires étrangères, OMS) changent, vérifiez-les avant de partir. Nous ne pouvons pas donner de conseils médicaux." },
        "luggage": { t: "🧳 Bagages", k: ["bagage", "bagages", "valise", "bagage a main", "bagage en soute", "limite de poids", "combien de kilos", "poids autorise"],
          a: "Les règles de bagages dépendent de la **compagnie aérienne** et du tarif de votre billet ; vérifiez-les avant de voler. En bagage à main, les liquides sont généralement limités à des contenants de **100 ml**, dans un sac transparent." },
        "airport-time": { t: "🕐 Quand arriver à l'aéroport", k: ["quand arriver", "combien de temps a l avance", "arrivee a l aeroport", "enregistrement", "embarquement", "a quelle heure etre a l aeroport"],
          a: "Pour les vols internationaux, arrivez à l'aéroport **2 à 3 heures avant**. Beaucoup de compagnies permettent l'**enregistrement en ligne** 24 à 48 heures à l'avance. L'aéroport et les horaires exacts figurent dans les documents de votre conseiller." },
        "money": { t: "💶 Monnaie et change", k: ["change", "ou changer de l argent", "quelle monnaie", "argent a l etranger", "monnaie locale", "especes a l etranger", "quelle devise utilise t on"],
          a: "Dans la zone euro (Rome, Paris, Vienne, Barcelone...) on utilise l'**euro**. Autres monnaies : livre sterling (Londres), couronne tchèque (Prague), franc suisse (Suisse), dollar américain (New York), yen (Japon), won (Corée), dirham (Dubaï), yuan (Chine), roupie indonésienne (Bali), shilling kényan (Kenya), rufiyaa (Maldives ; les dollars américains y sont largement acceptés). Changez dans les banques ou les bureaux de change, pas à l'aéroport." },
        "cards": { t: "💳 Cartes à l'étranger", k: ["carte a l etranger", "frais de carte", "payer par carte a l etranger", "prevenir la banque", "revolut", "apple pay", "carte dans un autre pays"],
          a: "Les cartes **Visa / Mastercard** sont largement acceptées. Renseignez-vous sur les frais de votre banque pour les paiements dans d'autres devises, prévenez votre banque que vous voyagez et emportez un peu d'**espèces**. En **Chine**, les paiements mobiles (Alipay / WeChat Pay) sont très courants : configurez-les avant de partir." },
        "roaming": { t: "📶 Internet et itinérance", k: ["roaming", "itinerance", "internet a l etranger", "esim", "carte sim", "donnees mobiles", "wifi", "data a l etranger"],
          a: "Dans l'**UE/EEE**, l'itinérance est facturée comme chez vous (sous réserve de la politique de votre opérateur). Hors de l'UE, elle peut coûter cher : choisissez un forfait d'itinérance, une **eSIM** ou une carte SIM locale. En **Chine**, certaines applications (Google, WhatsApp) peuvent être restreintes : préparez-vous à l'avance." },
        "adapters": { t: "🔌 Prises et adaptateurs", k: ["prise", "prises", "adaptateur", "voltage", "tension", "chargeur", "type de prise"],
          a: "**UE :** prises compatibles (type C/F). **Royaume-Uni, Dubaï, Kenya :** type G. **Suisse :** type J. **États-Unis et Japon :** type A/B, 100–120 V. **Chine :** type A/C/I. **Corée du Sud et Bali :** type C/F, 230 V. **Maldives :** type D/G/J. Le plus simple : un **adaptateur universel**." },
        "timezone": { t: "🕰️ Fuseaux horaires et décalage", k: ["fuseau horaire", "decalage horaire", "jet lag", "heure locale", "jetlag"],
          a: "Différences approximatives avec la Roumanie (elles varient avec l'heure d'été) : Europe centrale −1 h ; Londres −2 h ; Grèce 0 ; Turquie 0/+1 h ; Dubaï +1/+2 h ; Kenya 0/+1 h ; Maldives +2/+3 h ; Pékin, Shanghai, Bali +5/+6 h ; Tokyo, Séoul +6/+7 h ; New York −7 h. Pour les longs vols, décalez votre rythme de sommeil 1 à 2 jours avant." },
        "packing": { t: "🎒 Que dois-je emporter ?", k: ["que emporter", "liste de bagages", "que dois je emporter", "que dois je prendre", "comment faire sa valise", "quels vetements", "que faut il prendre", "faire ma valise"],
          a: "L'essentiel : **documents et assurance**, argent/carte, téléphone + chargeur + **adaptateur**, médicaments personnels, vêtements en couches adaptés à la météo, **crème solaire**, chaussures confortables et un petit sac pour les excursions. Consultez la météo quelques jours avant." },
        "kids-travel": { t: "👶 Voyager avec des enfants", k: ["voyager avec des enfants", "enfant en avion", "mineurs", "autorisation parentale", "documents enfant", "documents des enfants", "mineur"],
          a: "Chaque enfant a besoin de son **propre document** (carte d'identité ou passeport). Si un mineur voyage à l'étranger avec un seul parent ou avec une autre personne, l'**autorisation notariée de l'autre parent** et d'autres papiers peuvent être exigés : vérifiez les règles auprès de la **Police aux frontières** avant de partir." },
        "accessibility": { t: "♿ Accessibilité", k: ["handicap", "accessibilite", "fauteuil roulant", "mobilite reduite", "besoins specifiques", "personne handicapee", "pmr"],
          a: "Indiquez-nous vos besoins à l'avance (mobilité réduite, fauteuil roulant, etc.) dans le formulaire **Contact** ou au **{phone}**. Nous vérifions l'accessibilité auprès de nos partenaires, mais tous les lieux ne sont pas accessibles." },
        "diet": { t: "🥗 Allergies et régime", k: ["allergies", "allergie", "vegetarien", "vegan", "vegetalien", "sans gluten", "halal", "casher", "regime", "intolerance", "regime alimentaire"],
          a: "Mentionnez vos allergies ou besoins alimentaires (végétarien, sans gluten, halal, etc.) dans votre demande de réservation. Les hôtels peuvent généralement adapter le menu si on les prévient à l'avance, mais nous ne pouvons pas garantir tous les régimes partout." },
        "safety": { t: "🔒 Sécurité", k: ["est ce sur", "securite", "dangereux", "risques", "avis aux voyageurs", "est ce dangereux", "conseils aux voyageurs"],
          a: "Avant de partir, consultez les **conseils aux voyageurs** de votre ministère des Affaires étrangères pour la destination, souscrivez une **assurance voyage**, gardez des copies de vos documents et surveillez vos affaires dans les endroits bondés. Votre conseiller peut partager ce qu'il sait de la destination." },
        "weather": { t: "🌦️ Météo", k: ["quel temps fait il", "meteo", "previsions", "quelle temperature", "climat", "comment est le temps"],
          a: "La météo dépend de la destination et du mois. Dites-moi la destination (par exemple « Quel est le meilleur moment pour Bali ? ») et je vous donnerai des détails saisonniers. Quelques jours avant le départ, consultez les **prévisions**." },
        "best-time-general": { t: "📅 Meilleure période", k: ["meilleur moment pour partir", "quand partir", "quel mois est le meilleur", "meilleure periode", "quand vaut il la peine d y aller", "quel mois partir"],
          a: "En bref : **plage** juin–septembre ; **ski** décembre–mars ; **city breaks** avril–juin et septembre–octobre ; **Maldives et Dubaï** novembre–avril ; **safari au Kenya** juillet–octobre. Dites-moi la destination (par exemple « Quand partir à Bali ? ») et je vous donnerai des détails." },
        "tipping": { t: "🪙 Pourboire", k: ["pourboire", "pourboires", "combien laisser de pourboire", "laisser un pourboire", "tip"],
          a: "En gros : **États-Unis (New York)** 15–20 % au restaurant ; **Europe** 5–10 % si le service n'est pas inclus sur l'addition ; **Japon et Corée du Sud** pas de pourboire ; au **Kenya, à Bali, aux Maldives et à Dubaï**, environ 10 % sont appréciés (vérifiez si le service est déjà inclus)." },
        "delays": { t: "⏳ Vol retardé ou annulé", k: ["vol retarde", "vol annule", "vol rate", "bagage perdu", "indemnisation", "retard de vol", "j ai rate mon vol"],
          a: "Si votre vol est retardé ou annulé, contactez d'abord la **compagnie aérienne** et conservez vos documents. Vous pouvez aussi nous joindre au **{phone}**. Dans l'UE, les passagers ont des droits (assistance, parfois indemnisation), et l'**assurance voyage** peut couvrir un bagage perdu ou des frais supplémentaires." },
        "language-site": { t: "🌐 Changer la langue du site", k: ["changer de langue", "changer la langue", "modifier la langue", "langue du site", "traduire le site", "site en francais", "passer en francais"],
          a: "Changez la langue du site avec le bouton **RO / EN / IT / FR / ES** de l'en-tête (sur téléphone, dans le menu). Les textes, les forfaits et le chat se traduisent instantanément." },
        "dark-mode": { t: "🌙 Mode sombre", k: ["mode sombre", "mode clair", "theme sombre", "theme", "changer de theme", "mode nuit"],
          a: "Passez du mode **clair au mode sombre** avec le bouton **lune / soleil** de l'en-tête. Par défaut, le site suit le réglage de votre téléphone ou ordinateur jusqu'à ce que vous choisissiez." },
        "filters": { t: "🔎 Recherche et filtres", k: ["filtres", "filtre", "recherche", "comment chercher", "trouver une destination", "filtre de budget", "rechercher"],
          a: "En haut, dans la zone de recherche, choisissez la **destination**, le **type de vacances** et votre **budget maximum**. Dans la section **Destinations et forfaits**, il y a aussi des boutons de catégorie (Roumanie, plage, montagne, city break, exotique, Chine et Corée). Sur téléphone, les boutons défilent latéralement." },
        "package-details": { t: "🖼️ Détails du forfait", k: ["details du forfait", "galerie photo", "photos", "images", "ouvrir le forfait", "voir le forfait"],
          a: "Appuyez sur **Détails du forfait** sur une carte de destination : vous verrez la galerie de 4 photos, la description, les services, le **calculateur de prix** (personnes, dates, options) et le formulaire de réservation." },
        "mobile": { t: "📱 Sur mon téléphone", k: ["application", "appli", "application mobile", "sur mon telephone", "telecharger", "site mobile", "y a t il une application"],
          a: "Nous n'avons pas d'application : le site est **optimisé pour les téléphones** et fonctionne directement dans votre navigateur. Vous pouvez l'ajouter à votre écran d'accueil depuis le menu du navigateur (« Ajouter à l'écran d'accueil »)." },
        "chat-help": { t: "💬 Comment utiliser le chat ?", k: ["comment fonctionne le chat", "comment utiliser le chat", "aide chat", "chat", "assistant virtuel", "discussion en ligne"],
          a: "Écrivez votre question ou appuyez sur les boutons suggérés. Quand l'assistant IA est disponible, je réponds librement aux questions sur l'agence, le site et les destinations ; sinon, j'utilise des réponses préparées. Je peux aussi ouvrir des forfaits pour vous avec le bouton **« Voir le forfait »**." },
        "counter": { t: "❤️ Compteur « Voyageurs heureux »", k: ["voyageurs heureux", "compteur", "qu est ce que le compteur", "compteur de voyageurs"],
          a: "**« Voyageurs heureux »** est un compteur en direct : chaque clic ajoute 1, et tous les visiteurs de la page voient le nombre changer en temps réel." },
        "privacy": { t: "🔐 Données personnelles", k: ["donnees personnelles", "rgpd", "confidentialite", "protection des donnees", "mes donnees", "cookies", "mes donnees sont elles en securite"],
          a: "Les informations des formulaires (nom, téléphone, e-mail) servent à vous contacter au sujet de votre demande. **N'écrivez pas de données personnelles dans le chat** : utilisez les formulaires. Le compte est facultatif. Pour des précisions sur vos données, écrivez à **{email}**." },
        "tech-issue": { t: "🛠️ Le site ne fonctionne pas", k: ["ne fonctionne pas", "erreur", "ne se charge pas", "probleme technique", "bug", "bloque", "site ne fonctionne pas", "page blanche"],
          a: "Essayez : **recharger la page** (Ctrl+F5, ou tirer vers le bas sur téléphone), ouvrir le site dans un autre navigateur ou en navigation privée. Si le problème persiste, écrivez à **{email}** avec une capture d'écran et l'appareil utilisé." }
    });

    F.extendDest('fr', {
        "delta-dunarii": "Idéal en mai–juin et en septembre : temps doux, beaucoup d'oiseaux migrateurs et moins de moustiques qu'en juillet. L'été est chaud, l'hiver froid et calme.",
        "poiana-brasov": "L'hiver (décembre–mars) pour le ski et le spa ; l'été (juin–septembre) pour la randonnée et le télécabine. Les fêtes de fin d'année sont la période la plus fréquentée.",
        "bran-brasov": "La fin du printemps et l'automne (mai–juin, septembre–octobre) sont idéaux ; l'hiver est joli mais froid. Les week-ends d'été, le château est très fréquenté.",
        "transfagarasan": "La route de haute altitude n'est généralement ouverte qu'en été, environ de juillet à octobre. Vérifiez l'état des routes avant de partir ; il peut faire froid en haut même en août.",
        "cazanele-dunarii": "De mai à septembre pour la croisière sur le Danube ; le printemps et l'automne sont agréables, tandis que juillet–août est chaud.",
        "maramures": "Juin–octobre : beau temps pour les villages et la randonnée ; l'automne apporte de belles couleurs et des fêtes traditionnelles. Les hivers sont froids et enneigés.",
        "sibiu-sighisoara": "Mai–juin et septembre–octobre sont les plus agréables ; juillet accueille le Festival de la Sighișoara médiévale et décembre le célèbre marché de Noël de Sibiu.",
        "mamaia-constanta": "Juin–septembre. Juillet–août est la période la plus chaude, la plus fréquentée (et la plus chère) ; juin et septembre sont plus calmes, avec une mer encore agréable.",
        "roma": "Avril–juin et septembre–octobre : températures agréables. Juillet–août est très chaud ; l'hiver est plus calme et moins cher. Réservez à l'avance les entrées du Colisée et du Vatican.",
        "barcelona": "Mai–juin et septembre–octobre : beau temps et moins de touristes. L'été est chaud et idéal pour la plage ; l'hiver est doux.",
        "londra": "De mai à septembre, il fait plus chaud et plus sec, mais il peut pleuvoir à tout moment : emportez un parapluie. Décembre offre illuminations et marchés de Noël mais il fait froid.",
        "praga": "Avril–mai et septembre–octobre sont idéaux ; décembre offre de beaux marchés de Noël mais il fait froid. L'été est très fréquenté.",
        "viena": "Avril–mai et septembre–octobre pour les balades et les musées ; décembre apporte les marchés de Noël (froid, mais ambiance unique).",
        "paris": "Avril–juin et septembre–octobre sont les plus beaux mois ; l'été est bondé, l'hiver moins cher et plus calme. Réservez à l'avance les billets de la tour Eiffel et du Louvre.",
        "maldive-deluxe": "Décembre–avril est la saison sèche, la plus ensoleillée (et la plus chère). Mai–novembre est la saison des pluies, avec des prix plus bas et de courtes averses.",
        "kenya-safari": "Juillet–octobre est la saison de la Grande Migration au Masai Mara (la plus prisée) ; janvier–février est sec et bon pour le safari. Avril–mai est la saison des pluies. Emportez des vêtements de couleurs neutres.",
        "bali": "Avril–octobre est la saison sèche, la meilleure ; juillet–août est bondé. Novembre–mars est pluvieux mais chaud. Dans les temples, habillez-vous de façon décente (épaules et genoux couverts).",
        "santorini": "Mai–octobre ; juin et septembre offrent le meilleur équilibre entre météo, prix et affluence. Juillet–août est cher et animé ; beaucoup d'établissements ferment l'hiver.",
        "tokyo": "Mars–avril pour les cerisiers en fleurs (sakura) et octobre–novembre pour les feuilles d'automne. L'été est chaud et humide et juin est la saison des pluies. Le pourboire n'est pas d'usage au Japon.",
        "alpi-elvetia": "Juin–septembre pour la randonnée et les vues ; décembre–mars pour le ski. Avril–mai et octobre–novembre sont plus calmes, mais certains téléphériques sont fermés. La Suisse est chère.",
        "dubai": "Novembre–mars (20–30 °C) est idéal ; décembre est le mois le plus cher. L'été dépasse 40 °C, les activités se font donc en intérieur. Respectez le code vestimentaire et les lois locales.",
        "cappadocia": "Avril–juin et septembre–octobre sont les plus beaux mois. Les vols en montgolfière dépendent du vent et peuvent être annulés ; l'hiver est froid avec de possibles chutes de neige, mais le paysage est spectaculaire.",
        "newyork": "Avril–juin et septembre–novembre sont les meilleurs mois. Décembre offre des illuminations mais il fait froid et c'est cher ; juillet–août est très chaud et humide. Le pourboire aux États-Unis est de 15–20 %.",
        "beijing-marele-zid": "Avril–mai et septembre–octobre. L'hiver est très froid, l'été torride. Évitez la semaine de la fête nationale (1er–7 octobre) et le Nouvel An chinois : c'est extrêmement bondé.",
        "shanghai-metropola-futurului": "Mars–mai et septembre–novembre sont les plus beaux mois. Juin–juillet est humide avec de fréquentes pluies, et l'été est chaud et moite.",
        "zhangjiajie-avatar": "Avril–octobre ; le printemps et l'automne offrent des paysages brumeux et de belles couleurs. L'été est bondé et pluvieux, l'hiver froid avec de la neige.",
        "seoul-coreea": "Avril–mai (cerisiers en fleurs) et septembre–novembre (feuillage d'automne). Juillet–août apporte les pluies de mousson ; l'hiver est froid et sec. Le pourboire n'est pas d'usage.",
        "busan-coreea": "Mai–juin et septembre–octobre ; les plages sont animées en juillet–août mais il fait humide. L'hiver est plus doux qu'à Séoul.",
        "jeju-insula-vulcanica": "Avril (champs de colza en fleurs) et septembre–octobre sont les meilleurs mois. L'été est humide et des typhons sont possibles (août–septembre) ; l'hiver est doux mais venteux."
    });
})(typeof window !== 'undefined' ? window : globalThis);
