/* FeelVoyage — răspunsuri preprogramate, partea 3: informații generale de călătorie și folosirea site-ului.
   Informațiile despre acte, vize, vaccinuri și taxe se pot schimba: răspunsurile trimit mereu la surse oficiale. */
(function (root) {
    'use strict';
    const F = root.FVFAQ;
    if (!F) return;

    F.register([

        /* ==================================================== INFORMAȚII DE CĂLĂTORIE ==================================================== */
        { id: 'docs', topic: true, next: ['visa', 'kids-travel', 'insurance'],
          ro: { t: '🛂 Acte necesare', k: ['acte necesare', 'buletin', 'pasaport', 'ce acte', 'documente de calatorie', 'carte de identitate', 'valabilitate pasaport', 'ce documente'], a: `În **UE și spațiul Schengen** (inclusiv Elveția) poți călători, de regulă, cu **cartea de identitate** valabilă sau cu pașaport. Pentru **Regatul Unit** și țările din afara Europei (Asia, Africa, SUA, Emiratele) ai nevoie de **pașaport valabil**, de obicei încă 6 luni după întoarcere, iar unele țări cer viză sau autorizare electronică. Verifică mereu cerințele oficiale (MAE – Ghidul călătorului) înainte de plecare.` },
          en: { t: '🛂 Documents', k: ['documents', 'passport', 'id card', 'what documents', 'travel documents', 'passport validity', 'do i need a passport'], a: `In the **EU and Schengen area** (including Switzerland) you can usually travel with a valid **ID card** or a passport. For the **United Kingdom** and countries outside Europe (Asia, Africa, the USA, the Emirates) you need a **valid passport**, usually valid for 6 more months after your return, and some countries require a visa or electronic authorisation. Always check the official requirements (the Romanian MFA travel guide) before you leave.` },
          it: { t: '🛂 Documenti', k: ['documenti', 'passaporto', 'carta d identita', 'quali documenti', 'documenti di viaggio', 'validita del passaporto', 'serve il passaporto'], a: `Nell'**UE e nello spazio Schengen** (Svizzera inclusa) di solito si viaggia con **carta d'identità** valida o passaporto. Per il **Regno Unito** e i Paesi extraeuropei (Asia, Africa, USA, Emirati) serve un **passaporto valido**, di solito ancora 6 mesi dopo il ritorno, e alcuni Paesi richiedono visto o autorizzazione elettronica. Controlla sempre i requisiti ufficiali (guida del viaggiatore del Ministero degli Esteri) prima di partire.` } },

        { id: 'visa', topic: true, next: ['docs', 'human'],
          ro: { t: '🛃 Viză', k: ['viza', 'vize', 'autorizare electronica', 'eta', 'etias', 'e visa', 'evisa', 'am nevoie de viza'], a: `Necesitatea vizei depinde de țară și de cetățenie și se poate schimba. De exemplu, **Regatul Unit** (ETA), **SUA** (ESTA), **Kenya** (autorizare electronică) și **Indonezia / Bali** (viză la sosire, taxă turistică) au reguli speciale. Verifică pe site-ul oficial al MAE și întreabă un consultant la **{phone}**.` },
          en: { t: '🛃 Visa', k: ['visa', 'visas', 'electronic authorisation', 'eta', 'etias', 'e visa', 'evisa', 'do i need a visa'], a: `Whether you need a visa depends on the country and your citizenship, and it can change. For example, the **United Kingdom** (ETA), the **USA** (ESTA), **Kenya** (electronic authorisation) and **Indonesia / Bali** (visa on arrival, tourist levy) have special rules. Check the official foreign-ministry website and ask a consultant at **{phone}**.` },
          it: { t: '🛃 Visto', k: ['visto', 'visti', 'autorizzazione elettronica', 'eta', 'etias', 'e visa', 'evisa', 'serve il visto'], a: `La necessità del visto dipende dal Paese e dalla cittadinanza e può cambiare. Ad esempio **Regno Unito** (ETA), **USA** (ESTA), **Kenya** (autorizzazione elettronica) e **Indonesia / Bali** (visto all'arrivo, tassa turistica) hanno regole particolari. Controlla il sito ufficiale del Ministero degli Esteri e chiedi a un consulente al **{phone}**.` } },

        { id: 'vaccines', topic: true, next: ['insurance', 'safety'],
          ro: { t: '💉 Vaccinuri și sănătate', k: ['vaccin', 'vaccinuri', 'boli', 'malarie', 'sanatate in calatorie', 'medicul', 'profilaxie', 'am nevoie de vaccin'], a: `Pentru destinații exotice (ex.: Kenya, Bali) se recomandă un consult la medicul de familie sau la un centru de medicina călătoriilor cu **4–6 săptămâni înainte**. Recomandările oficiale (MAE, OMS) se schimbă, deci verifică-le înainte de plecare. Nu putem oferi sfaturi medicale.` },
          en: { t: '💉 Vaccines and health', k: ['vaccine', 'vaccines', 'vaccination', 'malaria', 'health', 'doctor', 'do i need a vaccine', 'health precautions'], a: `For exotic destinations (e.g. Kenya, Bali) we recommend seeing your GP or a travel-medicine clinic **4–6 weeks before** departure. Official recommendations (foreign ministry, WHO) change, so check them before you go. We can't give medical advice.` },
          it: { t: '💉 Vaccini e salute', k: ['vaccino', 'vaccini', 'vaccinazione', 'malaria', 'salute', 'medico', 'serve un vaccino', 'precauzioni sanitarie'], a: `Per le destinazioni esotiche (es. Kenya, Bali) consigliamo una visita dal medico di base o da un centro di medicina dei viaggi **4–6 settimane prima** della partenza. Le raccomandazioni ufficiali (Ministero degli Esteri, OMS) cambiano, quindi controllale prima di partire. Non possiamo dare consigli medici.` } },

        { id: 'luggage', topic: true, next: ['packing', 'airport-time'],
          ro: { t: '🧳 Bagaje', k: ['bagaj', 'bagaje', 'valiza', 'bagaj de mana', 'bagaj de cala', 'greutate bagaj', 'lichide', 'cati kg'], a: `Regulile de bagaj depind de **compania aeriană** și de tariful biletului; verifică-le înainte de zbor. La bagajul de mână, lichidele sunt în general limitate la recipiente de **100 ml**, puse într-o pungă transparentă.` },
          en: { t: '🧳 Luggage', k: ['luggage', 'baggage', 'suitcase', 'hand luggage', 'checked bag', 'weight limit', 'carry on', 'how many kg'], a: `Baggage rules depend on the **airline** and your ticket fare; check them before you fly. In hand luggage, liquids are generally limited to containers of **100 ml**, in a transparent bag.` },
          it: { t: '🧳 Bagagli', k: ['bagaglio', 'bagagli', 'valigia', 'bagaglio a mano', 'bagaglio in stiva', 'peso', 'quanti kg', 'liquidi'], a: `Le regole sui bagagli dipendono dalla **compagnia aerea** e dalla tariffa del biglietto; controllale prima del volo. Nel bagaglio a mano i liquidi sono in genere limitati a contenitori da **100 ml**, in una busta trasparente.` } },

        { id: 'airport-time', topic: true, next: ['luggage', 'delays'],
          ro: { t: '🕐 Cât timp înainte la aeroport?', k: ['cat timp inainte', 'la ce ora ajung la aeroport', 'check in', 'cand ajung la aeroport', 'ora ajungere', 'imbarcare'], a: `Pentru zboruri internaționale ajunge la aeroport cu **2–3 ore înainte**. Multe companii permit **check-in online** cu 24–48 de ore înainte. Aeroportul și orele exacte sunt în documentele primite de la consultant.` },
          en: { t: '🕐 When to arrive at the airport', k: ['when to arrive', 'how early', 'airport arrival', 'check in', 'boarding', 'what time should i be at the airport'], a: `For international flights arrive at the airport **2–3 hours before**. Many airlines allow **online check-in** 24–48 hours ahead. The airport and exact times are in the documents from your consultant.` },
          it: { t: '🕐 Quando arrivare in aeroporto', k: ['quando arrivare', 'con quanto anticipo', 'arrivo in aeroporto', 'check in', 'imbarco', 'a che ora devo essere in aeroporto'], a: `Per i voli internazionali arriva in aeroporto **2–3 ore prima**. Molte compagnie permettono il **check-in online** 24–48 ore prima. Aeroporto e orari esatti sono nei documenti ricevuti dal consulente.` } },

        { id: 'money', topic: true, next: ['cards', 'price-currency'],
          ro: { t: '💶 Monedă și schimb valutar', k: ['schimb valutar', 'unde schimb bani', 'ce moneda se foloseste', 'bani in vacanta', 'valuta', 'cash in vacanta', 'moneda locala'], a: `În zona euro (Roma, Paris, Viena, Barcelona...) folosești **euro**. Alte monede: liră sterlină (Londra), coroană cehă (Praga), franc elvețian (Elveția), dolar american (New York), yen (Japonia), won (Coreea), dirham (Dubai), yuan (China), rupie indoneziană (Bali), șiling kenyan (Kenya), rufiyaa (Maldive; dolarii sunt larg acceptați). Schimbă la bănci sau case de schimb, nu la aeroport.` },
          en: { t: '💶 Currency and exchange', k: ['currency exchange', 'where to exchange money', 'what currency', 'money abroad', 'local currency', 'cash abroad', 'which currency do they use'], a: `In the eurozone (Rome, Paris, Vienna, Barcelona...) you use the **euro**. Other currencies: pound sterling (London), Czech koruna (Prague), Swiss franc (Switzerland), US dollar (New York), yen (Japan), won (Korea), dirham (Dubai), yuan (China), Indonesian rupiah (Bali), Kenyan shilling (Kenya), rufiyaa (Maldives; US dollars are widely accepted). Exchange at banks or exchange offices, not at the airport.` },
          it: { t: '💶 Valuta e cambio', k: ['cambio valuta', 'dove cambiare', 'che valuta si usa', 'soldi all estero', 'valuta locale', 'contanti all estero', 'quale valuta'], a: `Nella zona euro (Roma, Parigi, Vienna, Barcellona...) si usa l'**euro**. Altre valute: sterlina (Londra), corona ceca (Praga), franco svizzero (Svizzera), dollaro USA (New York), yen (Giappone), won (Corea), dirham (Dubai), yuan (Cina), rupia indonesiana (Bali), scellino keniota (Kenya), rufiyaa (Maldive; i dollari sono molto accettati). Cambia in banca o negli uffici di cambio, non in aeroporto.` } },

        { id: 'cards', topic: true, next: ['money', 'roaming'],
          ro: { t: '💳 Cardul în străinătate', k: ['card in strainatate', 'comision card', 'plata cu cardul in strainatate', 'cu cardul in strainatate', 'notific banca', 'revolut', 'apple pay', 'card abroad'], a: `Cardurile **Visa / Mastercard** sunt larg acceptate. Verifică comisioanele băncii pentru plăți în alte monede, anunță banca despre călătorie și ia și puțin **cash**. În **China** plățile mobile (Alipay / WeChat Pay) sunt foarte răspândite: configurează-le înainte de plecare.` },
          en: { t: '💳 Cards abroad', k: ['card abroad', 'card fees', 'pay by card abroad', 'notify bank', 'revolut', 'apple pay', 'card in another country'], a: `**Visa / Mastercard** cards are widely accepted. Check your bank's fees for payments in other currencies, tell your bank you're travelling and carry a little **cash**. In **China** mobile payments (Alipay / WeChat Pay) are very common: set them up before you leave.` },
          it: { t: '💳 Carte all\'estero', k: ['carta all estero', 'commissioni carta', 'pagare con carta all estero', 'avvisare la banca', 'revolut', 'apple pay', 'carta in un altro paese'], a: `Le carte **Visa / Mastercard** sono molto accettate. Controlla le commissioni della banca per i pagamenti in altre valute, avvisa la banca del viaggio e porta un po' di **contanti**. In **Cina** i pagamenti da mobile (Alipay / WeChat Pay) sono diffusissimi: configurali prima di partire.` } },

        { id: 'roaming', topic: true, next: ['cards', 'adapters'],
          ro: { t: '📶 Internet și roaming', k: ['roaming', 'internet in strainatate', 'esim', 'sim', 'date mobile', 'wifi', 'cartela'], a: `În **UE/SEE** tarifele de roaming sunt ca acasă (în limita politicii operatorului). În afara UE poate fi scump: alege un pachet de roaming, o **eSIM** sau o cartelă locală. În **China** unele aplicații (Google, WhatsApp) pot fi restricționate: pregătește-te dinainte.` },
          en: { t: '📶 Internet and roaming', k: ['roaming', 'internet abroad', 'esim', 'sim card', 'mobile data', 'wifi', 'data abroad'], a: `In the **EU/EEA** roaming is charged like at home (subject to your operator's policy). Outside the EU it can be expensive: choose a roaming pack, an **eSIM** or a local SIM. In **China** some apps (Google, WhatsApp) may be restricted: prepare in advance.` },
          it: { t: '📶 Internet e roaming', k: ['roaming', 'internet all estero', 'esim', 'scheda sim', 'dati mobili', 'wifi', 'dati all estero'], a: `Nell'**UE/SEE** il roaming costa come a casa (nei limiti della politica dell'operatore). Fuori dall'UE può essere caro: scegli un pacchetto roaming, una **eSIM** o una SIM locale. In **Cina** alcune app (Google, WhatsApp) possono essere limitate: preparati in anticipo.` } },

        { id: 'adapters', topic: true, next: ['packing', 'roaming'],
          ro: { t: '🔌 Prize și adaptoare', k: ['priza', 'prize', 'adaptor', 'adaptoare', 'tensiune', 'incarcator', 'tip de priza'], a: `**UE:** prize compatibile (tip C/F). **Regatul Unit, Dubai, Kenya:** tip G. **Elveția:** tip J. **SUA și Japonia:** tip A/B, 100–120 V. **China:** tip A/C/I. **Coreea de Sud și Bali:** tip C/F, 230 V. **Maldive:** tip D/G/J. Cel mai simplu: un **adaptor universal**.` },
          en: { t: '🔌 Plugs and adapters', k: ['plug', 'plugs', 'adapter', 'adaptor', 'voltage', 'charger', 'socket type'], a: `**EU:** compatible sockets (type C/F). **UK, Dubai, Kenya:** type G. **Switzerland:** type J. **USA and Japan:** type A/B, 100–120 V. **China:** type A/C/I. **South Korea and Bali:** type C/F, 230 V. **Maldives:** type D/G/J. Easiest: a **universal adapter**.` },
          it: { t: '🔌 Prese e adattatori', k: ['presa', 'prese', 'adattatore', 'tensione', 'caricatore', 'tipo di presa'], a: `**UE:** prese compatibili (tipo C/F). **Regno Unito, Dubai, Kenya:** tipo G. **Svizzera:** tipo J. **USA e Giappone:** tipo A/B, 100–120 V. **Cina:** tipo A/C/I. **Corea del Sud e Bali:** tipo C/F, 230 V. **Maldive:** tipo D/G/J. Il più semplice: un **adattatore universale**.` } },

        { id: 'timezone', topic: true, next: ['packing', 'weather'],
          ro: { t: '🕰️ Fus orar și jet lag', k: ['fus orar', 'decalaj orar', 'jet lag', 'ora locala', 'diferenta de ora', 'oboseala calatoriei'], a: `Diferențe aproximative față de România (variază cu ora de vară/iarnă): Europa Centrală −1 h; Londra −2 h; Grecia 0; Turcia 0/+1 h; Dubai +1/+2 h; Kenya 0/+1 h; Maldive +2/+3 h; Beijing, Shanghai, Bali +5/+6 h; Tokyo, Seoul +6/+7 h; New York −7 h. Pentru zborurile lungi, mută-ți programul de somn cu 1–2 zile înainte.` },
          en: { t: '🕰️ Time zones and jet lag', k: ['time zone', 'time difference', 'jet lag', 'local time', 'jetlag'], a: `Approximate differences from Romania (they vary with daylight saving): Central Europe −1 h; London −2 h; Greece 0; Turkey 0/+1 h; Dubai +1/+2 h; Kenya 0/+1 h; Maldives +2/+3 h; Beijing, Shanghai, Bali +5/+6 h; Tokyo, Seoul +6/+7 h; New York −7 h. For long flights, shift your sleep schedule 1–2 days beforehand.` },
          it: { t: '🕰️ Fuso orario e jet lag', k: ['fuso orario', 'differenza di orario', 'jet lag', 'ora locale', 'jetlag'], a: `Differenze approssimative rispetto alla Romania (variano con l'ora legale): Europa centrale −1 h; Londra −2 h; Grecia 0; Turchia 0/+1 h; Dubai +1/+2 h; Kenya 0/+1 h; Maldive +2/+3 h; Pechino, Shanghai, Bali +5/+6 h; Tokyo, Seoul +6/+7 h; New York −7 h. Per i voli lunghi, sposta il ritmo del sonno 1–2 giorni prima.` } },

        { id: 'packing', topic: true, next: ['luggage', 'weather'],
          ro: { t: '🎒 Ce iau cu mine?', k: ['ce iau in bagaj', 'ce sa iau cu mine', 'ce impachetez', 'lista de bagaj', 'ce haine iau', 'ce trebuie sa iau'], a: `Lista de bază: **acte și asigurare**, bani/card, telefon + încărcător + **adaptor**, medicamente personale, haine pe straturi potrivite vremii, **cremă solară**, încălțăminte comodă și o geantă mică pentru excursii. Verifică prognoza cu câteva zile înainte.` },
          en: { t: '🎒 What should I pack?', k: ['what to pack', 'packing list', 'what should i bring', 'what should i pack', 'what do i pack', 'how to pack', 'what clothes', 'what do i need to take'], a: `The basics: **documents and insurance**, money/card, phone + charger + **adapter**, personal medication, layered clothes for the weather, **sunscreen**, comfortable shoes and a small bag for day trips. Check the forecast a few days before.` },
          it: { t: '🎒 Cosa porto?', k: ['cosa portare', 'lista bagaglio', 'cosa mettere in valigia', 'cosa metto in valigia', 'che vestiti', 'cosa devo portare'], a: `La lista base: **documenti e assicurazione**, soldi/carta, telefono + caricatore + **adattatore**, farmaci personali, abiti a strati adatti al meteo, **crema solare**, scarpe comode e una borsa piccola per le gite. Controlla le previsioni qualche giorno prima.` } },

        { id: 'kids-travel', topic: true, next: ['docs', 'kids-price'],
          ro: { t: '👶 Călătoria cu copii', k: ['calatorie cu copii', 'copil in avion', 'copii minori', 'acord parental', 'declaratie parinte', 'minor', 'minori'], a: `Fiecare copil are nevoie de **propriul act** (carte de identitate sau pașaport). Dacă un minor călătorește în străinătate doar cu un părinte sau cu altcineva, pot fi necesare **acordul notarial al celuilalt părinte** și alte documente: verifică regulile la **Poliția de Frontieră** înainte de plecare.` },
          en: { t: '👶 Travelling with children', k: ['travelling with children', 'child in plane', 'minors', 'parental consent', 'child documents', 'kids documents'], a: `Every child needs their **own document** (ID card or passport). If a minor travels abroad with just one parent or with someone else, the **other parent's notarised consent** and other papers may be required: check the rules with the **Border Police** before you leave.` },
          it: { t: '👶 Viaggiare con bambini', k: ['viaggiare con bambini', 'minori', 'consenso dei genitori', 'documenti bambino', 'documenti dei bambini', 'bambino in aereo'], a: `Ogni bambino ha bisogno di un **proprio documento** (carta d'identità o passaporto). Se un minore viaggia all'estero con un solo genitore o con altri, possono servire il **consenso notarile dell'altro genitore** e altri documenti: verifica le regole con la **Polizia di Frontiera** prima di partire.` } },

        { id: 'accessibility', topic: true, next: ['human', 'custom-trip'],
          ro: { t: '♿ Accesibilitate', k: ['dizabilitati', 'accesibilitate', 'scaun cu rotile', 'mobilitate redusa', 'persoane cu handicap', 'nevoi speciale'], a: `Spune-ne din start nevoile tale (mobilitate redusă, scaun cu rotile etc.) în formularul din **Contact** sau la **{phone}**. Verificăm accesibilitatea cu partenerii, dar nu toate locurile sunt accesibile.` },
          en: { t: '♿ Accessibility', k: ['disability', 'accessibility', 'wheelchair', 'reduced mobility', 'special needs', 'disabled'], a: `Tell us your needs upfront (reduced mobility, wheelchair, etc.) in the **Contact** form or at **{phone}**. We check accessibility with our partners, but not all places are accessible.` },
          it: { t: '♿ Accessibilità', k: ['disabilita', 'accessibilita', 'sedia a rotelle', 'mobilita ridotta', 'esigenze speciali', 'disabile'], a: `Comunicaci subito le tue esigenze (mobilità ridotta, sedia a rotelle ecc.) nel modulo **Contatti** o al **{phone}**. Verifichiamo l'accessibilità con i partner, ma non tutti i luoghi sono accessibili.` } },

        { id: 'diet', topic: true, next: ['human', 'meals'],
          ro: { t: '🥗 Alergii și dietă', k: ['alergii', 'vegetarian', 'vegan', 'fara gluten', 'halal', 'cazher', 'dieta', 'intoleranta'], a: `Menționează alergiile sau regimul (vegetarian, fără gluten, halal etc.) în cererea de rezervare. Hotelurile pot adapta meniul dacă sunt anunțate, dar nu putem garanta fiecare regim în fiecare loc.` },
          en: { t: '🥗 Allergies and diet', k: ['allergies', 'vegetarian', 'vegan', 'gluten free', 'halal', 'kosher', 'diet', 'intolerance'], a: `Mention allergies or dietary needs (vegetarian, gluten-free, halal, etc.) in your booking request. Hotels can usually adapt the menu if told in advance, but we can't guarantee every diet everywhere.` },
          it: { t: '🥗 Allergie e dieta', k: ['allergie', 'vegetariano', 'vegano', 'senza glutine', 'halal', 'dieta', 'intolleranza', 'kosher'], a: `Indica allergie o esigenze alimentari (vegetariano, senza glutine, halal ecc.) nella richiesta di prenotazione. Gli hotel di solito possono adattare il menù se avvisati, ma non possiamo garantire ogni dieta ovunque.` } },

        { id: 'safety', topic: true, next: ['insurance', 'docs'],
          ro: { t: '🔒 Siguranță', k: ['e sigur', 'siguranta', 'este sigur sa merg', 'pericol', 'riscuri', 'avertizari de calatorie', 'este periculos'], a: `Înainte de plecare verifică **avertizările de călătorie** ale MAE pentru destinația ta, ia o **asigurare de călătorie**, păstrează copii ale actelor și fii atent la lucrurile personale în zonele aglomerate. Consultantul îți poate spune ce știe despre destinație.` },
          en: { t: '🔒 Safety', k: ['is it safe', 'safety', 'dangerous', 'risks', 'travel warnings', 'is it dangerous'], a: `Before you go, check your foreign ministry's **travel advisories** for the destination, take **travel insurance**, keep copies of your documents and watch your belongings in crowded areas. Your consultant can share what they know about the destination.` },
          it: { t: '🔒 Sicurezza', k: ['e sicuro', 'sicurezza', 'pericoloso', 'rischi', 'avvisi di viaggio', 'e pericoloso'], a: `Prima di partire controlla gli **avvisi di viaggio** del Ministero degli Esteri per la destinazione, stipula un'**assicurazione di viaggio**, conserva copie dei documenti e fai attenzione agli effetti personali nelle zone affollate. Il consulente può dirti ciò che sa della destinazione.` } },

        { id: 'weather', defer: true, next: ['best-time-general', 'destinations-list'],
          ro: { t: '🌦️ Vremea', k: ['cum e vremea', 'vremea', 'prognoza', 'ce temperatura', 'clima', 'ce vreme e'], a: `Vremea depinde de destinație și de lună. Spune-mi destinația (ex.: „Când e cel mai bun moment pentru Bali?”) și îți dau detalii de sezon. Cu câteva zile înainte de plecare, verifică oricum **prognoza**.` },
          en: { t: '🌦️ Weather', k: ['how is the weather', 'weather', 'forecast', 'what temperature', 'climate', 'what is the weather like'], a: `Weather depends on the destination and the month. Tell me the destination (e.g. "When is the best time for Bali?") and I'll give you seasonal details. A few days before you leave, do check the **forecast**.` },
          it: { t: '🌦️ Meteo', k: ['che tempo fa', 'meteo', 'previsioni', 'che temperatura', 'clima', 'com e il tempo'], a: `Il meteo dipende dalla destinazione e dal mese. Dimmi la destinazione (es. "Quando è il momento migliore per Bali?") e ti do i dettagli stagionali. Qualche giorno prima di partire controlla comunque le **previsioni**.` } },

        { id: 'best-time-general', defer: true, next: ['weather', 'season-price'],
          ro: { t: '📅 Când e cel mai bine?', k: ['cand e cel mai bun moment', 'cand sa plec', 'ce luna e mai buna', 'cea mai buna perioada', 'cand merita sa merg', 'cand merita sa plec', 'cand merita', 'in ce luna sa merg'], a: `Pe scurt: **plajă** iunie–septembrie; **schi** decembrie–martie; **city break** aprilie–iunie și septembrie–octombrie; **Maldive și Dubai** noiembrie–aprilie; **safari în Kenya** iulie–octombrie. Spune-mi destinația (ex.: „Când merg în Bali?”) și îți dau detalii.` },
          en: { t: '📅 Best time to go', k: ['best time to go', 'when should i go', 'which month is best', 'best period', 'when is it worth going', 'what month should i go'], a: `In short: **beach** June–September; **skiing** December–March; **city breaks** April–June and September–October; **Maldives and Dubai** November–April; **Kenya safari** July–October. Tell me the destination (e.g. "When should I go to Bali?") and I'll give details.` },
          it: { t: '📅 Quando andare', k: ['quando andare', 'quando partire', 'che mese e meglio', 'periodo migliore', 'quando conviene andare', 'in che mese andare'], a: `In breve: **mare** giugno–settembre; **sci** dicembre–marzo; **city break** aprile–giugno e settembre–ottobre; **Maldive e Dubai** novembre–aprile; **safari in Kenya** luglio–ottobre. Dimmi la destinazione (es. "Quando vado a Bali?") e ti do i dettagli.` } },

        { id: 'tipping', topic: true, next: ['money', 'cards'],
          ro: { t: '🪙 Bacșiș', k: ['bacsis', 'tips', 'cat las bacsis', 'se lasa bacsis', 'bacsisul'], a: `Orientativ: **SUA (New York)** 15–20% la restaurant; **Europa** 5–10% dacă serviciul nu e inclus în notă; **Japonia și Coreea de Sud** nu se lasă bacșiș; în **Kenya, Bali, Maldive și Dubai** se apreciază în jur de 10% (verifică dacă serviciul e deja inclus).` },
          en: { t: '🪙 Tipping', k: ['tip', 'tipping', 'how much to tip', 'gratuity', 'do i tip'], a: `Roughly: **USA (New York)** 15–20% at restaurants; **Europe** 5–10% if service isn't included on the bill; **Japan and South Korea** no tipping; in **Kenya, Bali, the Maldives and Dubai** about 10% is appreciated (check whether service is already included).` },
          it: { t: '🪙 Mancia', k: ['mancia', 'mance', 'quanto lasciare di mancia', 'si lascia la mancia'], a: `Indicativamente: **USA (New York)** 15–20% al ristorante; **Europa** 5–10% se il servizio non è incluso nel conto; **Giappone e Corea del Sud** niente mancia; in **Kenya, Bali, Maldive e Dubai** circa il 10% è gradito (controlla se il servizio è già incluso).` } },

        { id: 'delays', topic: true, next: ['insurance', 'human'],
          ro: { t: '⏳ Zbor întârziat sau anulat', k: ['zbor intarziat', 'intarziere', 'zbor anulat', 'anulat', 'intarzi*', 'pierdut zborul', 'bagaj pierdut', 'compensatie', 'am pierdut avionul'], a: `Dacă zborul e întârziat sau anulat, contactează întâi **compania aeriană** și păstrează documentele. Ne poți scrie și nouă la **{phone}**. În UE pasagerii au drepturi (asistență, uneori compensații), iar o **asigurare de călătorie** poate acoperi bagajul pierdut sau costuri suplimentare.` },
          en: { t: '⏳ Delayed or cancelled flight', k: ['delayed flight', 'flight cancelled', 'missed flight', 'lost luggage', 'compensation', 'flight delay', 'i missed my flight'], a: `If your flight is delayed or cancelled, contact the **airline** first and keep your documents. You can also reach us at **{phone}**. In the EU passengers have rights (assistance, sometimes compensation), and **travel insurance** may cover lost luggage or extra costs.` },
          it: { t: '⏳ Volo in ritardo o cancellato', k: ['volo in ritardo', 'volo cancellato', 'perso il volo', 'bagaglio smarrito', 'risarcimento', 'ritardo del volo', 'ho perso l aereo'], a: `Se il volo è in ritardo o cancellato, contatta prima la **compagnia aerea** e conserva i documenti. Puoi scriverci anche al **{phone}**. Nell'UE i passeggeri hanno diritti (assistenza, a volte risarcimento) e un'**assicurazione di viaggio** può coprire bagaglio smarrito o costi extra.` } },

        /* ==================================================== FOLOSIREA SITE-ULUI ==================================================== */
        { id: 'language-site', next: ['dark-mode', 'languages'],
          ro: { t: '🌐 Schimbă limba site-ului', k: ['schimb limba', 'limba site ului', 'limba site', 'traducere site', 'site in engleza', 'site in italiana', 'pun site ul in engleza'], a: `Schimbă limba site-ului din butonul **RO / EN / IT / FR / ES** din antet (pe telefon, din meniu). Textele, pachetele și chatul se traduc pe loc.` },
          en: { t: '🌐 Change site language', k: ['change language', 'change the language', 'switch the language', 'site language', 'translate the site', 'switch language', 'website in english'], a: `Change the site language with the **RO / EN / IT / FR / ES** button in the header (on a phone, in the menu). Texts, packages and the chat translate instantly.` },
          it: { t: '🌐 Cambia lingua del sito', k: ['cambiare lingua', 'cambiare la lingua', 'lingua del sito', 'tradurre il sito', 'cambia lingua', 'sito in italiano'], a: `Cambia la lingua del sito con il pulsante **RO / EN / IT / FR / ES** nell'intestazione (su telefono, nel menu). Testi, pacchetti e chat si traducono subito.` } },

        { id: 'dark-mode', next: ['language-site', 'mobile'],
          ro: { t: '🌙 Mod întunecat', k: ['mod intunecat', 'dark mode', 'mod luminos', 'tema intunecata', 'tema', 'intunecat', 'luminos', 'schimb tema'], a: `Comută între modul **luminos și întunecat** cu butonul **lună / soare** din antet. Implicit, site-ul urmărește setarea telefonului sau a calculatorului până alegi tu.` },
          en: { t: '🌙 Dark mode', k: ['dark mode', 'light mode', 'dark theme', 'theme', 'switch theme', 'night mode'], a: `Switch between **light and dark** mode with the **moon / sun** button in the header. By default the site follows your phone or computer setting until you choose.` },
          it: { t: '🌙 Modalità scura', k: ['modalita scura', 'modalita chiara', 'tema scuro', 'tema', 'cambiare tema', 'modalita notte'], a: `Passa tra modalità **chiara e scura** con il pulsante **luna / sole** nell'intestazione. Di default il sito segue l'impostazione del telefono o del computer finché non scegli tu.` } },

        { id: 'filters', next: ['destinations-list', 'budget'],
          ro: { t: '🔎 Căutare și filtre', k: ['filtre', 'filtrez', 'cum caut', 'cautare', 'caut o destinatie', 'filtru buget', 'filtru categorie', 'sortare'], a: `Sus, în căutare, alegi **destinația**, **tipul de vacanță** și **bugetul maxim**. În secțiunea **Destinații & Pachete** ai și butoane pentru categorii (România, plajă, munte, city break, exotic, China & Coreea). Pe telefon, butoanele se derulează lateral.` },
          en: { t: '🔎 Search and filters', k: ['filters', 'filter', 'search', 'how to search', 'find a destination', 'budget filter'], a: `At the top, in the search box, choose the **destination**, the **type of holiday** and your **maximum budget**. In the **Destinations & Packages** section there are also category buttons (Romania, beach, mountains, city break, exotic, China & Korea). On a phone, the buttons scroll sideways.` },
          it: { t: '🔎 Ricerca e filtri', k: ['filtri', 'filtrare', 'cercare', 'come cerco', 'trovare una destinazione', 'filtro budget'], a: `In alto, nella ricerca, scegli **destinazione**, **tipo di vacanza** e **budget massimo**. Nella sezione **Destinazioni & Pacchetti** ci sono anche i pulsanti per categoria (Romania, mare, montagna, city break, esotiche, Cina & Corea). Su telefono i pulsanti scorrono lateralmente.` } },

        { id: 'package-details', next: ['how-to-book', 'dates-how'],
          ro: { t: '🖼️ Detalii pachet', k: ['detalii pachet', 'galerie foto', 'poze', 'fotografii', 'imagini', 'vezi pachetul', 'deschid pachetul', 'pozele', 'poze pachet', 'unde vad pozele'], a: `Apasă **Detalii Pachet** pe cardul unei destinații: vezi galeria cu 4 poze, descrierea, serviciile, **calculatorul de preț** (persoane, date, servicii extra) și formularul de rezervare.` },
          en: { t: '🖼️ Package details', k: ['package details', 'photo gallery', 'photos', 'pictures', 'open the package', 'see the package'], a: `Press **Package Details** on a destination card: you'll see the 4-photo gallery, the description, the services, the **price calculator** (people, dates, extras) and the booking form.` },
          it: { t: '🖼️ Dettagli pacchetto', k: ['dettagli pacchetto', 'galleria foto', 'foto', 'immagini', 'aprire il pacchetto', 'vedere il pacchetto'], a: `Premi **Dettagli Pacchetto** sulla scheda di una destinazione: vedi la galleria di 4 foto, la descrizione, i servizi, il **calcolatore di prezzo** (persone, date, extra) e il modulo di prenotazione.` } },

        { id: 'mobile', next: ['dark-mode', 'chat-help'],
          ro: { t: '📱 Pe telefon', k: ['aplicatie', 'app', 'pe telefon', 'mobil', 'site pe telefon', 'descarc', 'aplicatia mobila'], a: `Nu avem aplicație: site-ul este **optimizat pentru telefon** și funcționează direct în browser. Îl poți adăuga pe ecranul principal din meniul browserului („Adaugă pe ecranul principal”).` },
          en: { t: '📱 On my phone', k: ['app', 'mobile app', 'on my phone', 'download', 'mobile site', 'is there an app'], a: `We don't have an app: the site is **optimised for phones** and works right in your browser. You can add it to your home screen from the browser menu ("Add to Home screen").` },
          it: { t: '📱 Sul telefono', k: ['app', 'applicazione', 'sul telefono', 'scaricare', 'sito mobile', 'c e un app'], a: `Non abbiamo un'app: il sito è **ottimizzato per il telefono** e funziona direttamente nel browser. Puoi aggiungerlo alla schermata Home dal menu del browser ("Aggiungi a schermata Home").` } },

        { id: 'chat-help', next: ['can-do', 'human'],
          ro: { t: '💬 Cum folosesc chatul?', k: ['cum folosesc chatul', 'cum functioneaza chatul', 'cum scriu', 'chat', 'asistent virtual'], a: `Scrie-mi întrebarea sau apasă butoanele sugerate. Când asistentul AI e disponibil, răspund liber la întrebări despre agenție, site și destinații; altfel folosesc răspunsuri pregătite. Pot deschide și pachete pentru tine, cu butonul **„Vezi pachetul”**.` },
          en: { t: '💬 How do I use the chat?', k: ['how does the chat work', 'how to use the chat', 'chat help', 'chat', 'virtual assistant'], a: `Type your question or tap the suggested buttons. When the AI assistant is available I answer questions about the agency, site and destinations freely; otherwise I use prepared answers. I can also open packages for you with the **"See package"** button.` },
          it: { t: '💬 Come uso la chat?', k: ['come funziona la chat', 'come usare la chat', 'aiuto chat', 'chat', 'assistente virtuale'], a: `Scrivi la tua domanda o tocca i pulsanti suggeriti. Quando l'assistente IA è disponibile rispondo liberamente su agenzia, sito e destinazioni; altrimenti uso risposte preparate. Posso anche aprire i pacchetti per te con il pulsante **"Vedi il pacchetto"**.` } },

        { id: 'counter', next: ['about', 'chat-help'],
          ro: { t: '❤️ Contorul „Călători Fericiți”', k: ['calatori fericiti', 'contor', 'numarul de calatori', 'ce e contorul', 'counter'], a: `**„Călători Fericiți”** este un contor live: fiecare click adaugă 1, iar toți vizitatorii aflați pe pagină văd numărul schimbându-se în timp real.` },
          en: { t: '❤️ "Happy Travellers" counter', k: ['happy travellers', 'happy travelers', 'counter', 'what is the counter', 'travelers counter'], a: `**"Happy Travellers"** is a live counter: every click adds 1, and all visitors on the page see the number change in real time.` },
          it: { t: '❤️ Contatore "Viaggiatori Felici"', k: ['viaggiatori felici', 'contatore', 'cos e il contatore', 'numero di viaggiatori'], a: `**"Viaggiatori Felici"** è un contatore in tempo reale: ogni clic aggiunge 1 e tutti i visitatori sulla pagina vedono il numero cambiare subito.` } },

        { id: 'privacy', next: ['no-account', 'contact'],
          ro: { t: '🔐 Date personale', k: ['date personale', 'gdpr', 'confidentialitate', 'protectia datelor', 'datele mele', 'cookies', 'cookie', 'sunt in siguranta datele'], a: `Datele din formulare (nume, telefon, e-mail) sunt folosite pentru a te contacta în legătură cu solicitarea ta. **Nu scrie date personale în chat**: folosește formularele. Contul este opțional. Pentru detalii despre datele tale, scrie-ne la **{email}**.` },
          en: { t: '🔐 Personal data', k: ['personal data', 'gdpr', 'privacy', 'data protection', 'my data', 'cookies', 'is my data safe'], a: `The details in the forms (name, phone, e-mail) are used to contact you about your request. **Don't write personal data in the chat**: use the forms. The account is optional. For details about your data, write to **{email}**.` },
          it: { t: '🔐 Dati personali', k: ['dati personali', 'gdpr', 'privacy', 'protezione dei dati', 'i miei dati', 'cookie', 'i miei dati sono al sicuro'], a: `I dati inseriti nei moduli (nome, telefono, e-mail) servono per contattarti riguardo alla tua richiesta. **Non scrivere dati personali nella chat**: usa i moduli. L'account è opzionale. Per dettagli sui tuoi dati scrivici a **{email}**.` } },

        { id: 'tech-issue', next: ['contact', 'login-help'],
          ro: { t: '🛠️ Site-ul nu merge', k: ['nu merge site ul', 'eroare', 'nu se incarca', 'problema tehnica', 'bug', 'nu functioneaza', 'blocat', 'nu merge', 'site ul nu merge'], a: `Încearcă: **reîncarcă pagina** (Ctrl+F5, sau trage în jos pe telefon), deschide site-ul în alt browser sau în modul incognito. Dacă problema rămâne, scrie-ne la **{email}** cu o captură de ecran și dispozitivul folosit.` },
          en: { t: '🛠️ The site isn\'t working', k: ['not working', 'error', 'does not load', 'technical problem', 'bug', 'stuck', 'broken', 'site not working'], a: `Try: **reload the page** (Ctrl+F5, or pull down on a phone), open the site in another browser or in private mode. If the problem persists, write to **{email}** with a screenshot and the device you use.` },
          it: { t: '🛠️ Il sito non funziona', k: ['non funziona', 'errore', 'non si carica', 'problema tecnico', 'bug', 'bloccato', 'sito non funziona'], a: `Prova a **ricaricare la pagina** (Ctrl+F5, o trascina verso il basso su telefono), aprire il sito in un altro browser o in modalità privata. Se il problema persiste, scrivi a **{email}** con uno screenshot e il dispositivo usato.` } }
    ]);
})(typeof window !== 'undefined' ? window : globalThis);
