/* FeelVoyage — răspunsuri pentru destinații (nume alternative + cel mai bun moment din an).
   Prețul, durata, ce include și descrierea vin direct din js/destinations.js, deci se actualizează singure.
   „best" = informații generale (climă, sezon); nu sunt promisiuni: se verifică prognoza înainte de plecare. */
(function (root) {
    'use strict';
    const F = root.FVFAQ;
    if (!F) return;

    F.registerDestinations({
        'delta-dunarii': { alias: ['delta dunarii', 'delta', 'danube delta', 'delta del danubio', 'tulcea', 'sulina'],
            best: { ro: 'Cel mai bine mai–iunie și septembrie: temperaturi blânde, multe păsări migratoare și mai puțini țânțari decât în iulie. Vara e cald, iarna e rece și liniștit.', en: 'Best in May–June and September: mild weather, lots of migrating birds and fewer mosquitoes than in July. Summer is hot, winter is cold and quiet.', it: 'Meglio a maggio–giugno e settembre: clima mite, molti uccelli migratori e meno zanzare che a luglio. L\'estate è calda, l\'inverno freddo e tranquillo.' } },
        'poiana-brasov': { alias: ['poiana brasov', 'poiana', 'poiana brasov ski'],
            best: { ro: 'Iarna (decembrie–martie) pentru schi și spa; vara (iunie–septembrie) pentru drumeții și telegondolă. Sărbătorile de iarnă sunt cele mai aglomerate.', en: 'Winter (December–March) for skiing and spa; summer (June–September) for hiking and the cable car. The winter holidays are the busiest.', it: 'In inverno (dicembre–marzo) per sci e spa; in estate (giugno–settembre) per escursioni e cabinovia. Le feste invernali sono il periodo più affollato.' } },
        'bran-brasov': { alias: ['bran', 'castelul bran', 'bran castle', 'castello di bran', 'dracula', 'brasov'],
            best: { ro: 'Primăvara târzie și toamna (mai–iunie, septembrie–octombrie) sunt ideale; iarna e frumos, dar rece. În weekenduri de vară castelul e foarte aglomerat.', en: 'Late spring and autumn (May–June, September–October) are ideal; winter is pretty but cold. On summer weekends the castle is very crowded.', it: 'Fine primavera e autunno (maggio–giugno, settembre–ottobre) sono ideali; l\'inverno è bello ma freddo. Nei weekend estivi il castello è molto affollato.' } },
        'transfagarasan': { alias: ['transfagarasan', 'balea', 'balea lac', 'lacul balea', 'transfagarasan road'],
            best: { ro: 'Drumul de mare altitudine este, de regulă, deschis doar vara, aproximativ iulie–octombrie. Verifică starea drumului înainte de plecare; sus poate fi frig chiar și în august.', en: 'The high-altitude road is usually open only in summer, roughly July–October. Check road conditions before you go; it can be cold at the top even in August.', it: 'La strada d\'alta quota è di solito aperta solo in estate, circa luglio–ottobre. Controlla le condizioni prima di partire; in cima può fare freddo anche ad agosto.' } },
        'cazanele-dunarii': { alias: ['cazanele', 'cazanele dunarii', 'orsova', 'decebal', 'danube gorge', 'gole del danubio'],
            best: { ro: 'Mai–septembrie pentru croaziera pe Dunăre; primăvara și toamna sunt plăcute, iar în iulie–august e cald.', en: 'May–September for the Danube cruise; spring and autumn are pleasant, while July–August is hot.', it: 'Da maggio a settembre per la crociera sul Danubio; primavera e autunno sono piacevoli, luglio–agosto è caldo.' } },
        'maramures': { alias: ['maramures', 'sapanta', 'cimitirul vesel', 'merry cemetery', 'cimitero allegro', 'biserici de lemn'],
            best: { ro: 'Iunie–octombrie: vreme bună pentru sate și drumeții, iar toamna aduce culori frumoase și sărbători tradiționale. Iarna e frig și zăpadă.', en: 'June–October: good weather for villages and hiking; autumn brings beautiful colours and traditional celebrations. Winters are cold and snowy.', it: 'Giugno–ottobre: bel tempo per villaggi ed escursioni; l\'autunno porta colori splendidi e feste tradizionali. Gli inverni sono freddi e nevosi.' } },
        'sibiu-sighisoara': { alias: ['sibiu', 'sighisoara', 'transilvania', 'transylvania', 'transilvania'],
            best: { ro: 'Mai–iunie și septembrie–octombrie sunt cele mai plăcute luni; în iulie e Festivalul Sighișoara Medievală, iar în decembrie Sibiu are un târg de Crăciun renumit.', en: 'May–June and September–October are the most pleasant; July has the Medieval Sighișoara Festival and December brings Sibiu\'s well-known Christmas market.', it: 'Maggio–giugno e settembre–ottobre sono i mesi più piacevoli; a luglio c\'è il Festival Medievale di Sighișoara e a dicembre il noto mercatino di Natale di Sibiu.' } },
        'mamaia-constanta': { alias: ['mamaia', 'constanta', 'marea neagra', 'black sea', 'mar nero', 'plaja mamaia'],
            best: { ro: 'Iunie–septembrie. Iulie–august e cel mai cald și mai aglomerat (și cel mai scump); iunie și septembrie sunt mai liniștite, cu apă încă plăcută.', en: 'June–September. July–August is the hottest, busiest (and priciest) time; June and September are calmer with still-pleasant sea temperatures.', it: 'Da giugno a settembre. Luglio–agosto è il periodo più caldo, affollato (e caro); giugno e settembre sono più tranquilli con il mare ancora piacevole.' } },
        'roma': { alias: ['roma', 'rome', 'italia', 'italy', 'vatican', 'vaticano', 'colosseum', 'colosseo', 'fontana di trevi'],
            best: { ro: 'Aprilie–iunie și septembrie–octombrie: temperaturi plăcute. Iulie–august e foarte cald; iarna e mai liniștit și mai ieftin. Rezervă din timp intrările la Colosseum și Vatican.', en: 'April–June and September–October: pleasant temperatures. July–August is very hot; winter is quieter and cheaper. Book Colosseum and Vatican entries ahead.', it: 'Aprile–giugno e settembre–ottobre: temperature piacevoli. Luglio–agosto è molto caldo; l\'inverno è più tranquillo ed economico. Prenota in anticipo Colosseo e Vaticano.' } },
        'barcelona': { alias: ['barcelona', 'barcellona', 'spania', 'spain', 'spagna', 'sagrada familia'],
            best: { ro: 'Mai–iunie și septembrie–octombrie: vreme bună și mai puțini turiști. Vara e cald și bun pentru plajă; iarna e blândă.', en: 'May–June and September–October: nice weather and fewer tourists. Summer is hot and good for the beach; winter is mild.', it: 'Maggio–giugno e settembre–ottobre: bel tempo e meno turisti. L\'estate è calda e adatta alla spiaggia; l\'inverno è mite.' } },
        'londra': { alias: ['londra', 'london', 'anglia', 'england', 'inghilterra', 'regatul unit', 'united kingdom', 'regno unito', 'big ben', 'tower bridge'],
            best: { ro: 'Mai–septembrie e mai cald și mai uscat, dar poate ploua oricând: ia o umbrelă. Decembrie are iluminat festiv și târguri, dar e rece.', en: 'May–September is warmer and drier, but it can rain any time, so bring an umbrella. December has festive lights and markets but is cold.', it: 'Maggio–settembre è più caldo e asciutto, ma può piovere sempre: porta un ombrello. A dicembre ci sono luci e mercatini, ma fa freddo.' } },
        'praga': { alias: ['praga', 'prague', 'praha', 'cehia', 'czech republic', 'repubblica ceca', 'cehia'],
            best: { ro: 'Aprilie–mai și septembrie–octombrie sunt ideale; decembrie are târguri de Crăciun frumoase, dar e frig. Vara e aglomerat.', en: 'April–May and September–October are ideal; December has lovely Christmas markets but is cold. Summer is crowded.', it: 'Aprile–maggio e settembre–ottobre sono ideali; dicembre ha bei mercatini di Natale ma fa freddo. L\'estate è affollata.' } },
        'viena': { alias: ['viena', 'vienna', 'austria', 'schonbrunn'],
            best: { ro: 'Aprilie–mai și septembrie–octombrie pentru plimbări și muzee; în decembrie sunt târgurile de Crăciun (frig, dar atmosferă deosebită).', en: 'April–May and September–October for walks and museums; December brings the Christmas markets (cold, but a special atmosphere).', it: 'Aprile–maggio e settembre–ottobre per passeggiate e musei; a dicembre ci sono i mercatini di Natale (freddo, ma atmosfera speciale).' } },
        'paris': { alias: ['paris', 'parigi', 'franta', 'france', 'francia', 'turnul eiffel', 'eiffel', 'tour eiffel', 'torre eiffel', 'louvre'],
            best: { ro: 'Aprilie–iunie și septembrie–octombrie sunt cele mai plăcute; vara e aglomerat, iarna mai ieftin și mai liniștit. Ia bilete din timp pentru Turnul Eiffel și Luvru.', en: 'April–June and September–October are the nicest; summer is crowded, winter cheaper and quieter. Book Eiffel Tower and Louvre tickets ahead.', it: 'Aprile–giugno e settembre–ottobre sono i più piacevoli; l\'estate è affollata, l\'inverno più economico e tranquillo. Prenota in anticipo Torre Eiffel e Louvre.' } },
        'maldive-deluxe': { alias: ['maldiv*', 'maldive', 'maldives', 'malediven'],
            best: { ro: 'Decembrie–aprilie e sezonul uscat, cu cel mai mult soare (și cele mai mari prețuri). Mai–noiembrie e sezonul ploios, cu prețuri mai mici și ploi scurte.', en: 'December–April is the dry season with the most sun (and the highest prices). May–November is the rainy season with lower prices and short showers.', it: 'Da dicembre ad aprile è la stagione secca, con più sole (e prezzi più alti). Da maggio a novembre è la stagione delle piogge, con prezzi più bassi e brevi acquazzoni.' } },
        'kenya-safari': { alias: ['kenya', 'safari', 'masai mara', 'maasai mara', 'nairobi'],
            best: { ro: 'Iulie–octombrie este perioada Marii Migrații a gnuilor la Masai Mara (cea mai căutată); ianuarie–februarie e uscat și bun pentru safari. Aprilie–mai e sezon ploios. Ia haine în culori neutre.', en: 'July–October is the Great Migration season at Masai Mara (the most popular); January–February is dry and good for safari. April–May is the rainy season. Pack neutral-coloured clothes.', it: 'Da luglio a ottobre c\'è la Grande Migrazione al Masai Mara (la più richiesta); gennaio–febbraio è secco e ottimo per il safari. Aprile–maggio è stagione delle piogge. Porta abiti di colori neutri.' } },
        'bali': { alias: ['bali', 'indonezia', 'indonesia', 'ubud'],
            best: { ro: 'Aprilie–octombrie e sezonul uscat, cel mai bun; iulie–august e aglomerat. Noiembrie–martie e ploios, dar cald. La temple se poartă ținută decentă (umerii și genunchii acoperiți).', en: 'April–October is the dry season, the best; July–August is crowded. November–March is rainy but warm. At temples, dress modestly (shoulders and knees covered).', it: 'Da aprile a ottobre è la stagione secca, la migliore; luglio–agosto è affollato. Novembre–marzo è piovoso ma caldo. Nei templi vestiti in modo decoroso (spalle e ginocchia coperte).' } },
        'santorini': { alias: ['santorini', 'grecia', 'greece', 'oia'],
            best: { ro: 'Mai–octombrie; iunie și septembrie oferă cel mai bun raport între vreme, prețuri și aglomerație. Iulie–august e scump și aglomerat; iarna multe unități sunt închise.', en: 'May–October; June and September give the best balance of weather, prices and crowds. July–August is pricey and busy; many places close in winter.', it: 'Da maggio a ottobre; giugno e settembre offrono il miglior equilibrio tra clima, prezzi e folla. Luglio–agosto è caro e affollato; d\'inverno molte strutture chiudono.' } },
        'tokyo': { alias: ['tokyo', 'kyoto', 'japonia', 'japan', 'giappone', 'osaka'],
            best: { ro: 'Martie–aprilie pentru cireși înfloriți (sakura) și octombrie–noiembrie pentru frunzele de toamnă. Vara e cald și umed, iar iunie e sezonul ploilor. În Japonia nu se lasă bacșiș.', en: 'March–April for cherry blossoms (sakura) and October–November for autumn leaves. Summer is hot and humid and June is the rainy season. Tipping is not customary in Japan.', it: 'Marzo–aprile per i ciliegi in fiore (sakura) e ottobre–novembre per il foliage autunnale. L\'estate è calda e umida e giugno è la stagione delle piogge. In Giappone non si lascia la mancia.' } },
        'alpi-elvetia': { alias: ['alpi', 'alpii', 'alps', 'alpi elvetiei', 'elvetia', 'switzerland', 'svizzera', 'zermatt', 'interlaken', 'swiss'],
            best: { ro: 'Iunie–septembrie pentru drumeții și priveliști; decembrie–martie pentru schi. Aprilie–mai și octombrie–noiembrie sunt mai liniștite, dar unele telecabine sunt închise. Elveția e scumpă.', en: 'June–September for hiking and views; December–March for skiing. April–May and October–November are quieter but some cable cars are closed. Switzerland is expensive.', it: 'Da giugno a settembre per escursioni e panorami; da dicembre a marzo per lo sci. Aprile–maggio e ottobre–novembre sono più tranquilli ma alcune funivie sono chiuse. La Svizzera è cara.' } },
        'dubai': { alias: ['dubai', 'emiratele arabe', 'emirate', 'uae', 'emirati arabi', 'abu dhabi'],
            best: { ro: 'Noiembrie–martie (20–30°C) e perioada ideală; decembrie e cel mai scump. Vara depășește 40°C, deci activitățile sunt în interior. Ține cont de codul vestimentar și de legile locale.', en: 'November–March (20–30°C) is ideal; December is the most expensive. Summer tops 40°C, so activities are indoors. Respect the dress code and local laws.', it: 'Da novembre a marzo (20–30°C) è il periodo ideale; dicembre è il più caro. In estate si superano i 40°C, quindi si sta al chiuso. Rispetta il codice di abbigliamento e le leggi locali.' } },
        'cappadocia': { alias: ['cappadocia', 'capadocia', 'turcia', 'turkey', 'turchia', 'baloane', 'balon', 'balloon', 'montgolfiera', 'goreme'],
            best: { ro: 'Aprilie–iunie și septembrie–octombrie sunt cele mai plăcute. Zborurile cu balonul depind de vânt și pot fi anulate; iarna e frig și poate ninge, dar peisajul e spectaculos.', en: 'April–June and September–October are the nicest. Balloon flights depend on wind and can be cancelled; winter is cold with possible snow, but the scenery is spectacular.', it: 'Aprile–giugno e settembre–ottobre sono i più piacevoli. I voli in mongolfiera dipendono dal vento e possono essere annullati; l\'inverno è freddo con possibile neve, ma il paesaggio è spettacolare.' } },
        'newyork': { alias: ['new york', 'newyork', 'nyc', 'sua', 'usa', 'america', 'statele unite', 'stati uniti', 'manhattan'],
            best: { ro: 'Aprilie–iunie și septembrie–noiembrie sunt cele mai bune. Decembrie are iluminat festiv, dar e frig și scump; iulie–august e foarte cald și umed. Bacșișul în SUA e de 15–20%.', en: 'April–June and September–November are best. December has festive lights but is cold and pricey; July–August is very hot and humid. Tipping in the US is 15–20%.', it: 'Aprile–giugno e settembre–novembre sono i migliori. Dicembre ha luci festive ma è freddo e caro; luglio–agosto è molto caldo e umido. La mancia negli USA è del 15–20%.' } },
        'beijing-marele-zid': { alias: ['beijing', 'pekin', 'peking', 'marele zid', 'great wall', 'grande muraglia', 'orasul interzis', 'forbidden city'],
            best: { ro: 'Aprilie–mai și septembrie–octombrie. Iarna e foarte rece, vara fierbinte. Evită săptămâna națională din 1–7 octombrie și Anul Nou Chinezesc: sunt extrem de aglomerate.', en: 'April–May and September–October. Winter is very cold, summer scorching. Avoid the National Day week (1–7 October) and Chinese New Year: they are extremely crowded.', it: 'Aprile–maggio e settembre–ottobre. L\'inverno è molto freddo, l\'estate torrida. Evita la settimana della Festa Nazionale (1–7 ottobre) e il Capodanno cinese: sono affollatissimi.' } },
        'shanghai-metropola-futurului': { alias: ['shanghai', 'shangai'],
            best: { ro: 'Martie–mai și septembrie–noiembrie sunt cele mai plăcute. Iunie–iulie e umed, cu ploi frecvente, iar vara e caldă și lipicioasă.', en: 'March–May and September–November are the nicest. June–July is humid with frequent rain, and summer is hot and sticky.', it: 'Marzo–maggio e settembre–novembre sono i più piacevoli. Giugno–luglio è umido con piogge frequenti e l\'estate è calda e afosa.' } },
        'zhangjiajie-avatar': { alias: ['zhangjiajie', 'avatar', 'muntii avatar', 'montagne avatar'],
            best: { ro: 'Aprilie–octombrie; primăvara și toamna au peisaje cu ceață și culori frumoase. Vara e aglomerat și ploios, iarna e frig, cu zăpadă.', en: 'April–October; spring and autumn offer misty scenery and beautiful colours. Summer is crowded and rainy, winter is cold with snow.', it: 'Da aprile a ottobre; primavera e autunno offrono paesaggi con nebbia e bei colori. L\'estate è affollata e piovosa, l\'inverno freddo con neve.' } },
        'seoul-coreea': { alias: ['seoul', 'seul'],
            best: { ro: 'Aprilie–mai (cireși înfloriți) și septembrie–noiembrie (frunziș de toamnă). Iulie–august aduce ploi de vară; iarna e rece și uscată. Bacșișul nu e obișnuit.', en: 'April–May (cherry blossoms) and September–November (autumn foliage). July–August brings monsoon rains; winter is cold and dry. Tipping is not customary.', it: 'Aprile–maggio (ciliegi in fiore) e settembre–novembre (foliage autunnale). Luglio–agosto porta piogge monsoniche; l\'inverno è freddo e secco. La mancia non è usuale.' } },
        'busan-coreea': { alias: ['busan', 'pusan'],
            best: { ro: 'Mai–iunie și septembrie–octombrie; plajele sunt animate în iulie–august, dar e umed. Iarna e mai blândă decât la Seoul.', en: 'May–June and September–October; beaches are lively in July–August but it is humid. Winter is milder than in Seoul.', it: 'Maggio–giugno e settembre–ottobre; le spiagge sono animate a luglio–agosto ma è umido. L\'inverno è più mite che a Seoul.' } },
        'jeju-insula-vulcanica': { alias: ['jeju', 'insula jeju', 'jeju island', 'isola di jeju'],
            best: { ro: 'Aprilie (câmpuri de rapiță în floare) și septembrie–octombrie sunt cele mai bune. Vara e umedă și pot apărea taifunuri (august–septembrie); iarna e blândă, dar cu vânt.', en: 'April (blooming rapeseed fields) and September–October are best. Summer is humid and typhoons are possible (August–September); winter is mild but windy.', it: 'Aprile (campi di colza in fiore) e settembre–ottobre sono i migliori. L\'estate è umida e possibili tifoni (agosto–settembre); l\'inverno è mite ma ventoso.' } }
    });

    F.finish();
})(typeof window !== 'undefined' ? window : globalThis);
