/* FeelVoyage — răspunsuri preprogramate în limba spaniolă (ES).
   Completează, după id, intrările din js/faq-data-*.js (titlu, cuvinte-cheie, răspuns) și textele „cel mai bun moment" din js/faq-dest.js.
   Se încarcă lazy, o dată cu restul bazei de răspunsuri, când se deschide chatul. Dacă lipsește, chatul răspunde în engleză. */
(function (root) {
    'use strict';
    const F = root.FVFAQ;
    if (!F || !F.extend) return;

    F.extend('es', {
        "hello": { t: "👋 Hola", k: ["hola", "buenas", "buenos dias", "buenas tardes", "buenas noches", "que tal", "saludos"],
          a: "¡Hola! 👋 Soy el asistente virtual de FeelVoyage. Puedo ayudarte con destinos, precios, reservas e información de viaje. ¿Por dónde empezamos?" },
        "thanks": { t: "🙏 Gracias", k: ["gracias", "muchas gracias", "te lo agradezco", "mil gracias", "se agradece", "gracias por la ayuda"],
          a: "¡De nada! 😊 Si tienes más preguntas sobre destinos, precios o reservas, aquí estoy." },
        "bye": { t: "👋 Adiós", k: ["adios", "hasta luego", "hasta pronto", "nos vemos", "que tengas un buen dia", "buen viaje", "chao"],
          a: "¡Adiós y buen viaje! ✈️ Puedes contactarnos cuando quieras en el **{phone}** o en **{email}**." },
        "ok": { t: "👍 Vale", k: ["vale", "ok", "perfecto", "genial", "entendido", "de acuerdo", "muy bien", "estupendo"],
          a: "¡Perfecto! 😊 Si tienes más preguntas sobre destinos, precios o reservas, solo tienes que preguntar." },
        "human": { t: "🧑‍💼 Hablar con un asesor", k: ["asesor", "agente", "persona real", "hablar con alguien", "hablar con una persona", "operador", "llamadme", "llamenme", "asesor humano"],
          a: "Un asesor de FeelVoyage puede ayudarte:\n• **Teléfono / WhatsApp:** {phone}\n• **Correo:** {email}\n• **Horario:** {hours}\nTambién puedes enviar el formulario de la sección **Contacto** y un asesor se pondrá en contacto contigo." },
        "who": { t: "🤖 ¿Quién eres?", k: ["quien eres", "que eres", "eres un bot", "eres un robot", "eres una ia", "eres humano", "como te llamas", "cual es tu nombre", "quien sois"],
          a: "Soy el asistente virtual de FeelVoyage. Cuando el asistente de IA está disponible respondo con un modelo de IA; si no, uso respuestas preparadas por el equipo. Puedo ayudarte con destinos, precios y reservas, y un asesor confirma la oferta final." },
        "can-do": { t: "❓ ¿Qué puedes hacer?", k: ["que puedes hacer", "como puedes ayudarme", "ayuda", "ayudame", "para que sirves", "puedes ayudarme", "que haces"],
          a: "Puedo ayudarte con:\n• **Destinos y paquetes** ({count} en el catálogo) y recomendaciones según el presupuesto\n• **Precios** (por persona, niños, temporada, extras)\n• **Reservas**, pago y contacto\n• **Información de viaje**: documentos, moneda, clima, equipaje\nPrueba a preguntar: «¿Cuánto cuesta Roma?» o «¿Qué puedo hacer con 800 €?»." },
        "languages": { t: "🌐 Idiomas", k: ["hablas espanol", "que idiomas", "que idiomas hablas", "hablas ingles", "hablas rumano", "hablas italiano", "respondeme en espanol", "idiomas"],
          a: "Puedes escribir en **rumano, inglés, italiano, francés o español** y te responderé en el mismo idioma. También puedes cambiar el idioma del sitio con el botón **RO / EN / IT / FR / ES** de la cabecera o del menú." },
        "joke": { t: "😄 Un chiste", k: ["chiste", "cuentame un chiste", "algo gracioso", "hazme reir", "dime un chiste"],
          a: "Los chistes no son lo mío 😄, ¡pero las vacaciones sí! ¿Quieres que te sugiera un destino según tu presupuesto o el tipo de viaje (playa, montaña, escapada urbana)?" },
        "off-topic": { t: "Fuera de tema", k: ["python", "javascript", "escribe codigo", "codigo fuente", "programacion", "bitcoin", "crypto*", "ethereum", "politica", "elecciones", "presidente", "receta", "deberes", "ecuacion", "horoscopo", "poema"],
          a: "Solo puedo ayudarte con preguntas sobre la agencia FeelVoyage, nuestro sitio web y los destinos de vacaciones. 🌍 Pregúntame, por ejemplo, por los paquetes disponibles, los precios o qué ver en un destino." },
        "complaint": { t: "⚠️ Tengo un problema", k: ["queja", "reclamacion", "insatisfecho", "problema con mi", "tengo un problema", "no estoy contento", "no estoy satisfecho"],
          a: "¡Lamentamos las molestias! Para resolverlo rápido, escribe a **{email}** o llama al **{phone}** ({hours}) y cuéntanos brevemente qué ha pasado. Un asesor se hará cargo de tu caso." },
        "contact": { t: "📞 Contacto", k: ["contacto", "datos de contacto", "como contactaros", "como contactar", "contactaros", "ponerme en contacto", "comunicarme con vosotros", "contactar"],
          a: "Puedes contactarnos aquí:\n• **Teléfono / WhatsApp:** {phone}\n• **Correo:** {email}\n• **Oficina:** {address}\n• **Horario:** {hours}\n• **Facebook:** [FeelVoyage](https://www.facebook.com/share/19XnMiUthZ/?mibextid=wwXlfr)" },
        "phone": { t: "☎️ Teléfono", k: ["telefono", "numero de telefono", "llamar", "llamada", "puedo llamar", "llamaros", "numero"],
          a: "Puedes llamarnos al **{phone}** (también es nuestro número de WhatsApp). Horario: {hours}." },
        "email": { t: "✉️ Correo electrónico", k: ["correo", "email", "e mail", "direccion de correo", "escribiros", "por correo", "por email", "correo electronico"],
          a: "Puedes escribirnos a **{email}**. Para una oferta personalizada, indícanos el destino, las fechas y el número de viajeros; respondemos en 24 horas como máximo." },
        "whatsapp": { t: "💬 WhatsApp", k: ["whatsapp", "whats app", "mensaje de whatsapp", "grupo de whatsapp", "escribir por whatsapp"],
          a: "Puedes escribirnos por **WhatsApp** al **{phone}**. Durante tu viaje, tu asesor dedicado también crea un grupo de apoyo en WhatsApp." },
        "address": { t: "📍 Dirección", k: ["direccion", "donde estais", "donde esta la oficina", "donde esta vuestra oficina", "ubicacion", "sede", "mapa", "donde se encuentra la agencia"],
          a: "La oficina de FeelVoyage está en **{address}**, Rumanía. 📍 Horario: {hours}." },
        "hours": { t: "🕘 Horario", k: ["horario", "horarios", "abierto", "cerrado", "domingo", "sabado", "a que hora abris", "horario de fin de semana", "cuando estais abiertos"],
          a: "Horario: **{hours}**. No tenemos horario de oficina publicado para el domingo; puedes escribirnos cuando quieras por correo o WhatsApp y responderemos el siguiente día laborable." },
        "facebook": { t: "🔵 Facebook", k: ["facebook", "pagina de facebook", "fb", "redes sociales", "instagram", "redes"],
          a: "Sigue nuestra página de Facebook para ver ofertas, promociones y novedades: [FeelVoyage Facebook](https://www.facebook.com/share/19XnMiUthZ/?mibextid=wwXlfr) 🔵" },
        "about": { t: "ℹ️ Sobre nosotros", k: ["sobre vosotros", "sobre la agencia", "vuestra historia", "que es feelvoyage", "sobre feelvoyage", "hablame de la agencia", "presentacion de la agencia"],
          a: "FeelVoyage es una agencia de viajes de **Târgu Jiu (Gorj, Rumanía)** con **{count} destinos**, desde el litoral rumano hasta China y Corea del Sur. Construimos las vacaciones según tu presupuesto y tu ritmo, con precios transparentes y un asesor dedicado." },
        "why-us": { t: "⭐ ¿Por qué FeelVoyage?", k: ["por que elegiros", "por que elegir", "por que vosotros", "ventajas", "que os diferencia", "por que feelvoyage", "vuestros puntos fuertes"],
          a: "Lo que obtienes con nosotros:\n• **Asesoramiento gratuito** y una oferta personalizada en 24 horas\n• Precios en **EUR y lei**, con pago a plazos sin intereses en algunos paquetes\n• **Seguro** de viaje y asistencia médica opcionales\n• Un **asesor dedicado** y un grupo de WhatsApp durante tu viaje" },
        "consultant": { t: "🧑‍💼 Asesor dedicado", k: ["asesor dedicado", "quien me va a ayudar", "persona de contacto", "ayuda durante el viaje", "apoyo durante las vacaciones", "asistencia durante el viaje"],
          a: "Cada cliente tiene un **asesor dedicado**, desde la primera oferta hasta que vuelve a casa. Durante tu estancia también cuentas con un **grupo de apoyo en WhatsApp** para ayuda rápida." },
        "response-time": { t: "⏱️ ¿Con qué rapidez respondéis?", k: ["cuanto tardais", "cuando respondereis", "tiempo de respuesta", "cuando me contactareis", "en cuanto tiempo", "cuando recibo la oferta", "rapidez"],
          a: "Con el formulario de la sección **Contacto**, un asesor responde en un máximo de **2 horas laborables**. Recibes tu oferta personalizada en **24 horas**." },
        "visit-office": { t: "🏢 Visitar la oficina", k: ["visitar la oficina", "puedo ir", "cita", "conoceros en persona", "ir a la oficina", "pasar por la oficina"],
          a: "Sí, eres bienvenido en nuestra oficina: **{address}**. Horario: {hours}. Para una conversación dedicada, llama antes al **{phone}**." },
        "reviews": { t: "⭐ Opiniones", k: ["opiniones", "testimonios", "que dicen los clientes", "referencias", "valoraciones", "resenas", "opiniones de clientes"],
          a: "Por el momento no mostramos opiniones en el sitio. Encontrarás novedades y ofertas en [nuestra página de Facebook](https://www.facebook.com/share/19XnMiUthZ/?mibextid=wwXlfr); para referencias, pregunta a un asesor en el **{phone}**." },
        "how-to-book": { t: "🎫 ¿Cómo reservo?", k: ["como reservar", "como reservo", "quiero reservar", "reserva", "reservar", "hacer una reserva", "pasos para reservar"],
          a: "Reservar en el sitio, paso a paso:\n1. Elige un paquete y pulsa **Detalles del paquete**.\n2. Selecciona adultos/niños, **fechas de salida y regreso** y extras: ves la estimación al instante.\n3. Rellena tus datos y pulsa **Enviar solicitud de reserva**.\nUn asesor se pone en contacto contigo para confirmar. También puedes reservar por teléfono (**{phone}**) o en la oficina." },
        "request-offer": { t: "📝 Pedir una oferta", k: ["pedir una oferta", "solicitud de presupuesto", "pedir presupuesto", "quiero un presupuesto", "oferta personalizada", "formulario de contacto", "conseguir un presupuesto", "oferta a medida", "formulario de oferta"],
          a: "Para una **oferta personalizada**, rellena el formulario **«Enviar una solicitud de presupuesto»** de la sección **Contacto** (nombre, teléfono, correo, destino deseado, detalles). Un asesor se pone en contacto contigo en un máximo de 2 horas laborables." },
        "book-online": { t: "💻 Reservar online", k: ["reservar online", "reservar en la web", "reserva online", "reservar en el sitio", "reservar desde el movil", "reservar por internet"],
          a: "Sí, puedes enviar una **solicitud de reserva** directamente desde el sitio o el móvil, desde la ventana del paquete. No pagas en el sitio: un asesor se pone en contacto contigo, confirma la disponibilidad y acuerda el pago contigo." },
        "no-account": { t: "👤 ¿Necesito una cuenta?", k: ["necesito una cuenta", "sin cuenta", "cuenta obligatoria", "tengo que registrarme", "hace falta una cuenta", "cuenta necesaria"],
          a: "No, la **cuenta es opcional**: puedes enviar reservas y solicitudes de presupuesto sin ella. Con una cuenta, tus datos se rellenan automáticamente en los formularios." },
        "create-account": { t: "✍️ Crear una cuenta", k: ["crear cuenta", "crear una cuenta", "registrarme", "registro", "nueva cuenta", "como me registro", "abrir una cuenta"],
          a: "Pulsa el botón **Mi cuenta** de la cabecera (icono de usuario) → **Registrarse**. Indica tu nombre, tu **teléfono (obligatorio)**, tu correo y una contraseña de al menos 6 caracteres. La cuenta funciona en cualquier dispositivo con el mismo correo y la misma contraseña." },
        "login-help": { t: "🔑 Iniciar sesión", k: ["iniciar sesion", "acceder", "login", "olvide mi contrasena", "restablecer contrasena", "no puedo entrar", "cerrar sesion", "salir de mi cuenta"],
          a: "Iniciar sesión: botón **Mi cuenta** de la cabecera → correo y contraseña. Si olvidaste la contraseña, pulsa **«¿Olvidaste tu contraseña?»** (escribe antes tu correo) y recibirás un enlace para restablecerla. Para cerrar sesión, abre tu perfil y pulsa **Cerrar sesión**." },
        "account-benefits": { t: "🎁 Ventajas de la cuenta", k: ["ventajas de la cuenta", "por que crear una cuenta", "para que sirve la cuenta", "ventajas de registrarse", "beneficios de la cuenta"],
          a: "Con una cuenta: tu nombre, teléfono y correo se **rellenan automáticamente** al reservar, tienes la misma cuenta en **móvil y ordenador**, y las solicitudes salen más rápido. La cuenta sigue siendo opcional." },
        "cancel": { t: "❌ Cancelar una reserva", k: ["cancelar", "cancelacion", "reembolso", "devolucion del dinero", "penalizacion", "cancelar mi reserva", "quiero cancelar"],
          a: "Las condiciones de cancelación y las posibles penalizaciones dependen del paquete y se fijan al confirmar la oferta. Para tu caso, llama al **{phone}** o escribe a **{email}** lo antes posible." },
        "change-booking": { t: "🔄 Modificar una reserva", k: ["modificar mi reserva", "modificar la reserva", "cambiar la fecha", "aplazar", "posponer", "cambiar mi reserva"],
          a: "Los cambios (fechas, personas, servicios) se hacen con tu asesor, según la disponibilidad y las condiciones del paquete. Llama al **{phone}** o escribe a **{email}**." },
        "group": { t: "👥 Grupos", k: ["grupo", "grupos", "boda", "team building", "viaje de empresa", "viaje escolar", "grupo grande", "viaje en grupo"],
          a: "Sí, organizamos **reservas para grupos** (bodas, team building, viajes de empresa o escolares). Envía el formulario de presupuesto con el destino, las fechas y el número de personas, o llama al **{phone}**." },
        "custom-trip": { t: "🧭 Viaje a medida", k: ["viaje a medida", "a medida", "itinerario personalizado", "paquete personalizado", "destino que no esta", "no esta en vuestra lista", "viaje personalizado"],
          a: "No solo vendemos paquetes prefabricados: construimos **itinerarios personalizados** según tu presupuesto e intereses. Si tu destino no está en el catálogo, escríbenos a **{email}** o por el formulario de contacto y prepararemos una oferta." },
        "dates-how": { t: "📅 ¿Cómo elijo las fechas?", k: ["elegir fechas", "calendario", "fecha de salida", "fecha de regreso", "desde cuando hasta cuando", "seleccionar fechas", "elegir la fecha"],
          a: "En la ventana del paquete pulsa **Salida** y elige el día en el calendario (el primer día disponible es **mañana**). La fecha de **Regreso** se rellena con la duración estándar y, en los paquetes flexibles, puedes elegir otro día. Los circuitos guiados tienen duración fija. Las fechas se muestran como dd/mm/aaaa." },
        "travelers-how": { t: "🧍 Adultos y niños", k: ["cuantos viajeros", "adultos y ninos", "anadir ninos", "numero de personas", "cuantas personas", "anadir personas"],
          a: "En la ventana del paquete, en **Número de viajeros**, usa los botones **− / +** para adultos, niños de 0–4 años y niños de 5–12 años. El total y el precio por persona se actualizan al instante." },
        "after-request": { t: "📨 ¿Qué pasa después?", k: ["que pasa despues", "despues de enviar", "he enviado la solicitud", "nadie me ha contactado", "sin respuesta", "no he recibido respuesta", "ninguna respuesta"],
          a: "Tras enviar la solicitud, un asesor de FeelVoyage se pone en contacto contigo (con el formulario de contacto, en un máximo de 2 horas laborables). Si no has tenido noticias, llama al **{phone}** o escribe a **{email}**." },
        "payment": { t: "💳 Formas de pago", k: ["pago", "pagar", "como pagar", "formas de pago", "metodos de pago", "opciones de pago"],
          a: "El pago se realiza **solo después de hablar con un agente de FeelVoyage** y de recibir la oferta confirmada; **no se paga en el sitio**. Acuerdas la forma con tu asesor: **transferencia bancaria**, **pago a plazos** (para paquetes de más de 500 €) o **efectivo en la oficina**." },
        "installments": { t: "🧾 Pago a plazos", k: ["cuotas", "pago a plazos", "a plazos", "sin intereses", "pagar en cuotas", "pagar a plazos", "fraccionar el pago"],
          a: "Ofrecemos **pago a plazos** para paquetes de más de 500 €, y **sin intereses** en algunos paquetes. Pide los detalles al **{phone}** o a **{email}**." },
        "card-pay": { t: "💳 Pagar con tarjeta", k: ["tarjeta", "mastercard", "visa o mastercard", "con visa", "pagar con tarjeta", "tarjeta de credito", "tarjeta de debito"],
          a: "No se puede pagar con tarjeta en el sitio y **el pago se acuerda solo después de hablar con un agente de FeelVoyage**, que te indicará qué formas de pago hay disponibles para tu oferta. Llama al **{phone}** o escribe a **{email}**." },
        "advance": { t: "💶 Anticipo", k: ["anticipo", "senal", "deposito", "cuanto pago por adelantado", "pago por adelantado", "pagar por adelantado"],
          a: "Si hace falta un anticipo, y de cuánto, depende del paquete y se fija al confirmar la oferta. Consulta a un asesor en el **{phone}**." },
        "invoice": { t: "🧾 Factura", k: ["factura", "recibo", "factura de empresa", "iva", "factura para mi empresa", "factura a nombre de empresa"],
          a: "Para una factura (también a nombre de una empresa), da los datos a tu asesor al confirmar la reserva. Detalles en el **{phone}** o en **{email}**." },
        "vouchers": { t: "🎟️ Cheques vacaciones", k: ["cheques vacaciones", "bonos de vacaciones", "cheque regalo", "tarjeta regalo", "bono regalo", "vales"],
          a: "Para pagar con cheques de vacaciones, tarjetas o bonos regalo, pregunta a un asesor si se aceptan para el paquete que quieres: **{phone}**." },
        "pay-online": { t: "🌐 Pagar en el sitio", k: ["pagar en la web", "pago online", "pagar online", "pagar en el sitio", "pagar por internet"],
          a: "Por ahora **no se paga en el sitio**: este envía tu solicitud y el pago se acuerda después de hablar con un asesor (por ejemplo, transferencia bancaria o efectivo en la oficina)." },
        "price-ranges": { t: "💰 Precios", k: ["precios", "precio", "cuanto cuesta", "cuanto vale", "coste", "tarifas", "cuanto cuestan unas vacaciones", "presupuesto de vacaciones"],
          a: "Los precios dependen del destino, la temporada, la duración y el número de viajeros. «Desde» significa **por adulto, en habitación doble**. Como referencia:" },
        "price-from": { t: "❓ ¿Qué significa «desde»?", k: ["que significa desde", "precio desde", "precio mostrado", "precio por persona", "que significa el precio", "el precio de la tarjeta"],
          a: "El precio «desde» de la tarjeta es **por adulto**, en **habitación doble**, en **temporada baja** y para la **duración estándar** del paquete. Para tu total, abre el paquete y elige personas, fechas y extras: la estimación se recalcula al instante." },
        "single": { t: "🛏️ Habitación individual", k: ["suplemento individual", "habitacion individual", "viajar solo", "una persona", "viajero solo", "voy solo", "viajar sola"],
          a: "Un adulto que viaja solo en una habitación paga un **suplemento de habitación individual** (por noche, según el destino). Con 3 adultos, uno paga el suplemento; con un niño en la habitación no se aplica. La estimación de la ventana del paquete lo calcula automáticamente." },
        "kids-price": { t: "🧒 Precios para niños", k: ["precio nino", "precio ninos", "tarifa nino", "descuento nino", "descuento para ninos", "bebe", "ninos gratis", "lactante", "precio para un nino", "cuanto cuesta un nino", "precio para ninos", "cuanto pagan los ninos"],
          a: "Los niños pagan un porcentaje del precio de adulto según la edad: **Rumanía** 40 % (0–4 años) y 70 % (5–12 años); **escapadas urbanas, playa, montaña** 65 % y 85 %; **exóticos y Asia** 75 % y 85 %. Un niño que comparte habitación con **un solo adulto** paga el precio completo." },
        "season-price": { t: "🌞 Temporada y precios", k: ["temporada alta", "temporada baja", "precio por temporada", "precio verano", "precio invierno", "por que mas caro", "cuando es mas barato", "epoca mas barata", "cuando sale mas barato"],
          a: "El precio «desde» es para **temporada baja**. En los meses punta el precio sube (por ejemplo en la playa en julio–agosto, para esquiar en diciembre, en escapadas urbanas en diciembre y primavera). Elige tu fecha de salida en el calendario del paquete para ver el suplemento exacto." },
        "extras": { t: "➕ Servicios extra", k: ["extras", "servicios extra", "servicios adicionales", "opciones", "complementos", "que puedo anadir", "suplementos"],
          a: "En la ventana del paquete eliges extras: **traslado aeropuerto-hotel**, **mejora de comidas**, **entradas a atracciones**, **seguro de viaje**, **guía local**, **alquiler de coche** (y transporte en autocar en los paquetes de Rumanía). Algunos ya están incluidos; el precio de cada uno aparece a su lado." },
        "nights-flex": { t: "🌙 ¿Cuántas noches?", k: ["cuantas noches", "duracion de la estancia", "ampliar", "mas noches", "estancia mas larga", "estancia mas corta", "noches", "cuanto tiempo puedo quedarme"],
          a: "En los paquetes flexibles puedes elegir entre **2 y 14 noches** (5–21 en exóticos y Asia). El precio se ajusta: una parte (el vuelo) es fija y el resto crece con cada noche. Elige tus fechas en el calendario para ver la estimación." },
        "fixed-tours": { t: "🧭 Circuitos de duración fija", k: ["circuito", "circuitos", "duracion fija", "circuito guiado", "circuitos guiados", "visita guiada", "viaje organizado"],
          a: "Los circuitos guiados tienen **duración fija** y la fecha de regreso se calcula automáticamente. Son:" },
        "price-currency": { t: "💱 ¿Euros o lei?", k: ["euros o lei", "en que moneda estan los precios", "precios en euros", "precios en lei", "moneda de los precios", "en lei", "divisa de los precios"],
          a: "Los precios se muestran en **EUR** y en **lei** (cambio de referencia: 5 lei = 1 €). Tu asesor confirma el importe final, en lei o en euros." },
        "hidden-fees": { t: "🔎 Tasas y costes ocultos", k: ["costes ocultos", "gastos ocultos", "cargos extra", "tasa turistica", "impuesto turistico", "que no esta incluido", "otros gastos", "gastos adicionales"],
          a: "El precio que ves no tiene comisiones ocultas. La estimación **no incluye** gastos personales, **tasas turísticas locales** (donde se apliquen) ni entradas o excursiones opcionales que no hayas seleccionado. Un asesor confirma la oferta final." },
        "cheapest": { t: "🏷️ Los más baratos", k: ["mas barato*", "barato*", "precio mas bajo", "asequible*", "presupuesto ajustado", "economico*", "el mas asequible", "low cost"],
          a: "Nuestros paquetes más asequibles (precio «desde», por adulto):" },
        "priciest": { t: "💎 Lujo", k: ["mas caro*", "lujo", "premium", "alta gama", "deluxe", "el mejor"],
          a: "Nuestros paquetes más exclusivos (y más caros):" },
        "budget": { t: "🎯 Según el presupuesto", k: ["presupuesto", "budget", "tengo", "puedo gastar", "menos de", "hasta", "no mas de", "maximo", "mi presupuesto"],
          a: "Dime tu presupuesto." },
        "discounts": { t: "🎁 Descuentos y ofertas", k: ["descuentos", "promociones", "ofertas especiales", "chollos", "reserva anticipada", "ultima hora", "cupon", "codigo promocional", "ofertas"],
          a: "Las promociones y novedades aparecen en [nuestra página de Facebook](https://www.facebook.com/share/19XnMiUthZ/?mibextid=wwXlfr). Los precios del sitio son los base (temporada baja); para una oferta personalizada en 24 horas, envía el formulario de **Contacto** o llama al **{phone}**." },
        "price-includes": { t: "📋 ¿Qué incluye el precio?", k: ["que esta incluido", "que incluye el precio", "el paquete incluye", "que viene incluido", "que hay en el precio", "que incluye"],
          a: "Depende del paquete: en la ventana del paquete ves la lista de **Servicios y comodidades incluidos** y la etiqueta **Incluido** en los servicios. En los paquetes fuera de Rumanía el **vuelo está incluido**; en Rumanía, no. Los gastos personales, las tasas locales y los extras opcionales sin seleccionar no están incluidos." },
        "insurance": { t: "🛡️ Seguro de viaje", k: ["seguro", "seguro de viaje", "seguro medico", "seguro de cancelacion", "necesito un seguro"],
          a: "El **seguro de viaje** y la asistencia médica son opcionales en cualquier paquete (los añades como extra, con precio por persona y día). Siempre lo recomendamos, sobre todo fuera de la UE. Dentro de la UE también puedes tener la tarjeta sanitaria europea, pero no lo cubre todo (por ejemplo, la repatriación)." },
        "tickets-extra": { t: "🎫 Entradas a atracciones", k: ["entradas a atracciones", "entradas", "entradas a museos", "entradas sin colas", "tickets de entrada", "entradas de acceso"],
          a: "Las entradas a atracciones se pueden añadir como **servicio extra** (por persona, según el destino y la duración). Algunos paquetes ya incluyen una entrada, por ejemplo Roma: **entrada sin colas al Coliseo**." },
        "car-rental": { t: "🚗 Alquiler de coche", k: ["alquiler de coche", "alquilar un coche", "alquiler de coches", "coche de alquiler", "alquilar un vehiculo", "alquiler de auto"],
          a: "El **alquiler de coche** se añade como extra (precio por día y por coche; un coche para un máximo de 4 personas). No está disponible en **Maldivas**, en **China** ni en el **safari de Kenia**." },
        "transfer": { t: "🚐 Traslado al aeropuerto", k: ["traslado", "traslado aeropuerto", "traslado al hotel", "del aeropuerto al hotel", "shuttle", "transfer"],
          a: "El **traslado aeropuerto-hotel** se añade como extra (precio por persona, ida y vuelta). En **Maldivas**, el traslado (lancha rápida o hidroavión) cuesta más." },
        "guide": { t: "🧑‍🏫 Guía local", k: ["guia", "guia local", "guia turistico", "guia privado", "quiero un guia"],
          a: "Un **guía local privado** se añade como extra (precio por grupo y día, hasta 3 días). En los circuitos guiados (por ejemplo Tokio, Pekín, safari en Kenia) el guía ya está **incluido**." },
        "meals": { t: "🍽️ Comidas", k: ["comidas", "comida incluida", "media pension", "pension completa", "desayuno", "cena", "almuerzo", "que comemos"],
          a: "Las comidas dependen del paquete: **todo incluido**, pensión completa, media pensión o solo desayuno (mira la tarjeta del paquete). Donde las comidas no están incluidas, puedes añadir una **mejora de comidas** como extra." },
        "destinations-list": { t: "🌍 Destinos", k: ["destinos", "que destinos", "lista de destinos", "adonde puedo ir", "todos los destinos", "que paquetes teneis", "paquetes", "paquetes de viaje"],
          a: "Tenemos **{count} destinos** en el catálogo: **Rumanía** (Delta del Danubio, Poiana Brașov, Bran, Transfăgărășan, Desfiladero del Danubio, Maramureș, Sibiu y Sighișoara, Mamaia), **escapadas urbanas en Europa** (Roma, Barcelona, Londres, Praga, Viena, París), **playa y montaña** (Santorini, Alpes suizos), **exóticos** (Maldivas, Kenia, Bali, Tokio, Dubái, Capadocia, Nueva York) y **China y Corea del Sur** (Pekín, Shanghái, Zhangjiajie, Seúl, Busan, Jeju). Novedades: **América** (Yosemite, Gran Cañón, Horseshoe Bend, San Francisco, Hawái, Niágara, Banff, Machu Picchu, Río de Janeiro, Patagonia), **Reino Unido e Irlanda** (Edimburgo, isla de Skye, Cornualles, Irlanda), **norte de Europa** (Noruega, Islandia), **África** (Ciudad del Cabo, Marrakech, Egipto, Zanzíbar, Serengeti, cataratas Victoria, Namibia) y **Asia y Oceanía** (India, Vietnam, Tailandia, Jordania, Nueva Zelanda, Sídney)" },
        "romania": { t: "🇷🇴 Rumanía", k: ["rumania", "en rumania", "vacaciones en rumania", "destinos en rumania", "viaje a rumania", "viajar por rumania"],
          a: "¡Descubre la belleza de Rumanía! 🇷🇴 Nuestros paquetes en el país:" },
        "europe": { t: "🇪🇺 Europa", k: ["europa", "en europa", "europeo", "destinos europeos", "escapada urbana europa", "vacaciones en europa"],
          a: "Nuestras escapadas urbanas más populares en Europa: 🇪🇺" },
        "exotic": { t: "🏝️ Exóticos", k: ["exotic*", "exotico*", "destinos exoticos", "vacaciones exoticas", "viaje lejano", "destino lejano", "otro continente", "ultramar"],
          a: "Destinos exóticos y lejanos: 🏝️" },
        "beach": { t: "🏖️ Playa y mar", k: ["playa", "mar", "litoral", "vacaciones de sol", "sol y playa", "vacaciones de playa", "arena", "isla", "islas"],
          a: "Para playa y mar, te recomiendo: 🏖️" },
        "mountain": { t: "⛰️ Montaña", k: ["montana", "montanas", "esqui", "esquiar", "senderismo", "vacaciones en la montana", "alpino"],
          a: "Para montaña y naturaleza: ⛰️" },
        "city": { t: "🏙️ Escapada urbana", k: ["city break", "city breaks", "escapada urbana", "escapadas urbanas", "ciudades", "capitales", "vacaciones urbanas", "viaje a una ciudad"],
          a: "Para una escapada urbana: 🏙️" },
        "asia": { t: "🐉 China y Corea", k: ["china", "corea", "corea del sur", "asia", "chino", "en asia", "vacaciones en asia"],
          a: "Para China y Corea del Sur: 🐉" },
        "romantic": { t: "💑 Romántico", k: ["luna de miel", "pareja", "romantico", "aniversario", "para dos", "compromiso", "escapada romantica", "viaje de novios"],
          a: "Para una escapada romántica (luna de miel, aniversario): 💑" },
        "family": { t: "👨‍👩‍👧 En familia", k: ["familia", "con ninos", "con hijos", "vacaciones en familia", "viaje en familia", "ninos pequenos", "para la familia", "familiar"],
          a: "Para unas vacaciones en familia, te sugiero: 👨‍👩‍👧" },
        "adventure": { t: "🧗 Aventura", k: ["aventura", "naturaleza", "adrenalina", "vacaciones activas", "paisajes", "fauna", "aire libre"],
          a: "Para aventura y naturaleza: 🧗" },
        "culture": { t: "🏛️ Cultura e historia", k: ["cultura", "historia", "museos", "monumentos", "arquitectura", "patrimonio", "viaje cultural"],
          a: "Para cultura e historia: 🏛️" },
        "weekend": { t: "📆 Para un fin de semana", k: ["fin de semana", "finde", "viaje corto", "escapada corta", "unos dias", "escapada rapida", "vacaciones cortas"],
          a: "Para una escapada corta (2–3 noches): 📆" },
        "longtrip": { t: "🗓️ Viaje largo", k: ["viaje largo", "dos semanas", "vacaciones largas", "estancia larga", "una semana", "para una semana", "mucho tiempo"],
          a: "Para una estancia más larga (8 noches o más): 🗓️" },
        "winter": { t: "❄️ Invierno", k: ["invierno", "navidad", "ano nuevo", "vacaciones de invierno", "escapada de invierno", "nieve", "fiestas navidenas"],
          a: "Para unas vacaciones de invierno (nieve o sol, como prefieras): ❄️" },
        "summer": { t: "☀️ Verano", k: ["verano", "vacaciones de verano", "calor", "en julio", "en agosto", "julio", "agosto", "caluroso"],
          a: "Para unas vacaciones de verano: ☀️" },
        "allinclusive": { t: "🍹 Todo incluido", k: ["todo incluido", "all inclusive", "bebidas incluidas", "todo pagado", "all in"],
          a: "Paquetes **todo incluido**: 🍹" },
        "flight-included": { t: "✈️ ¿Está incluido el vuelo?", k: ["vuelo incluido", "en avion", "billete de avion", "vuelo", "vuelos", "precio del vuelo", "incluis los vuelos", "con vuelo"],
          a: "En los paquetes fuera de Rumanía el **vuelo está incluido** (mira «Vuelo incluido» en la lista de servicios incluidos). En los paquetes de Rumanía el transporte no está incluido, pero puedes añadir **transporte en autocar** como extra. Tu asesor confirma los detalles del vuelo (aeropuerto, horarios)." },
        "docs": { t: "🛂 Documentos", k: ["documentos", "pasaporte", "dni", "carnet de identidad", "que documentos", "documentos de viaje", "validez del pasaporte", "necesito pasaporte"],
          a: "En la **UE y el espacio Schengen** (incluida Suiza) normalmente puedes viajar con un **documento de identidad** en vigor o un pasaporte. Para el **Reino Unido** y los países fuera de Europa (Asia, África, Estados Unidos, Emiratos) hace falta un **pasaporte válido**, normalmente con 6 meses de validez tras tu regreso, y algunos países exigen visado o autorización electrónica. Comprueba siempre los requisitos oficiales según tu nacionalidad (para ciudadanos rumanos: la guía de viaje del Ministerio de Asuntos Exteriores de Rumanía) antes de salir." },
        "visa": { t: "🛃 Visado", k: ["visado", "visados", "visa", "autorizacion electronica", "eta", "etias", "e visa", "evisa", "necesito visado"],
          a: "Si necesitas visado depende del país y de tu nacionalidad, y puede cambiar. Por ejemplo, el **Reino Unido** (ETA), **Estados Unidos** (ESTA), **Kenia** (autorización electrónica) e **Indonesia / Bali** (visado a la llegada, tasa turística) tienen normas especiales. Consulta la web oficial del ministerio de Asuntos Exteriores y pregunta a un asesor en el **{phone}**." },
        "vaccines": { t: "💉 Vacunas y salud", k: ["vacuna", "vacunas", "vacunacion", "paludismo", "malaria", "salud", "medico", "necesito una vacuna", "precauciones sanitarias"],
          a: "Para destinos exóticos (por ejemplo Kenia, Bali) recomendamos consultar a tu médico o a un centro de medicina del viajero **4–6 semanas antes** de la salida. Las recomendaciones oficiales (ministerio de Asuntos Exteriores, OMS) cambian, así que compruébalas antes de viajar. No podemos dar consejo médico." },
        "luggage": { t: "🧳 Equipaje", k: ["equipaje", "maleta", "equipaje de mano", "equipaje facturado", "limite de peso", "cuantos kilos", "peso permitido"],
          a: "Las normas de equipaje dependen de la **aerolínea** y de la tarifa de tu billete; compruébalas antes de volar. En el equipaje de mano, los líquidos suelen limitarse a envases de **100 ml**, en una bolsa transparente." },
        "airport-time": { t: "🕐 Cuándo llegar al aeropuerto", k: ["cuando llegar", "con cuanta antelacion", "llegada al aeropuerto", "facturacion", "embarque", "a que hora estar en el aeropuerto"],
          a: "En vuelos internacionales llega al aeropuerto **2–3 horas antes**. Muchas aerolíneas permiten el **check-in online** con 24–48 horas de antelación. El aeropuerto y los horarios exactos figuran en los documentos de tu asesor." },
        "money": { t: "💶 Moneda y cambio", k: ["cambio de moneda", "donde cambiar dinero", "que moneda", "dinero en el extranjero", "moneda local", "efectivo en el extranjero", "que divisa usan"],
          a: "En la zona euro (Roma, París, Viena, Barcelona...) se usa el **euro**. Otras monedas: libra esterlina (Londres), corona checa (Praga), franco suizo (Suiza), dólar estadounidense (Nueva York), yen (Japón), won (Corea), dírham (Dubái), yuan (China), rupia indonesia (Bali), chelín keniano (Kenia), rufiyaa (Maldivas; los dólares estadounidenses se aceptan ampliamente). Cambia en bancos o casas de cambio, no en el aeropuerto." },
        "cards": { t: "💳 Tarjetas en el extranjero", k: ["tarjeta en el extranjero", "comisiones de tarjeta", "pagar con tarjeta en el extranjero", "avisar al banco", "revolut", "apple pay", "tarjeta en otro pais"],
          a: "Las tarjetas **Visa / Mastercard** se aceptan ampliamente. Consulta las comisiones de tu banco por pagos en otras monedas, avisa a tu banco de que viajas y lleva algo de **efectivo**. En **China** los pagos por móvil (Alipay / WeChat Pay) son muy habituales: configúralos antes de salir." },
        "roaming": { t: "📶 Internet y roaming", k: ["roaming", "itinerancia", "internet en el extranjero", "esim", "tarjeta sim", "datos moviles", "wifi", "datos en el extranjero"],
          a: "En la **UE/EEE** el roaming se factura como en tu país (según la política de tu operador). Fuera de la UE puede ser caro: elige un bono de roaming, una **eSIM** o una SIM local. En **China** algunas aplicaciones (Google, WhatsApp) pueden estar restringidas: prepárate con antelación." },
        "adapters": { t: "🔌 Enchufes y adaptadores", k: ["enchufe", "enchufes", "adaptador", "voltaje", "tension", "cargador", "tipo de enchufe"],
          a: "**UE:** enchufes compatibles (tipo C/F). **Reino Unido, Dubái, Kenia:** tipo G. **Suiza:** tipo J. **Estados Unidos y Japón:** tipo A/B, 100–120 V. **China:** tipo A/C/I. **Corea del Sur y Bali:** tipo C/F, 230 V. **Maldivas:** tipo D/G/J. Lo más fácil: un **adaptador universal**." },
        "timezone": { t: "🕰️ Husos horarios y jet lag", k: ["huso horario", "diferencia horaria", "jet lag", "hora local", "jetlag", "cambio de hora"],
          a: "Diferencias aproximadas con Rumanía (varían con el horario de verano): Europa central −1 h; Londres −2 h; Grecia 0; Turquía 0/+1 h; Dubái +1/+2 h; Kenia 0/+1 h; Maldivas +2/+3 h; Pekín, Shanghái, Bali +5/+6 h; Tokio, Seúl +6/+7 h; Nueva York −7 h. En vuelos largos, adelanta tu horario de sueño 1–2 días antes." },
        "packing": { t: "🎒 ¿Qué llevo?", k: ["que llevar", "lista de equipaje", "que debo llevar", "que meto en la maleta", "como hacer la maleta", "que ropa", "que necesito llevar", "hacer la maleta"],
          a: "Lo básico: **documentos y seguro**, dinero/tarjeta, móvil + cargador + **adaptador**, medicación personal, ropa por capas según el tiempo, **protector solar**, calzado cómodo y una mochila pequeña para las excursiones. Mira la previsión unos días antes." },
        "kids-travel": { t: "👶 Viajar con niños", k: ["viajar con ninos", "nino en avion", "menores", "autorizacion de los padres", "documentos del nino", "documentos de los ninos", "menor"],
          a: "Cada niño necesita su **propio documento** (documento de identidad o pasaporte). Si un menor viaja al extranjero con un solo progenitor o con otra persona, puede exigirse la **autorización notarial del otro progenitor** y otros papeles: consulta las normas a la **Policía de Fronteras** antes de salir." },
        "accessibility": { t: "♿ Accesibilidad", k: ["discapacidad", "accesibilidad", "silla de ruedas", "movilidad reducida", "necesidades especiales", "persona con discapacidad", "minusvalia"],
          a: "Cuéntanos tus necesidades de antemano (movilidad reducida, silla de ruedas, etc.) en el formulario de **Contacto** o en el **{phone}**. Consultamos la accesibilidad con nuestros socios, pero no todos los lugares son accesibles." },
        "diet": { t: "🥗 Alergias y dieta", k: ["alergias", "alergia", "vegetariano", "vegano", "sin gluten", "halal", "kosher", "dieta", "intolerancia", "regimen alimentario"],
          a: "Indica tus alergias o necesidades alimentarias (vegetariano, sin gluten, halal, etc.) en tu solicitud de reserva. Los hoteles normalmente pueden adaptar el menú si se les avisa con antelación, pero no podemos garantizar todas las dietas en todas partes." },
        "safety": { t: "🔒 Seguridad", k: ["es seguro", "seguridad", "peligroso", "riesgos", "avisos de viaje", "es peligroso", "recomendaciones de viaje"],
          a: "Antes de salir, consulta las **recomendaciones de viaje** de tu ministerio de Asuntos Exteriores para el destino, contrata un **seguro de viaje**, guarda copias de tus documentos y vigila tus pertenencias en zonas concurridas. Tu asesor puede compartir lo que sabe del destino." },
        "weather": { t: "🌦️ Clima", k: ["que tiempo hace", "clima", "prevision del tiempo", "que temperatura", "como esta el tiempo", "meteorologia", "el tiempo en"],
          a: "El clima depende del destino y del mes. Dime el destino (por ejemplo «¿Cuál es la mejor época para Bali?») y te daré detalles por temporada. Unos días antes de salir, consulta la **previsión del tiempo**." },
        "best-time-general": { t: "📅 Mejor época", k: ["mejor momento para ir", "cuando ir", "que mes es mejor", "mejor epoca", "cuando merece la pena ir", "en que mes ir"],
          a: "En resumen: **playa** junio–septiembre; **esquí** diciembre–marzo; **escapadas urbanas** abril–junio y septiembre–octubre; **Maldivas y Dubái** noviembre–abril; **safari en Kenia** julio–octubre. Dime el destino (por ejemplo «¿Cuándo ir a Bali?») y te daré detalles." },
        "tipping": { t: "🪙 Propinas", k: ["propina", "propinas", "cuanta propina dejar", "dejar propina", "tip", "gratificacion"],
          a: "Aproximadamente: **Estados Unidos (Nueva York)** 15–20 % en restaurantes; **Europa** 5–10 % si el servicio no está incluido en la cuenta; **Japón y Corea del Sur** no se deja propina; en **Kenia, Bali, Maldivas y Dubái** se agradece alrededor del 10 % (comprueba si el servicio ya está incluido)." },
        "delays": { t: "⏳ Vuelo retrasado o cancelado", k: ["vuelo retrasado", "vuelo cancelado", "vuelo perdido", "maleta perdida", "equipaje perdido", "indemnizacion", "retraso del vuelo", "he perdido mi vuelo"],
          a: "Si tu vuelo se retrasa o se cancela, contacta primero con la **aerolínea** y conserva tus documentos. También puedes llamarnos al **{phone}**. En la UE los pasajeros tienen derechos (asistencia y, a veces, indemnización), y el **seguro de viaje** puede cubrir el equipaje perdido o gastos adicionales." },
        "language-site": { t: "🌐 Cambiar el idioma del sitio", k: ["cambiar de idioma", "cambiar el idioma", "idioma del sitio", "traducir el sitio", "sitio en espanol", "pasar a espanol", "cambiar idioma"],
          a: "Cambia el idioma del sitio con el botón **RO / EN / IT / FR / ES** de la cabecera (en el móvil, en el menú). Los textos, los paquetes y el chat se traducen al instante." },
        "dark-mode": { t: "🌙 Modo oscuro", k: ["modo oscuro", "modo claro", "tema oscuro", "tema", "cambiar de tema", "modo noche"],
          a: "Cambia entre modo **claro y oscuro** con el botón **luna / sol** de la cabecera. Por defecto, el sitio sigue el ajuste de tu móvil u ordenador hasta que elijas." },
        "filters": { t: "🔎 Búsqueda y filtros", k: ["filtros", "filtro", "busqueda", "como buscar", "encontrar un destino", "filtro de presupuesto", "buscar"],
          a: "Arriba, en el buscador, elige el **destino**, el **tipo de vacaciones** y tu **presupuesto máximo**. En la sección **Destinos y paquetes** también hay botones de categoría (Rumanía, playa, montaña, escapada urbana, exóticos, China y Corea). En el móvil, los botones se desplazan hacia los lados." },
        "package-details": { t: "🖼️ Detalles del paquete", k: ["detalles del paquete", "galeria de fotos", "fotos", "imagenes", "abrir el paquete", "ver el paquete"],
          a: "Pulsa **Detalles del paquete** en una tarjeta de destino: verás la galería de 4 fotos, la descripción, los servicios, la **calculadora de precio** (personas, fechas, extras) y el formulario de reserva." },
        "mobile": { t: "📱 En mi móvil", k: ["app", "aplicacion", "aplicacion movil", "en mi movil", "descargar", "sitio movil", "hay una app"],
          a: "No tenemos aplicación: el sitio está **optimizado para móviles** y funciona directamente en tu navegador. Puedes añadirlo a tu pantalla de inicio desde el menú del navegador («Añadir a la pantalla de inicio»)." },
        "chat-help": { t: "💬 ¿Cómo uso el chat?", k: ["como funciona el chat", "como usar el chat", "ayuda del chat", "chat", "asistente virtual", "conversacion en linea"],
          a: "Escribe tu pregunta o pulsa los botones sugeridos. Cuando el asistente de IA está disponible, respondo libremente a preguntas sobre la agencia, el sitio y los destinos; si no, uso respuestas preparadas. También puedo abrirte paquetes con el botón **«Ver paquete»**." },
        "counter": { t: "❤️ Contador «Viajeros felices»", k: ["viajeros felices", "contador", "que es el contador", "contador de viajeros"],
          a: "**«Viajeros felices»** es un contador en directo: cada clic suma 1 y todos los visitantes de la página ven cambiar el número en tiempo real." },
        "privacy": { t: "🔐 Datos personales", k: ["datos personales", "rgpd", "privacidad", "proteccion de datos", "mis datos", "cookies", "mis datos estan seguros"],
          a: "Los datos de los formularios (nombre, teléfono, correo) se usan para contactarte sobre tu solicitud. **No escribas datos personales en el chat**: usa los formularios. La cuenta es opcional. Para más información sobre tus datos, escribe a **{email}**." },
        "tech-issue": { t: "🛠️ El sitio no funciona", k: ["no funciona", "error", "no carga", "problema tecnico", "bug", "bloqueado", "el sitio no funciona", "pagina en blanco"],
          a: "Prueba a **recargar la página** (Ctrl+F5, o desliza hacia abajo en el móvil), abrir el sitio en otro navegador o en modo privado. Si el problema continúa, escribe a **{email}** con una captura de pantalla y el dispositivo que usas." }
    });

    F.extendDest('es', {
        "delta-dunarii": "Lo mejor es mayo–junio y septiembre: clima suave, muchas aves migratorias y menos mosquitos que en julio. El verano es caluroso; el invierno, frío y tranquilo.",
        "poiana-brasov": "Invierno (diciembre–marzo) para esquí y spa; verano (junio–septiembre) para senderismo y telecabina. Las fiestas de invierno son la época más concurrida.",
        "bran-brasov": "Finales de primavera y otoño (mayo–junio, septiembre–octubre) son ideales; el invierno es bonito pero frío. Los fines de semana de verano el castillo está muy concurrido.",
        "transfagarasan": "La carretera de alta montaña suele estar abierta solo en verano, aproximadamente de julio a octubre. Comprueba el estado de la carretera antes de ir; arriba puede hacer frío incluso en agosto.",
        "cazanele-dunarii": "De mayo a septiembre para el crucero por el Danubio; primavera y otoño son agradables, mientras que julio–agosto es caluroso.",
        "maramures": "Junio–octubre: buen tiempo para los pueblos y el senderismo; el otoño trae colores preciosos y fiestas tradicionales. Los inviernos son fríos y con nieve.",
        "sibiu-sighisoara": "Mayo–junio y septiembre–octubre son los más agradables; en julio se celebra el Festival de la Sighișoara Medieval y en diciembre llega el conocido mercado navideño de Sibiu.",
        "mamaia-constanta": "Junio–septiembre. Julio–agosto es la época más calurosa, más concurrida (y más cara); junio y septiembre son más tranquilos y con el mar aún agradable.",
        "roma": "Abril–junio y septiembre–octubre: temperaturas agradables. Julio–agosto es muy caluroso; el invierno es más tranquilo y barato. Reserva con antelación las entradas del Coliseo y del Vaticano.",
        "barcelona": "Mayo–junio y septiembre–octubre: buen tiempo y menos turistas. El verano es caluroso y bueno para la playa; el invierno es suave.",
        "londra": "De mayo a septiembre hace más calor y menos lluvia, pero puede llover en cualquier momento, así que lleva paraguas. Diciembre tiene luces y mercadillos navideños, pero hace frío.",
        "praga": "Abril–mayo y septiembre–octubre son ideales; diciembre tiene bonitos mercadillos navideños pero hace frío. El verano está muy concurrido.",
        "viena": "Abril–mayo y septiembre–octubre para pasear y visitar museos; diciembre trae los mercadillos navideños (frío, pero con un ambiente especial).",
        "paris": "Abril–junio y septiembre–octubre son los meses más bonitos; el verano está lleno de gente, el invierno es más barato y tranquilo. Reserva con antelación las entradas de la Torre Eiffel y del Louvre.",
        "maldive-deluxe": "Diciembre–abril es la estación seca, con más sol (y los precios más altos). Mayo–noviembre es la estación de lluvias, con precios más bajos y chubascos cortos.",
        "kenya-safari": "Julio–octubre es la temporada de la Gran Migración en Masai Mara (la más popular); enero–febrero es seco y bueno para el safari. Abril–mayo es la estación de lluvias. Lleva ropa de colores neutros.",
        "bali": "Abril–octubre es la estación seca, la mejor; julio–agosto está concurrido. Noviembre–marzo es lluvioso pero cálido. En los templos, viste con recato (hombros y rodillas cubiertos).",
        "santorini": "Mayo–octubre; junio y septiembre ofrecen el mejor equilibrio entre clima, precios y afluencia. Julio–agosto es caro y concurrido; muchos locales cierran en invierno.",
        "tokyo": "Marzo–abril para los cerezos en flor (sakura) y octubre–noviembre para las hojas de otoño. El verano es caluroso y húmedo y junio es la estación de lluvias. En Japón no se acostumbra dejar propina.",
        "alpi-elvetia": "Junio–septiembre para senderismo y vistas; diciembre–marzo para esquiar. Abril–mayo y octubre–noviembre son más tranquilos, pero algunos teleféricos están cerrados. Suiza es cara.",
        "dubai": "Noviembre–marzo (20–30 °C) es lo ideal; diciembre es el mes más caro. El verano supera los 40 °C, así que las actividades son en interiores. Respeta el código de vestimenta y las leyes locales.",
        "cappadocia": "Abril–junio y septiembre–octubre son los meses más bonitos. Los vuelos en globo dependen del viento y pueden cancelarse; el invierno es frío, con posible nieve, pero el paisaje es espectacular.",
        "newyork": "Abril–junio y septiembre–noviembre son lo mejor. Diciembre tiene luces festivas pero hace frío y es caro; julio–agosto es muy caluroso y húmedo. La propina en Estados Unidos es del 15–20 %.",
        "beijing-marele-zid": "Abril–mayo y septiembre–octubre. El invierno es muy frío y el verano, achicharrante. Evita la semana de la Fiesta Nacional (1–7 de octubre) y el Año Nuevo chino: hay muchísima gente.",
        "shanghai-metropola-futurului": "Marzo–mayo y septiembre–noviembre son los meses más agradables. Junio–julio es húmedo con lluvias frecuentes, y el verano es caluroso y bochornoso.",
        "zhangjiajie-avatar": "Abril–octubre; primavera y otoño ofrecen paisajes con niebla y colores preciosos. El verano está concurrido y lluvioso; el invierno es frío, con nieve.",
        "seoul-coreea": "Abril–mayo (cerezos en flor) y septiembre–noviembre (follaje otoñal). Julio–agosto trae lluvias monzónicas; el invierno es frío y seco. No se acostumbra dejar propina.",
        "busan-coreea": "Mayo–junio y septiembre–octubre; las playas están animadas en julio–agosto, pero hay humedad. El invierno es más suave que en Seúl.",
        "jeju-insula-vulcanica": "Abril (campos de colza en flor) y septiembre–octubre son lo mejor. El verano es húmedo y puede haber tifones (agosto–septiembre); el invierno es suave pero ventoso.",
        "yosemite": "De mayo a septiembre: las cascadas son más potentes en mayo–junio y las carreteras de altura suelen abrir a principios del verano. El invierno es bonito y tranquilo, pero algunas zonas están cerradas.",
        "grand-canyon": "De marzo a mayo y de septiembre a noviembre: temperaturas agradables. El verano es muy caluroso en el fondo del cañón y en invierno puede nevar en el borde, pero hay tranquilidad.",
        "san-francisco": "Septiembre–octubre suelen ser los meses más despejados y cálidos; el verano suele ser fresco y con niebla, incluso en julio. Lleva siempre una chaqueta.",
        "hawaii": "De abril a junio y de septiembre a octubre: buen tiempo y precios más bajos. Diciembre–marzo es la temporada de olas grandes y ballenas; el verano es cálido y concurrido.",
        "banff": "De junio a septiembre para senderismo y lagos sin hielo (el lago Louise suele deshelarse en junio); de diciembre a marzo para esquiar. A finales de septiembre llegan los colores dorados del otoño.",
        "machu-picchu": "De mayo a septiembre es la temporada seca, la mejor para la subida; junio–agosto está muy concurrido. Enero–marzo trae lluvias abundantes y en febrero el Camino Inca está cerrado.",
        "rio": "De abril a junio y de septiembre a octubre: calor, menos lluvia y menos turistas. Diciembre–marzo es verano, muy caluroso, y el Carnaval se celebra en febrero o marzo.",
        "patagonia": "De noviembre a marzo es el verano austral: días largos y senderos abiertos. El viento es fuerte casi todo el año, así que lleva varias capas de ropa.",
        "edinburgh": "De mayo a septiembre es lo más agradable; en agosto se celebra el Festival Fringe (muy concurrido y caro) y diciembre trae mercadillos navideños y Hogmanay. Lleva siempre un impermeable.",
        "norvegia-fiorduri": "De mayo a septiembre para cruceros y carreteras de montaña abiertas; junio–julio tienen días largos y noches luminosas. El invierno es precioso, pero algunas carreteras y barcos no operan.",
        "cape-town": "De noviembre a marzo es verano, con playas y días largos; octubre–abril es ideal para subir a Table Mountain. Junio–agosto es la temporada fresca y lluviosa.",
        "niagara": "De mayo a septiembre: tiempo cálido y paseos en barco en servicio; junio–agosto está concurrido. En invierno las cataratas se congelan en parte y son espectaculares, pero los barcos no operan.",
        "skye": "De mayo a septiembre: días largos y tiempo más suave; en verano también hay mosquitos (midges). El tiempo cambia rápido todo el año, así que lleva impermeable y varias capas.",
        "lofoten": "De septiembre a marzo para las auroras boreales (noches oscuras, aunque el cielo despejado nunca está garantizado); de junio a agosto para el sol de medianoche y el senderismo. El invierno es frío, con días cortos.",
        "irlanda": "De mayo a septiembre: días largos y tiempo más suave, pero puede llover en cualquier momento. A primera hora o a última hora de la tarde hay menos turistas en los acantilados.",
        "islanda": "De junio a agosto: carreteras abiertas, días largos y atardeceres tardíos; de septiembre a marzo para las auroras boreales. En invierno las carreteras pueden estar cerradas y los días son cortos.",
        "marrakech": "De marzo a mayo y de septiembre a noviembre: temperaturas agradables. Julio–agosto es muy caluroso (más de 35 °C) y en invierno las noches son frescas.",
        "egipt": "De octubre a abril: temperaturas agradables; julio–agosto es muy caluroso, sobre todo en el sur. A primera hora en las pirámides hace más fresco y hay menos gente.",
        "zanzibar": "De junio a octubre y de diciembre a febrero: tiempo seco y mar en calma. Abril–mayo son las lluvias fuertes y algunos alojamientos pueden estar cerrados.",
        "serengeti": "De junio a octubre: la estación seca, la mejor para ver animales; la migración de los ñus suele cruzar el río Mara en julio–septiembre. Enero–febrero es la temporada de partos en el sur.",
        "victoria-falls": "De febrero a mayo: caudal máximo y mucha bruma (la vista puede quedar tapada); de junio a octubre: menos agua, vistas más despejadas y estación seca para los safaris.",
        "namibia": "De mayo a octubre: estación seca, días despejados y noches frías; junio–agosto tiene las noches más frías. El verano (noviembre–marzo) es muy caluroso, con lluvias escasas.",
        "india": "De octubre a marzo: tiempo más fresco y seco, ideal para visitar. Abril–junio es muy caluroso (más de 40 °C) y julio–septiembre trae el monzón.",
        "halong": "De octubre a abril: tiempo más seco y fresco; marzo–abril puede haber niebla. Junio–septiembre es caluroso y húmedo, con riesgo de tormentas y tifones.",
        "noua-zeelanda": "De diciembre a marzo: verano, días largos y senderos abiertos; octubre–abril es bueno para los cruceros. Junio–agosto es invierno, más frío, con nieve en la montaña.",
        "sydney": "De septiembre a noviembre y de marzo a mayo: temperaturas agradables y menos turistas. Diciembre–febrero es verano, con playa y precios más altos; junio–agosto es un invierno suave.",
        "petra": "De marzo a mayo y de septiembre a noviembre: temperaturas agradables para caminar. El verano es muy caluroso y el invierno puede ser frío y lluvioso; a primera hora hay más tranquilidad.",
        "krabi": "De noviembre a abril: la estación seca y el mar en calma, lo mejor para la playa. Mayo–octubre es la estación de lluvias, con más oleaje y menos excursiones en barco.",
        "cornwall": "De mayo a septiembre: el periodo más cálido y seco, ideal para playas y senderos costeros; julio–agosto está concurrido. La primavera y el otoño son más tranquilos, pero con tiempo cambiante.",
        "horseshoe-bend": "De marzo a mayo y de septiembre a noviembre: temperaturas agradables. El verano es muy caluroso al mediodía; el mejor momento para fotos es al atardecer o al amanecer."
    });
})(typeof window !== 'undefined' ? window : globalThis);
