/* FeelVoyage — răspunsuri preprogramate, partea 1: mesaje scurte, agenție și contact, rezervări, plată.
   Structura unei intrări (o poți copia ca să adaugi una nouă):
     { id: 'nume-unic', next: ['alt-id', 'alt-id'],        // butoanele care apar sub răspuns
       ro: { t: 'Titlu scurt (etichetă de buton)', k: ['cuvinte-cheie', 'fraze', 'stem*'], a: 'Răspunsul' },
       en: { ... }, it: { ... } }
   Cuvintele-cheie se scriu fără grijă de diacritice și majuscule. „stem*" potrivește orice cuvânt care începe așa.
   În răspunsuri: **bold**, \n pentru rând nou și {phone} {email} {address} {hours} {count} (se completează singure). */
(function (root) {
    'use strict';
    const F = root.FVFAQ;
    if (!F) return;
    const FB = 'https://www.facebook.com/share/19XnMiUthZ/?mibextid=wwXlfr';

    F.register([

        /* ==================================================== MESAJE SCURTE ==================================================== */
        { id: 'hello', short: true, local: true, next: ['can-do', 'destinations-list', 'contact'],
          ro: { t: '👋 Salut', k: ['salut', 'buna', 'buna ziua', 'buna seara', 'buna dimineata', 'hei', 'servus', 'noroc'], a: `Salut! 👋 Sunt asistentul virtual FeelVoyage. Te ajut cu destinații, prețuri, rezervări și informații de călătorie. Cu ce începem?` },
          en: { t: '👋 Hello', k: ['hello', 'hi', 'hey', 'good morning', 'good evening', 'good afternoon'], a: `Hello! 👋 I'm the FeelVoyage virtual assistant. I can help with destinations, prices, bookings and travel information. Where shall we start?` },
          it: { t: '👋 Ciao', k: ['ciao', 'salve', 'buongiorno', 'buonasera', 'buon pomeriggio'], a: `Ciao! 👋 Sono l'assistente virtuale di FeelVoyage. Ti aiuto con destinazioni, prezzi, prenotazioni e informazioni di viaggio. Da dove iniziamo?` } },

        { id: 'thanks', short: true, local: true, next: ['destinations-list', 'contact'],
          ro: { t: '🙏 Mulțumesc', k: ['multumesc', 'multumim', 'mersi', 'mersi frumos', 'multam'], a: `Cu plăcere! 😊 Dacă mai ai întrebări despre destinații, prețuri sau rezervări, sunt aici.` },
          en: { t: '🙏 Thanks', k: ['thanks', 'thank you', 'thx', 'cheers', 'many thanks'], a: `You're welcome! 😊 If you have more questions about destinations, prices or bookings, I'm here.` },
          it: { t: '🙏 Grazie', k: ['grazie', 'grazie mille', 'ti ringrazio', 'vi ringrazio'], a: `Prego! 😊 Se hai altre domande su destinazioni, prezzi o prenotazioni, sono qui.` } },

        { id: 'bye', short: true, local: true, next: ['contact'],
          ro: { t: '👋 La revedere', k: ['la revedere', 'pa', 'o zi buna', 'numai bine', 'pe curand', 'va salut'], a: `La revedere și călătorii plăcute! ✈️ Ne găsești oricând la **{phone}** sau pe **{email}**.` },
          en: { t: '👋 Goodbye', k: ['bye', 'goodbye', 'see you', 'see you later', 'have a nice day'], a: `Goodbye and happy travels! ✈️ You can always reach us at **{phone}** or **{email}**.` },
          it: { t: '👋 Arrivederci', k: ['arrivederci', 'a presto', 'buona giornata', 'buon viaggio'], a: `Arrivederci e buon viaggio! ✈️ Ci trovi sempre al **{phone}** o su **{email}**.` } },

        { id: 'ok', short: true, local: true, next: ['destinations-list', 'price-ranges'],
          ro: { t: '👍 Ok', k: ['ok', 'bine', 'perfect', 'super', 'excelent', 'de acord', 'am inteles', 'inteles'], a: `Perfect! 😊 Dacă mai ai întrebări despre destinații, prețuri sau rezervări, spune-mi.` },
          en: { t: '👍 Ok', k: ['ok', 'okay', 'great', 'perfect', 'got it', 'understood', 'fine', 'sounds good'], a: `Great! 😊 If you have more questions about destinations, prices or bookings, just ask.` },
          it: { t: '👍 Ok', k: ['va bene', 'perfetto', 'ottimo', 'capito', 'd accordo', 'benissimo'], a: `Perfetto! 😊 Se hai altre domande su destinazioni, prezzi o prenotazioni, chiedi pure.` } },

        { id: 'human', local: true, next: ['request-offer', 'hours', 'contact'],
          ro: { t: '🧑‍💼 Vorbesc cu un consultant', k: ['consultant', 'om real', 'operator', 'agent uman', 'vorbesc cu cineva', 'persoana reala', 'ma sunati', 'sunati ma', 'suna ma', 'vreau sa vorbesc cu'], a: `Te poate ajuta un consultant FeelVoyage:\n• **Telefon / WhatsApp:** {phone}\n• **E-mail:** {email}\n• **Program:** {hours}\nDacă preferi, trimite formularul de ofertă din secțiunea **Contact** și un consultant te contactează.` },
          en: { t: '🧑‍💼 Talk to a consultant', k: ['consultant', 'human', 'real person', 'operator', 'speak to someone', 'talk to someone', 'call me', 'live agent'], a: `A FeelVoyage consultant can help you:\n• **Phone / WhatsApp:** {phone}\n• **E-mail:** {email}\n• **Hours:** {hours}\nOr send the offer form in the **Contact** section and a consultant will get back to you.` },
          it: { t: '🧑‍💼 Parlare con un consulente', k: ['consulente', 'operatore', 'persona reale', 'parlare con qualcuno', 'richiamami', 'chiamatemi', 'parlare con un operatore'], a: `Un consulente FeelVoyage può aiutarti:\n• **Telefono / WhatsApp:** {phone}\n• **E-mail:** {email}\n• **Orari:** {hours}\nOppure invia il modulo di richiesta nella sezione **Contatti** e un consulente ti ricontatterà.` } },

        { id: 'who', next: ['can-do', 'about'],
          ro: { t: '🤖 Cine ești?', k: ['cine esti', 'ce esti', 'esti robot', 'esti om', 'esti un bot', 'esti ai', 'cum te cheama', 'te cheama'], a: `Sunt asistentul virtual FeelVoyage. Când asistentul AI este disponibil, răspund cu ajutorul unui model AI; altfel folosesc răspunsuri pregătite de echipă. Te ajut cu destinații, prețuri și rezervări, iar oferta finală o confirmă un consultant.` },
          en: { t: '🤖 Who are you?', k: ['who are you', 'what are you', 'are you a bot', 'are you a robot', 'are you ai', 'are you human', 'your name', 'what is your name'], a: `I'm the FeelVoyage virtual assistant. When the AI assistant is available I answer with an AI model; otherwise I use answers prepared by the team. I can help with destinations, prices and bookings, and a consultant confirms the final offer.` },
          it: { t: '🤖 Chi sei?', k: ['chi sei', 'cosa sei', 'sei un bot', 'sei un robot', 'sei umano', 'come ti chiami', 'sei una ia'], a: `Sono l'assistente virtuale di FeelVoyage. Quando l'assistente IA è disponibile rispondo con un modello IA; altrimenti uso risposte preparate dal team. Ti aiuto con destinazioni, prezzi e prenotazioni, e l'offerta finale la conferma un consulente.` } },

        { id: 'can-do', next: ['destinations-list', 'price-ranges', 'how-to-book', 'contact'],
          ro: { t: '❓ Cu ce mă poți ajuta?', k: ['ce poti face', 'cu ce ma ajuti', 'cu ce ma poti ajuta', 'ajutor', 'help', 'ce stii', 'ce faci', 'poti sa ma ajuti'], a: `Te pot ajuta cu:\n• **Destinații și pachete** ({count} în catalog) și recomandări după buget\n• **Prețuri** (per persoană, copii, sezon, servicii extra)\n• **Rezervări**, plată și contact\n• **Informații de călătorie**: acte, monedă, vreme, bagaje\nÎntreabă-mă, de exemplu: „Cât costă Roma?” sau „Ce pot face cu 800 €?”.` },
          en: { t: '❓ What can you do?', k: ['what can you do', 'how can you help', 'help', 'what do you do', 'can you help', 'can you help me'], a: `I can help with:\n• **Destinations and packages** ({count} in the catalogue) and recommendations by budget\n• **Prices** (per person, children, season, extras)\n• **Bookings**, payment and contact\n• **Travel info**: documents, currency, weather, luggage\nTry asking: "How much is Rome?" or "What can I do with 800 €?".` },
          it: { t: '❓ Come puoi aiutarmi?', k: ['cosa puoi fare', 'come puoi aiutarmi', 'aiuto', 'cosa fai', 'puoi aiutarmi', 'mi puoi aiutare'], a: `Posso aiutarti con:\n• **Destinazioni e pacchetti** ({count} nel catalogo) e consigli in base al budget\n• **Prezzi** (a persona, bambini, stagione, servizi extra)\n• **Prenotazioni**, pagamento e contatti\n• **Info di viaggio**: documenti, valuta, meteo, bagagli\nProva a chiedere: "Quanto costa Roma?" o "Cosa posso fare con 800 €?".` } },

        { id: 'languages', next: ['language-site', 'can-do'],
          ro: { t: '🌐 Limbi vorbite', k: ['vorbesti engleza', 'vorbiti engleza', 'vorbiti italiana', 'vorbesti italiana', 'ce limbi', 'limbi straine', 'raspunzi in engleza', 'in engleza te rog'], a: `Poți scrie în **română, engleză sau italiană**; îți răspund în aceeași limbă. Poți schimba și limba site-ului din butonul **RO / EN / IT** din antet sau din meniu.` },
          en: { t: '🌐 Languages', k: ['do you speak', 'which languages', 'what languages', 'speak english', 'speak romanian', 'speak italian', 'answer in english'], a: `You can write in **Romanian, English or Italian** and I'll reply in the same language. You can also switch the site language with the **RO / EN / IT** button in the header or menu.` },
          it: { t: '🌐 Lingue', k: ['parli italiano', 'parli inglese', 'quali lingue', 'che lingue', 'parlate romeno', 'rispondi in italiano'], a: `Puoi scrivere in **rumeno, inglese o italiano** e ti rispondo nella stessa lingua. Puoi anche cambiare la lingua del sito con il pulsante **RO / EN / IT** nell'intestazione o nel menu.` } },

        { id: 'joke', next: ['destinations-list', 'price-ranges'],
          ro: { t: '😄 O glumă', k: ['banc', 'gluma', 'spune o gluma', 'ceva amuzant', 'distreaza ma', 'spune un banc'], a: `Nu mă pricep la glume 😄, dar mă pricep la vacanțe! Vrei să-ți propun o destinație după buget sau după tipul de vacanță (plajă, munte, city break)?` },
          en: { t: '😄 A joke', k: ['joke', 'tell me a joke', 'something funny', 'make me laugh', 'be funny'], a: `Jokes aren't my strong suit 😄, but holidays are! Want me to suggest a destination by budget or by type of trip (beach, mountains, city break)?` },
          it: { t: '😄 Una battuta', k: ['barzelletta', 'battuta', 'raccontami una barzelletta', 'fammi ridere', 'dimmi una battuta'], a: `Non sono bravo con le battute 😄, ma con le vacanze sì! Vuoi che ti proponga una destinazione in base al budget o al tipo di viaggio (mare, montagna, city break)?` } },

        { id: 'off-topic', next: ['destinations-list', 'price-ranges', 'contact'],
          ro: { t: 'În afara domeniului', k: ['python', 'javascript', 'scrie cod', 'cod sursa', 'programare', 'bitcoin', 'cripto*', 'ethereum', 'politica', 'alegeri', 'presedinte', 'retete', 'reteta', 'tema de casa', 'teme scolare', 'rezolva tema', 'ecuatie', 'horoscop', 'poezie'], a: `Te pot ajuta doar cu întrebări despre agenția FeelVoyage, site-ul nostru și destinațiile de vacanță. 🌍 Întreabă-mă, de exemplu, despre pachetele disponibile, prețuri sau ce poți vizita într-o destinație!` },
          en: { t: 'Off-topic', k: ['python', 'javascript', 'write code', 'source code', 'programming', 'bitcoin', 'crypto*', 'ethereum', 'politics', 'election', 'president', 'recipe', 'homework', 'equation', 'horoscope', 'poem'], a: `I can only help with questions about the FeelVoyage agency, our website and holiday destinations. 🌍 Ask me, for example, about the available packages, prices or what to see in a destination!` },
          it: { t: 'Fuori tema', k: ['python', 'javascript', 'scrivi codice', 'codice sorgente', 'programmazione', 'bitcoin', 'cripto*', 'ethereum', 'politica', 'elezioni', 'presidente', 'ricetta', 'compiti', 'equazione', 'oroscopo', 'poesia'], a: `Posso aiutarti solo con domande sull'agenzia FeelVoyage, sul nostro sito e sulle destinazioni di vacanza. 🌍 Chiedimi, ad esempio, dei pacchetti disponibili, dei prezzi o di cosa visitare in una destinazione!` } },

        { id: 'complaint', next: ['human', 'hours'],
          ro: { t: '⚠️ Am o problemă', k: ['reclamatie', 'nemultumit', 'nemultumire', 'problema cu', 'sesizare', 'plangere', 'nu sunt multumit', 'am o problema'], a: `Ne pare rău pentru neplăcere! Ca să rezolvăm cât mai repede, scrie-ne pe **{email}** sau sună la **{phone}** ({hours}) și spune-ne pe scurt ce s-a întâmplat. Un consultant preia cazul tău.` },
          en: { t: '⚠️ I have a problem', k: ['complaint', 'unhappy', 'dissatisfied', 'problem with my', 'i have a problem', 'not happy', 'issue with my'], a: `We're sorry for the inconvenience! To solve it quickly, write to **{email}** or call **{phone}** ({hours}) and tell us briefly what happened. A consultant will take your case.` },
          it: { t: '⚠️ Ho un problema', k: ['reclamo', 'insoddisfatto', 'problema con', 'non sono soddisfatto', 'ho un problema', 'lamentela'], a: `Ci dispiace per il disagio! Per risolvere in fretta, scrivi a **{email}** o chiama il **{phone}** ({hours}) e raccontaci brevemente cosa è successo. Un consulente si occuperà del tuo caso.` } },

        /* ==================================================== AGENȚIE ȘI CONTACT ==================================================== */
        { id: 'contact', next: ['hours', 'address', 'request-offer'],
          ro: { t: '📞 Contact', k: ['contact', 'date de contact', 'cum va contactez', 'contactati', 'contacta'], a: `Ne poți contacta astfel:\n• **Telefon / WhatsApp:** {phone}\n• **E-mail:** {email}\n• **Sediu:** {address}\n• **Program:** {hours}\n• **Facebook:** [FeelVoyage](${FB})` },
          en: { t: '📞 Contact', k: ['contact', 'contact details', 'how to contact', 'get in touch', 'reach you', 'contact you'], a: `You can reach us here:\n• **Phone / WhatsApp:** {phone}\n• **E-mail:** {email}\n• **Office:** {address}\n• **Hours:** {hours}\n• **Facebook:** [FeelVoyage](${FB})` },
          it: { t: '📞 Contatti', k: ['contatti', 'contattare', 'come contattarvi', 'recapiti', 'contattarvi', 'metterci in contatto'], a: `Puoi contattarci così:\n• **Telefono / WhatsApp:** {phone}\n• **E-mail:** {email}\n• **Sede:** {address}\n• **Orari:** {hours}\n• **Facebook:** [FeelVoyage](${FB})` } },

        { id: 'phone', next: ['hours', 'whatsapp'],
          ro: { t: '☎️ Telefon', k: ['telefon', 'numar de telefon', 'numarul', 'suna', 'sunati', 'apel', 'va pot suna', 'nr de tel'], a: `Ne poți suna la **{phone}** (este și număr de WhatsApp). Program: {hours}.` },
          en: { t: '☎️ Phone', k: ['phone', 'phone number', 'call', 'telephone', 'call you', 'can i call'], a: `You can call us at **{phone}** (it's also our WhatsApp number). Hours: {hours}.` },
          it: { t: '☎️ Telefono', k: ['telefono', 'numero di telefono', 'chiamare', 'chiamata', 'posso chiamare'], a: `Puoi chiamarci al **{phone}** (è anche il nostro numero WhatsApp). Orari: {hours}.` } },

        { id: 'email', next: ['response-time', 'phone'],
          ro: { t: '✉️ E-mail', k: ['email', 'e mail', 'mail', 'adresa de email', 'va scriu', 'pe mail'], a: `Ne poți scrie la **{email}**. Pentru o ofertă personalizată, spune-ne destinația, perioada și numărul de persoane; revenim în cel mult 24 de ore.` },
          en: { t: '✉️ E-mail', k: ['email', 'e mail', 'mail address', 'write to you', 'email address', 'by email'], a: `You can write to us at **{email}**. For a personalised offer, tell us the destination, dates and number of travellers; we reply within 24 hours at most.` },
          it: { t: '✉️ E-mail', k: ['email', 'e mail', 'indirizzo email', 'scrivervi', 'posta elettronica', 'via email'], a: `Puoi scriverci a **{email}**. Per un'offerta personalizzata indica destinazione, date e numero di viaggiatori; rispondiamo entro 24 ore al massimo.` } },

        { id: 'whatsapp', next: ['consultant', 'phone'],
          ro: { t: '💬 WhatsApp', k: ['whatsapp', 'watsap', 'mesaj pe whatsapp', 'grup whatsapp'], a: `Ne poți scrie pe **WhatsApp** la **{phone}**. În timpul sejurului, consultantul tău dedicat creează și un grup WhatsApp de asistență.` },
          en: { t: '💬 WhatsApp', k: ['whatsapp', 'whats app', 'message on whatsapp', 'whatsapp group'], a: `You can message us on **WhatsApp** at **{phone}**. During your trip your dedicated consultant also sets up a WhatsApp support group.` },
          it: { t: '💬 WhatsApp', k: ['whatsapp', 'messaggio whatsapp', 'gruppo whatsapp'], a: `Puoi scriverci su **WhatsApp** al **{phone}**. Durante il viaggio il tuo consulente dedicato crea anche un gruppo WhatsApp di assistenza.` } },

        { id: 'address', next: ['hours', 'phone'],
          ro: { t: '📍 Adresa', k: ['adresa', 'unde va aflati', 'unde sunteti', 'sediu', 'sediul', 'unde e agentia', 'locatie agentie', 'harta', 'tg jiu', 'targu jiu', 'gorj'], a: `Sediul agenției FeelVoyage este pe **{address}**, România. 📍 Program: {hours}.` },
          en: { t: '📍 Address', k: ['address', 'where are you', 'where is the office', 'office location', 'headquarters', 'map', 'where is your office'], a: `The FeelVoyage office is at **{address}**, Romania. 📍 Hours: {hours}.` },
          it: { t: '📍 Indirizzo', k: ['indirizzo', 'dove siete', 'dove si trova', 'sede', 'ufficio', 'mappa', 'dov e l ufficio'], a: `La sede di FeelVoyage è in **{address}**, Romania. 📍 Orari: {hours}.` } },

        { id: 'hours', next: ['contact', 'address'],
          ro: { t: '🕘 Program', k: ['program', 'programul', 'programul vostru', 'orar', 'ore de functionare', 'pana la ce ora', 'deschis', 'inchis', 'duminica', 'sambata', 'cand sunteti deschisi', 'programul in weekend'], a: `Program: **{hours}**. Duminica nu avem program afișat la sediu; ne poți scrie oricând pe e-mail sau WhatsApp și îți răspundem în următoarea zi lucrătoare.` },
          en: { t: '🕘 Opening hours', k: ['opening hours', 'hours', 'open', 'closed', 'sunday', 'saturday', 'what time do you open', 'weekend hours'], a: `Hours: **{hours}**. We have no posted office hours on Sunday; you can write to us any time by e-mail or WhatsApp and we'll reply on the next working day.` },
          it: { t: '🕘 Orari', k: ['orari', 'orario', 'aperto', 'chiuso', 'domenica', 'sabato', 'quando siete aperti', 'orari nel weekend'], a: `Orari: **{hours}**. La domenica non c'è un orario di apertura in sede; puoi scriverci in qualsiasi momento via e-mail o WhatsApp e rispondiamo il giorno lavorativo successivo.` } },

        { id: 'facebook', next: ['contact', 'discounts'],
          ro: { t: '🔵 Facebook', k: ['facebook', 'pagina de facebook', 'fb', 'social media', 'instagram'], a: `Ne poți urmări pe pagina noastră de Facebook pentru oferte, promoții și noutăți: [FeelVoyage Facebook](${FB}) 🔵` },
          en: { t: '🔵 Facebook', k: ['facebook', 'facebook page', 'fb', 'social media', 'instagram'], a: `Follow our Facebook page for offers, promotions and news: [FeelVoyage Facebook](${FB}) 🔵` },
          it: { t: '🔵 Facebook', k: ['facebook', 'pagina facebook', 'fb', 'social media', 'instagram'], a: `Seguici sulla nostra pagina Facebook per offerte, promozioni e novità: [FeelVoyage Facebook](${FB}) 🔵` } },

        { id: 'about', next: ['why-us', 'destinations-list', 'contact'],
          ro: { t: 'ℹ️ Despre noi', k: ['despre voi', 'despre agentie', 'cine sunteti', 'povestea', 'istoria', 'despre feelvoyage', 'ce este feelvoyage', 'prezentare'], a: `FeelVoyage este o agenție de turism din **Târgu Jiu (Gorj)**, cu **{count} de destinații**: de la litoralul românesc până în China și Coreea de Sud. Construim vacanțe în jurul bugetului și al ritmului tău, cu prețuri transparente și un consultant dedicat.` },
          en: { t: 'ℹ️ About us', k: ['about you', 'about the agency', 'who are you guys', 'your story', 'what is feelvoyage', 'about feelvoyage', 'tell me about the agency'], a: `FeelVoyage is a travel agency from **Târgu Jiu (Gorj, Romania)** with **{count} destinations**, from the Romanian seaside to China and South Korea. We build holidays around your budget and pace, with transparent prices and a dedicated consultant.` },
          it: { t: 'ℹ️ Chi siamo', k: ['chi siete', 'su di voi', 'la vostra storia', 'cos e feelvoyage', 'sull agenzia', 'parlami dell agenzia'], a: `FeelVoyage è un'agenzia di viaggi di **Târgu Jiu (Gorj, Romania)** con **{count} destinazioni**, dal litorale rumeno fino a Cina e Corea del Sud. Costruiamo vacanze intorno al tuo budget e al tuo ritmo, con prezzi trasparenti e un consulente dedicato.` } },

        { id: 'why-us', next: ['consultant', 'request-offer'],
          ro: { t: '⭐ De ce FeelVoyage?', k: ['de ce voi', 'de ce sa aleg', 'avantaje', 'de ce feelvoyage', 'ce va face diferiti', 'beneficii'], a: `Ce te așteaptă la noi:\n• **Consultanță gratuită** și ofertă personalizată în maximum 24 de ore\n• Prețuri în **EUR și lei**, cu rate fără dobândă pentru anumite pachete\n• **Asigurare** de călătorie și asistență medicală opționale\n• **Consultant dedicat** și grup WhatsApp în timpul sejurului` },
          en: { t: '⭐ Why FeelVoyage?', k: ['why choose', 'why you', 'advantages', 'benefits', 'what makes you different', 'why feelvoyage'], a: `What you get with us:\n• **Free advice** and a personalised offer within 24 hours\n• Prices in **EUR and lei**, with interest-free instalments on some packages\n• Optional travel **insurance** and medical assistance\n• A **dedicated consultant** and a WhatsApp group during your trip` },
          it: { t: '⭐ Perché FeelVoyage?', k: ['perche voi', 'perche scegliere', 'vantaggi', 'cosa vi rende diversi', 'perche feelvoyage'], a: `Cosa trovi da noi:\n• **Consulenza gratuita** e offerta personalizzata entro 24 ore\n• Prezzi in **EUR e lei**, con rate senza interessi su alcuni pacchetti\n• **Assicurazione** di viaggio e assistenza medica opzionali\n• Un **consulente dedicato** e un gruppo WhatsApp durante il viaggio` } },

        { id: 'consultant', next: ['whatsapp', 'request-offer'],
          ro: { t: '🧑‍💼 Consultant dedicat', k: ['consultant dedicat', 'cine ma ajuta', 'cine se ocupa', 'persoana de contact', 'asistenta in vacanta', 'ajutor in vacanta', 'asistenta 24'], a: `Fiecare client are un **consultant dedicat**, de la prima ofertă până la întoarcerea acasă. În timpul sejurului ai și un **grup WhatsApp de asistență**, ca să primești ajutor rapid.` },
          en: { t: '🧑‍💼 Dedicated consultant', k: ['dedicated consultant', 'who will help me', 'contact person', 'help during the trip', 'support during the holiday', 'assistance during the trip'], a: `Every client has a **dedicated consultant**, from the first offer until you're back home. During your stay you also get a **WhatsApp support group** for quick help.` },
          it: { t: '🧑‍💼 Consulente dedicato', k: ['consulente dedicato', 'chi mi aiuta', 'persona di contatto', 'assistenza durante la vacanza', 'aiuto durante il viaggio'], a: `Ogni cliente ha un **consulente dedicato**, dalla prima offerta fino al ritorno a casa. Durante il soggiorno hai anche un **gruppo WhatsApp di assistenza** per un aiuto rapido.` } },

        { id: 'response-time', next: ['request-offer', 'hours'],
          ro: { t: '⏱️ Cât durează răspunsul?', k: ['cat dureaza', 'cand ma contactati', 'cand raspundeti', 'in cat timp', 'timp de raspuns', 'cand primesc oferta', 'in cate ore'], a: `La formularul din secțiunea **Contact**, un consultant răspunde în cel mult **2 ore lucrătoare**. Oferta personalizată o primești în maximum **24 de ore**.` },
          en: { t: '⏱️ How fast do you reply?', k: ['how long', 'when will you reply', 'response time', 'when will you contact', 'how fast', 'when do i get the offer'], a: `For the form in the **Contact** section, a consultant replies within **2 working hours** at most. You get your personalised offer within **24 hours**.` },
          it: { t: '⏱️ Tempi di risposta', k: ['quanto tempo', 'quando rispondete', 'tempi di risposta', 'quando mi contattate', 'quando ricevo l offerta'], a: `Per il modulo nella sezione **Contatti**, un consulente risponde entro **2 ore lavorative** al massimo. L'offerta personalizzata arriva entro **24 ore**.` } },

        { id: 'visit-office', next: ['address', 'hours'],
          ro: { t: '🏢 Vizită la sediu', k: ['pot veni la sediu', 'vizita la sediu', 'programare la sediu', 'pot sa vin', 'intalnire'], a: `Da, ne poți vizita la sediu: **{address}**. Program: {hours}. Pentru o discuție dedicată, sună înainte la **{phone}**.` },
          en: { t: '🏢 Visit the office', k: ['visit the office', 'can i come', 'appointment', 'meet in person', 'come to the office'], a: `Yes, you're welcome at our office: **{address}**. Hours: {hours}. For a dedicated chat, call **{phone}** first.` },
          it: { t: '🏢 Visita in sede', k: ['posso venire', 'visita in ufficio', 'appuntamento', 'incontrarvi', 'venire in sede'], a: `Sì, puoi venire nella nostra sede: **{address}**. Orari: {hours}. Per un colloquio dedicato, chiama prima il **{phone}**.` } },

        { id: 'reviews', next: ['facebook', 'about'],
          ro: { t: '⭐ Recenzii', k: ['recenzii', 'parerile clientilor', 'testimoniale', 'referinte', 'ce spun clientii'], a: `Momentan nu afișăm recenzii pe site. Noutăți și oferte găsești pe [pagina noastră de Facebook](${FB}); pentru referințe, întreabă un consultant la **{phone}**.` },
          en: { t: '⭐ Reviews', k: ['reviews', 'testimonials', 'what do clients say', 'references', 'ratings'], a: `We don't show reviews on the site at the moment. You'll find news and offers on [our Facebook page](${FB}); for references, ask a consultant at **{phone}**.` },
          it: { t: '⭐ Recensioni', k: ['recensioni', 'testimonianze', 'cosa dicono i clienti', 'referenze'], a: `Al momento non mostriamo recensioni sul sito. Novità e offerte le trovi sulla [nostra pagina Facebook](${FB}); per referenze, chiedi a un consulente al **{phone}**.` } },

        /* ==================================================== REZERVĂRI ==================================================== */
        { id: 'how-to-book', next: ['dates-how', 'travelers-how', 'after-request'],
          ro: { t: '🎫 Cum rezerv?', k: ['cum rezerv', 'cum fac o rezervare', 'vreau sa rezerv', 'rezervare', 'rezerva', 'cum comand', 'cum pot rezerva', 'pasii rezervarii'], a: `Rezervarea pe site, în pași:\n1. Alege un pachet și apasă **Detalii Pachet**.\n2. Alege adulții/copiii, **datele** de plecare și întoarcere și serviciile extra: vezi estimarea pe loc.\n3. Completează datele și apasă **Trimite Solicitarea de Rezervare**.\nUn agent te contactează pentru confirmare. Poți rezerva și prin telefon (**{phone}**) sau la sediu.` },
          en: { t: '🎫 How do I book?', k: ['how to book', 'how do i book', 'i want to book', 'booking', 'reserve', 'make a reservation', 'booking steps'], a: `Booking on the site, step by step:\n1. Pick a package and press **Package Details**.\n2. Choose adults/children, **departure and return dates** and extras: you see the estimate instantly.\n3. Fill in your details and press **Send Booking Request**.\nAn agent contacts you to confirm. You can also book by phone (**{phone}**) or at the office.` },
          it: { t: '🎫 Come prenoto?', k: ['come prenotare', 'come prenoto', 'voglio prenotare', 'prenotazione', 'prenotare', 'passaggi della prenotazione'], a: `Prenotare sul sito, passo dopo passo:\n1. Scegli un pacchetto e premi **Dettagli Pacchetto**.\n2. Scegli adulti/bambini, **date** di partenza e ritorno e servizi extra: vedi subito la stima.\n3. Compila i tuoi dati e premi **Invia richiesta di prenotazione**.\nUn agente ti contatta per la conferma. Puoi prenotare anche per telefono (**{phone}**) o in sede.` } },

        { id: 'request-offer', next: ['response-time', 'contact'],
          ro: { t: '📝 Cerere de ofertă', k: ['cerere de oferta', 'solicitare oferta', 'oferta personalizata', 'formular', 'vreau o oferta', 'cer oferta', 'formularul de contact'], a: `Pentru o **ofertă personalizată**, completează formularul **„Trimite o Solicitare de Ofertă”** din secțiunea **Contact** (nume, telefon, e-mail, destinația dorită, detalii). Un consultant te contactează în cel mult 2 ore lucrătoare.` },
          en: { t: '📝 Request an offer', k: ['request an offer', 'quote request', 'personalised offer', 'contact form', 'get a quote', 'custom offer', 'offer form'], a: `For a **personalised offer**, fill in the **"Send an Offer Request"** form in the **Contact** section (name, phone, e-mail, desired destination, details). A consultant contacts you within 2 working hours at most.` },
          it: { t: '📝 Richiesta di offerta', k: ['richiesta di offerta', 'preventivo', 'offerta personalizzata', 'modulo di contatto', 'voglio un preventivo', 'modulo offerta'], a: `Per un'**offerta personalizzata**, compila il modulo **"Invia una richiesta di offerta"** nella sezione **Contatti** (nome, telefono, e-mail, destinazione desiderata, dettagli). Un consulente ti contatta entro 2 ore lavorative al massimo.` } },

        { id: 'book-online', next: ['how-to-book', 'pay-online'],
          ro: { t: '💻 Rezervare online', k: ['rezerv online', 'pot rezerva pe site', 'rezervare online', 'rezerv de pe telefon', 'pot rezerva de pe site', 'rezerva online', 'pot rezerva online', 'rezerva de pe telefon'], a: `Da, poți trimite **solicitarea de rezervare** direct de pe site sau de pe telefon, din fereastra pachetului. Nu plătești pe site: un agent te contactează, confirmă disponibilitatea și stabilește împreună cu tine plata.` },
          en: { t: '💻 Book online', k: ['book online', 'book on the website', 'online booking', 'reserve on the site', 'book from my phone'], a: `Yes, you can send a **booking request** straight from the site or your phone, from the package window. You don't pay on the site: an agent contacts you, confirms availability and agrees the payment with you.` },
          it: { t: '💻 Prenotare online', k: ['prenotare online', 'prenotare sul sito', 'prenotazione online', 'prenotare dal telefono'], a: `Sì, puoi inviare la **richiesta di prenotazione** direttamente dal sito o dal telefono, dalla finestra del pacchetto. Non paghi sul sito: un agente ti contatta, conferma la disponibilità e concorda con te il pagamento.` } },

        { id: 'no-account', next: ['create-account', 'account-benefits'],
          ro: { t: '👤 Trebuie cont?', k: ['trebuie cont', 'trebuie sa am cont', 'sa am cont', 'fara cont', 'obligatoriu cont', 'am nevoie de cont', 'pot rezerva fara cont'], a: `Nu, **contul este opțional**: poți trimite rezervări și cereri de ofertă și fără cont. Cu cont, datele tale se completează automat în formulare.` },
          en: { t: '👤 Do I need an account?', k: ['need an account', 'without an account', 'account required', 'do i need to register', 'account mandatory'], a: `No, the **account is optional**: you can send bookings and offer requests without one. With an account your details are filled in automatically in the forms.` },
          it: { t: '👤 Serve un account?', k: ['serve un account', 'senza account', 'account obbligatorio', 'devo registrarmi', 'account necessario'], a: `No, l'**account è opzionale**: puoi inviare prenotazioni e richieste di offerta anche senza. Con l'account i tuoi dati si compilano automaticamente nei moduli.` } },

        { id: 'create-account', next: ['login-help', 'account-benefits'],
          ro: { t: '✍️ Creare cont', k: ['creez cont', 'creare cont', 'inregistrare', 'cum ma inregistrez', 'cont nou', 'sign up', 'fac cont'], a: `Apasă butonul **Contul Meu** din antet (iconița de utilizator) → **Înregistrare**. Completezi numele, telefonul (opțional), e-mailul și o parolă de minim 6 caractere. Contul funcționează pe orice dispozitiv, cu același e-mail și aceeași parolă.` },
          en: { t: '✍️ Create an account', k: ['create account', 'register', 'sign up', 'new account', 'how to register', 'make an account'], a: `Press the **My Account** button in the header (user icon) → **Register**. Fill in your name, phone (optional), e-mail and a password of at least 6 characters. The account works on any device with the same e-mail and password.` },
          it: { t: '✍️ Creare account', k: ['creare account', 'registrazione', 'registrarmi', 'nuovo account', 'come mi registro', 'creare un account'], a: `Premi il pulsante **Il Mio Account** nell'intestazione (icona utente) → **Registrati**. Inserisci nome, telefono (opzionale), e-mail e una password di almeno 6 caratteri. L'account funziona su qualsiasi dispositivo con la stessa e-mail e password.` } },

        { id: 'login-help', next: ['create-account', 'tech-issue'],
          ro: { t: '🔑 Autentificare', k: ['autentificare', 'login', 'loghez', 'nu pot intra', 'parola uitata', 'am uitat parola', 'resetare parola', 'schimb parola', 'deconectare', 'logout'], a: `Autentificare: butonul **Contul Meu** din antet → e-mail și parolă. Dacă ai uitat parola, apasă **„Ai uitat parola?”** (scrie întâi e-mailul) și primești un link de resetare. Pentru deconectare, deschide profilul și apasă **Deconectare**.` },
          en: { t: '🔑 Log in', k: ['log in', 'login', 'sign in', 'forgot password', 'reset password', 'cannot log in', 'log out', 'logout'], a: `Log in: **My Account** button in the header → e-mail and password. If you forgot the password, press **"Forgot your password?"** (type your e-mail first) and you'll get a reset link. To log out, open your profile and press **Log out**.` },
          it: { t: '🔑 Accedere', k: ['accedere', 'login', 'password dimenticata', 'reimpostare password', 'non riesco ad accedere', 'esci', 'logout', 'ho dimenticato la password'], a: `Accesso: pulsante **Il Mio Account** nell'intestazione → e-mail e password. Se hai dimenticato la password, premi **"Password dimenticata?"** (scrivi prima l'e-mail) e riceverai un link di reimpostazione. Per uscire, apri il profilo e premi **Esci**.` } },

        { id: 'account-benefits', next: ['create-account', 'no-account'],
          ro: { t: '🎁 Avantajele contului', k: ['avantaje cont', 'de ce sa am cont', 'ce ofera contul', 'beneficii cont', 'ce pot face cu contul', 'avantaje are contul', 'avantajele contului'], a: `Cu un cont: numele, telefonul și e-mailul se **completează automat** la rezervări, ai același cont pe **telefon și calculator**, iar rezervările se trimit mai repede. Contul rămâne opțional.` },
          en: { t: '🎁 Account benefits', k: ['account benefits', 'why create an account', 'what does the account do', 'benefits of registering'], a: `With an account: your name, phone and e-mail are **filled in automatically** when booking, you have the same account on **phone and computer**, and requests go out faster. The account stays optional.` },
          it: { t: '🎁 Vantaggi dell\'account', k: ['vantaggi account', 'perche creare un account', 'cosa offre l account', 'vantaggi della registrazione'], a: `Con un account: nome, telefono ed e-mail si **compilano automaticamente** nelle prenotazioni, hai lo stesso account su **telefono e computer** e le richieste partono più in fretta. L'account resta opzionale.` } },

        { id: 'cancel', next: ['change-booking', 'human'],
          ro: { t: '❌ Anulare rezervare', k: ['anulare', 'anulez', 'pot anula', 'renunt la rezervare', 'rambursare', 'banii inapoi', 'retur bani', 'penalizare'], a: `Condițiile de anulare și eventualele penalizări depind de pachet și se stabilesc la confirmarea ofertei. Pentru cazul tău, sună la **{phone}** sau scrie la **{email}** cât mai repede.` },
          en: { t: '❌ Cancel a booking', k: ['cancel', 'cancellation', 'refund', 'money back', 'penalty', 'cancel my booking'], a: `Cancellation terms and any penalties depend on the package and are set when the offer is confirmed. For your case, call **{phone}** or write to **{email}** as soon as possible.` },
          it: { t: '❌ Annullare la prenotazione', k: ['annullare', 'annullo', 'rimborso', 'penale', 'disdire', 'voglio annullare'], a: `Le condizioni di annullamento ed eventuali penali dipendono dal pacchetto e si stabiliscono alla conferma dell'offerta. Per il tuo caso, chiama il **{phone}** o scrivi a **{email}** il prima possibile.` } },

        { id: 'change-booking', next: ['cancel', 'human'],
          ro: { t: '🔄 Modificare rezervare', k: ['modificare rezervare', 'schimb data', 'schimb rezervarea', 'modific', 'mut data', 'amanare', 'amanare calatorie'], a: `Modificările (date, persoane, servicii) se fac împreună cu consultantul tău, în funcție de disponibilitate și de condițiile pachetului. Sună la **{phone}** sau scrie la **{email}**.` },
          en: { t: '🔄 Change a booking', k: ['change my booking', 'modify booking', 'change the date', 'reschedule', 'postpone', 'amend my booking'], a: `Changes (dates, people, services) are made with your consultant, depending on availability and the package terms. Call **{phone}** or write to **{email}**.` },
          it: { t: '🔄 Modificare la prenotazione', k: ['modificare prenotazione', 'cambiare data', 'spostare', 'rinviare', 'modifica prenotazione', 'cambiare la prenotazione'], a: `Le modifiche (date, persone, servizi) si fanno con il tuo consulente, in base alla disponibilità e alle condizioni del pacchetto. Chiama il **{phone}** o scrivi a **{email}**.` } },

        { id: 'group', next: ['custom-trip', 'request-offer'],
          ro: { t: '👥 Grupuri', k: ['grup', 'grupuri', 'nunta', 'team building', 'excursie de grup', 'rezervare de grup', 'firma', 'companie', 'scoala', 'clasa'], a: `Da, organizăm **rezervări de grup** (nuntă, team building, excursii de firmă sau de școală). Trimite formularul de ofertă cu destinația, perioada și numărul de persoane, sau sună la **{phone}**.` },
          en: { t: '👥 Groups', k: ['group', 'groups', 'wedding', 'team building', 'company trip', 'school trip', 'large group'], a: `Yes, we arrange **group bookings** (weddings, team building, company or school trips). Send the offer form with the destination, dates and number of people, or call **{phone}**.` },
          it: { t: '👥 Gruppi', k: ['gruppo', 'gruppi', 'matrimonio', 'team building', 'viaggio aziendale', 'gita scolastica', 'prenotazione di gruppo'], a: `Sì, organizziamo **prenotazioni di gruppo** (matrimoni, team building, viaggi aziendali o scolastici). Invia il modulo con destinazione, date e numero di persone, oppure chiama il **{phone}**.` } },

        { id: 'custom-trip', next: ['request-offer', 'destinations-list'],
          ro: { t: '🧭 Vacanță personalizată', k: ['itinerariu personalizat', 'pachet personalizat', 'vacanta la comanda', 'circuit personalizat', 'nu gasesc destinatia mea', 'destinatie care nu e pe site', 'la comanda'], a: `Nu vindem doar pachete „de pe raft”: construim **itinerarii personalizate** în jurul bugetului și al pasiunilor tale. Dacă destinația ta nu apare în catalog, spune-ne la **{email}** sau prin formularul din Contact și pregătim o ofertă.` },
          en: { t: '🧭 Custom trip', k: ['custom trip', 'tailor made', 'personalised itinerary', 'custom package', 'destination not listed', 'not on your list', 'bespoke'], a: `We don't only sell off-the-shelf packages: we build **personalised itineraries** around your budget and interests. If your destination isn't in the catalogue, tell us at **{email}** or via the Contact form and we'll prepare an offer.` },
          it: { t: '🧭 Viaggio su misura', k: ['viaggio su misura', 'itinerario personalizzato', 'pacchetto personalizzato', 'destinazione non in elenco', 'non e nella vostra lista'], a: `Non vendiamo solo pacchetti già pronti: costruiamo **itinerari personalizzati** intorno al tuo budget e ai tuoi interessi. Se la tua destinazione non è nel catalogo, scrivici a **{email}** o tramite il modulo Contatti e prepariamo un'offerta.` } },

        { id: 'dates-how', next: ['nights-flex', 'travelers-how'],
          ro: { t: '📅 Cum aleg datele?', k: ['cum aleg datele', 'calendar', 'data plecarii', 'data intoarcerii', 'de pe cand pana cand', 'perioada', 'cand pot pleca', 'alege data'], a: `În fereastra pachetului apasă **Plecare** și alege ziua din calendar (prima zi disponibilă este **mâine**). **Întoarcerea** se completează cu durata standard, iar la pachetele flexibile poți alege altă zi. Circuitele ghidate au durată fixă. Datele se afișează zz/ll/aaaa.` },
          en: { t: '📅 How do I pick dates?', k: ['choose dates', 'calendar', 'departure date', 'return date', 'from when to when', 'pick dates', 'select dates'], a: `In the package window press **Departure** and pick the day in the calendar (the first available day is **tomorrow**). The **Return** date is filled with the standard length, and on flexible packages you can pick another day. Guided tours have a fixed length. Dates show as dd/mm/yyyy.` },
          it: { t: '📅 Come scelgo le date?', k: ['scegliere le date', 'calendario', 'data di partenza', 'data di ritorno', 'periodo', 'da quando a quando', 'selezionare le date'], a: `Nella finestra del pacchetto premi **Partenza** e scegli il giorno nel calendario (il primo giorno disponibile è **domani**). Il **Ritorno** si compila con la durata standard e nei pacchetti flessibili puoi scegliere un altro giorno. I tour guidati hanno durata fissa. Le date sono mostrate gg/mm/aaaa.` } },

        { id: 'travelers-how', next: ['kids-price', 'single'],
          ro: { t: '🧍 Adulți și copii', k: ['cati calatori', 'adulti si copii', 'cum adaug copii', 'numar de persoane', 'pentru cate persoane', 'cate persoane', 'adauga persoane'], a: `În fereastra pachetului, la **Număr Călători**, folosești butoanele **− / +** pentru adulți, copii de 0–4 ani și copii de 5–12 ani. Prețul total și cel pe persoană se actualizează pe loc.` },
          en: { t: '🧍 Adults and children', k: ['how many travellers', 'adults and children', 'add children', 'number of people', 'how many people', 'add people'], a: `In the package window, under **Number of Travellers**, use the **− / +** buttons for adults, children aged 0–4 and children aged 5–12. The total and per-person price update instantly.` },
          it: { t: '🧍 Adulti e bambini', k: ['quanti viaggiatori', 'adulti e bambini', 'aggiungere bambini', 'numero di persone', 'aggiungere persone'], a: `Nella finestra del pacchetto, sotto **Numero di viaggiatori**, usa i pulsanti **− / +** per adulti, bambini 0–4 anni e bambini 5–12 anni. Il prezzo totale e quello a persona si aggiornano subito.` } },

        { id: 'after-request', next: ['response-time', 'human'],
          ro: { t: '📨 Ce urmează după trimitere?', k: ['ce urmeaza dupa', 'dupa ce trimit', 'ce se intampla dupa', 'am trimis solicitarea', 'am trimis formularul', 'nu m a contactat nimeni', 'nu am primit raspuns'], a: `După ce trimiți solicitarea, un agent FeelVoyage te contactează (la formularul de contact, în cel mult 2 ore lucrătoare). Dacă nu ai primit răspuns, sună la **{phone}** sau scrie la **{email}**.` },
          en: { t: '📨 What happens next?', k: ['what happens next', 'after i send', 'i sent the request', 'nobody contacted me', 'no reply', 'did not receive an answer', 'no answer'], a: `After you send the request, a FeelVoyage agent contacts you (for the contact form, within 2 working hours). If you haven't heard back, call **{phone}** or write to **{email}**.` },
          it: { t: '📨 Cosa succede dopo?', k: ['cosa succede dopo', 'dopo l invio', 'ho inviato la richiesta', 'nessuno mi ha contattato', 'nessuna risposta', 'non ho ricevuto risposta'], a: `Dopo l'invio della richiesta, un agente FeelVoyage ti contatta (per il modulo di contatto, entro 2 ore lavorative). Se non hai ricevuto risposta, chiama il **{phone}** o scrivi a **{email}**.` } },

        /* ==================================================== PLATĂ ==================================================== */
        { id: 'payment', next: ['installments', 'advance', 'pay-online'],
          ro: { t: '💳 Metode de plată', k: ['plata', 'plati', 'cum platesc', 'metode de plata', 'modalitati de plata', 'achitare', 'cum achit'], a: `Metode de plată: **transfer bancar**, **card** (Visa / Mastercard), **plata în rate** (pentru pachete peste 500 €) și **cash la sediu**. Modalitatea exactă o stabilești cu consultantul, după confirmarea ofertei.` },
          en: { t: '💳 Payment methods', k: ['payment', 'pay', 'how to pay', 'payment methods', 'payment options', 'ways to pay'], a: `Payment methods: **bank transfer**, **card** (Visa / Mastercard), **instalments** (for packages over 500 €) and **cash at the office**. You agree the exact method with your consultant once the offer is confirmed.` },
          it: { t: '💳 Metodi di pagamento', k: ['pagamento', 'pagare', 'come pagare', 'metodi di pagamento', 'modalita di pagamento', 'come si paga'], a: `Metodi di pagamento: **bonifico bancario**, **carta** (Visa / Mastercard), **pagamento a rate** (per pacchetti oltre 500 €) e **contanti in sede**. Concordi il metodo esatto con il tuo consulente dopo la conferma dell'offerta.` } },

        { id: 'installments', next: ['payment', 'advance'],
          ro: { t: '🧾 Plata în rate', k: ['rate', 'in rate', 'fara dobanda', 'plata in rate', 'ratele'], a: `Oferim **plata în rate**, pentru pachete peste 500 €, iar pentru anumite pachete **fără dobândă**. Cere detalii la **{phone}** sau **{email}**.` },
          en: { t: '🧾 Instalments', k: ['installments', 'instalments', 'in instalments', 'interest free', 'pay in parts', 'pay in installments'], a: `We offer **payment in instalments** for packages over 500 €, and **interest-free** on some packages. Ask for details at **{phone}** or **{email}**.` },
          it: { t: '🧾 Pagamento a rate', k: ['rate', 'a rate', 'senza interessi', 'pagamento rateale', 'rateizzare', 'pagare a rate'], a: `Offriamo il **pagamento a rate** per pacchetti oltre 500 € e **senza interessi** per alcuni pacchetti. Chiedi dettagli al **{phone}** o a **{email}**.` } },

        { id: 'card-pay', next: ['payment', 'pay-online'],
          ro: { t: '💳 Plata cu cardul', k: ['card', 'mastercard', 'visa mastercard', 'cu visa', 'plata cu cardul', 'cu cardul'], a: `Da, acceptăm plata cu **cardul** (Visa / Mastercard). Plata nu se face pe site: o stabilești cu consultantul după confirmarea ofertei.` },
          en: { t: '💳 Pay by card', k: ['card', 'mastercard', 'visa or mastercard', 'with visa', 'pay by card', 'credit card', 'debit card'], a: `Yes, we accept **card** payments (Visa / Mastercard). Payment isn't made on the site: you arrange it with your consultant after the offer is confirmed.` },
          it: { t: '💳 Pagare con carta', k: ['carta', 'mastercard', 'visa o mastercard', 'con visa', 'pagare con carta', 'carta di credito', 'carta di debito'], a: `Sì, accettiamo pagamenti con **carta** (Visa / Mastercard). Il pagamento non si fa sul sito: lo concordi con il consulente dopo la conferma dell'offerta.` } },

        { id: 'advance', next: ['payment', 'installments'],
          ro: { t: '💶 Avans', k: ['avans', 'garantie', 'cat platesc la inceput', 'plata avans', 'acont', 'plata in avans'], a: `Dacă se cere avans și cât anume depinde de pachet și se stabilește la confirmarea ofertei. Întreabă un consultant la **{phone}**.` },
          en: { t: '💶 Deposit', k: ['deposit', 'advance payment', 'down payment', 'how much upfront', 'upfront', 'pay in advance'], a: `Whether a deposit is required, and how much, depends on the package and is set when the offer is confirmed. Ask a consultant at **{phone}**.` },
          it: { t: '💶 Acconto', k: ['acconto', 'caparra', 'anticipo', 'quanto pago subito', 'pagamento anticipato'], a: `Se serve un acconto e quanto dipende dal pacchetto e si stabilisce alla conferma dell'offerta. Chiedi a un consulente al **{phone}**.` } },

        { id: 'invoice', next: ['payment', 'human'],
          ro: { t: '🧾 Factură', k: ['factura', 'factura fiscala', 'chitanta', 'acte contabile', 'pe firma', 'cui'], a: `Pentru factură (inclusiv pe firmă), spune-i consultantului datele la confirmarea rezervării. Detalii la **{phone}** sau **{email}**.` },
          en: { t: '🧾 Invoice', k: ['invoice', 'receipt', 'company invoice', 'vat', 'invoice for my company'], a: `For an invoice (including one for a company), give your consultant the details when the booking is confirmed. Details at **{phone}** or **{email}**.` },
          it: { t: '🧾 Fattura', k: ['fattura', 'ricevuta', 'fattura aziendale', 'partita iva', 'fattura per la mia azienda'], a: `Per la fattura (anche aziendale), comunica i dati al consulente alla conferma della prenotazione. Dettagli al **{phone}** o a **{email}**.` } },

        { id: 'vouchers', next: ['payment', 'human'],
          ro: { t: '🎟️ Tichete de vacanță', k: ['tichete de vacanta', 'voucher', 'card de vacanta', 'bonuri', 'tichete', 'vouchere'], a: `Pentru plata cu tichete/carduri de vacanță sau vouchere, întreabă un consultant dacă sunt acceptate pentru pachetul dorit: **{phone}**.` },
          en: { t: '🎟️ Holiday vouchers', k: ['holiday vouchers', 'vouchers', 'gift voucher', 'gift card', 'vacation vouchers'], a: `To pay with holiday vouchers, cards or gift vouchers, ask a consultant whether they're accepted for the package you want: **{phone}**.` },
          it: { t: '🎟️ Buoni vacanza', k: ['buoni vacanza', 'voucher', 'buono regalo', 'gift card', 'buoni'], a: `Per pagare con buoni vacanza, carte o voucher, chiedi a un consulente se sono accettati per il pacchetto che vuoi: **{phone}**.` } },

        { id: 'pay-online', next: ['book-online', 'payment'],
          ro: { t: '🌐 Plată pe site', k: ['pot plati pe site', 'plata pe site', 'platesc online', 'plata online', 'plata prin site', 'direct pe site', 'plati pe site'], a: `Momentan **nu se plătește pe site**: site-ul trimite solicitarea, iar plata se stabilește cu consultantul (transfer, card, rate sau cash).` },
          en: { t: '🌐 Pay on the site', k: ['pay on the website', 'pay online', 'online payment', 'pay on the site'], a: `At the moment you **don't pay on the site**: it sends your request, and payment is arranged with your consultant (transfer, card, instalments or cash).` },
          it: { t: '🌐 Pagare sul sito', k: ['pagare sul sito', 'pagamento online', 'pagare online', 'pagamento sul sito'], a: `Al momento **non si paga sul sito**: il sito invia la richiesta e il pagamento si concorda con il consulente (bonifico, carta, rate o contanti).` } }
    ]);
})(typeof window !== 'undefined' ? window : globalThis);
